
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jul  5 2024 12:01:51 IST (Jul  5 2024 06:31:51 UTC)

// Verification Directory fv/sdrc_xfr_ctl 

module sdrc_xfr_ctl(clk, reset_n, r2x_idle, b2x_idle, b2x_req,
     b2x_start, b2x_last, b2x_id, b2x_ba, b2x_addr, b2x_len, b2x_cmd,
     b2x_wrap, x2b_ack, b2x_tras_ok, x2b_refresh, x2b_pre_ok,
     x2b_act_ok, x2b_rdok, x2b_wrok, sdr_cs_n, sdr_cke, sdr_ras_n,
     sdr_cas_n, sdr_we_n, sdr_dqm, sdr_ba, sdr_addr, sdr_din, sdr_dout,
     sdr_den_n, x2a_rdstart, x2a_wrstart, x2a_rdlast, x2a_wrlast,
     x2a_id, a2x_wrdt, a2x_wren_n, x2a_wrnext, x2a_rddt, x2a_rdok,
     sdr_init_done, sdram_enable, sdram_mode_reg, xfr_bank_sel,
     cas_latency, trp_delay, trcar_delay, twr_delay, rfsh_time,
     rfsh_rmax);
  input clk, reset_n, r2x_idle, b2x_idle, b2x_req, b2x_start, b2x_last,
       b2x_wrap, b2x_tras_ok, sdram_enable;
  input [3:0] b2x_id, trp_delay, trcar_delay, twr_delay;
  input [1:0] b2x_ba, b2x_cmd, a2x_wren_n;
  input [12:0] b2x_addr, sdram_mode_reg;
  input [6:0] b2x_len;
  input [15:0] sdr_din, a2x_wrdt;
  input [2:0] cas_latency, rfsh_rmax;
  input [11:0] rfsh_time;
  output x2b_ack, x2b_refresh, x2b_act_ok, x2b_rdok, x2b_wrok,
       sdr_cs_n, sdr_cke, sdr_ras_n, sdr_cas_n, sdr_we_n, x2a_rdstart,
       x2a_wrstart, x2a_rdlast, x2a_wrlast, x2a_wrnext, x2a_rdok,
       sdr_init_done;
  output [3:0] x2b_pre_ok, x2a_id;
  output [1:0] sdr_dqm, sdr_ba, sdr_den_n, xfr_bank_sel;
  output [12:0] sdr_addr;
  output [15:0] sdr_dout, x2a_rddt;
  wire clk, reset_n, r2x_idle, b2x_idle, b2x_req, b2x_start, b2x_last,
       b2x_wrap, b2x_tras_ok, sdram_enable;
  wire [3:0] b2x_id, trp_delay, trcar_delay, twr_delay;
  wire [1:0] b2x_ba, b2x_cmd, a2x_wren_n;
  wire [12:0] b2x_addr, sdram_mode_reg;
  wire [6:0] b2x_len;
  wire [15:0] sdr_din, a2x_wrdt;
  wire [2:0] cas_latency, rfsh_rmax;
  wire [11:0] rfsh_time;
  wire x2b_ack, x2b_refresh, x2b_act_ok, x2b_rdok, x2b_wrok, sdr_cs_n,
       sdr_cke, sdr_ras_n, sdr_cas_n, sdr_we_n, x2a_rdstart,
       x2a_wrstart, x2a_rdlast, x2a_wrlast, x2a_wrnext, x2a_rdok,
       sdr_init_done;
  wire [3:0] x2b_pre_ok, x2a_id;
  wire [1:0] sdr_dqm, sdr_ba, sdr_den_n, xfr_bank_sel;
  wire [12:0] sdr_addr;
  wire [15:0] sdr_dout, x2a_rddt;
  wire [1:0] l_ba;
  wire [6:0] l_len;
  wire [3:0] l_id;
  wire [6:0] l_rd_next;
  wire [6:0] l_rd_last;
  wire [6:0] l_rd_start;
  wire [12:0] xfr_caddr;
  wire [2:0] mgmt_st;
  wire [1:0] xfr_st;
  wire [3:0] cntr1;
  wire [2:0] rfsh_row_cnt;
  wire [11:0] rfsh_timer;
  wire [3:0] tmr0;
  wire act_cmd, b2x_read, b2x_write, d_act_cmd, dec_SUB_UNS_OP_n_0,
       dec_SUB_UNS_OP_n_1, dec_SUB_UNS_OP_n_2, dec_SUB_UNS_OP_n_4;
  wire dec_SUB_UNS_OP_n_6, dec_sub_281_31_n_0, dec_sub_281_31_n_2,
       dec_sub_281_31_n_3, dec_sub_281_31_n_5, dec_sub_281_31_n_6,
       dec_sub_616_23_n_0, dec_sub_616_23_n_2;
  wire gte_631_35_n_0, gte_631_35_n_1, gte_631_35_n_2, gte_631_35_n_3,
       gte_631_35_n_4, inc_add_239_40_n_0, inc_add_239_40_n_2,
       inc_add_239_40_n_4;
  wire inc_add_239_40_n_5, inc_add_239_40_n_6, inc_add_239_40_n_8,
       inc_add_239_40_n_11, inc_add_239_40_n_12, inc_add_239_40_n_13,
       inc_add_239_40_n_16, inc_add_239_40_n_20;
  wire inc_add_620_50_n_0, inc_add_620_50_n_2, inc_add_620_50_n_4,
       inc_add_620_50_n_5, inc_add_620_50_n_6, inc_add_620_50_n_8,
       inc_add_620_50_n_11, inc_add_620_50_n_12;
  wire inc_add_620_50_n_14, inc_add_620_50_n_17, inc_add_622_36_n_0,
       l_last, l_start, l_wrap, l_xfr_end, last_burst;
  wire ld_xfr, n_0, n_1, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_89, n_90;
  wire n_91, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_116;
  wire n_117, n_118, n_119, n_120, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_134;
  wire n_135, n_136, n_138, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_155, n_156, n_157, n_158, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_223, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_235, n_236, n_237, n_238, n_239, n_240, n_241, n_242;
  wire n_243, n_244, n_245, n_246, n_247, n_248, n_249, n_250;
  wire n_251, n_252, n_253, n_254, n_255, n_256, n_257, n_258;
  wire n_259, n_260, n_261, n_262, n_263, n_264, n_265, n_266;
  wire n_267, n_268, n_269, n_270, n_271, n_272, n_273, n_274;
  wire n_275, n_276, n_277, n_278, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_286, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, n_294, n_295, n_296, n_297, n_298, n_299;
  wire n_300, n_301, n_302, n_303, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_311, n_312, n_313, n_314, n_315;
  wire n_316, n_317, n_318, n_319, n_320, n_321, n_322, n_323;
  wire n_324, n_325, n_326, n_327, n_328, n_329, n_330, n_331;
  wire n_332, n_333, n_334, n_335, n_336, n_337, n_338, n_339;
  wire n_340, n_341, n_342, n_343, n_344, n_345, n_346, n_347;
  wire n_348, n_349, n_350, n_351, n_352, n_353, n_354, n_355;
  wire n_356, n_357, n_358, n_359, n_360, n_361, n_362, n_363;
  wire n_364, n_366, n_367, n_368, n_369, n_370, n_371, n_372;
  wire n_373, n_374, n_375, n_376, n_377, n_378, n_380, n_381;
  wire n_382, n_383, n_384, n_385, n_386, n_387, n_388, n_389;
  wire n_390, n_391, n_392, n_394, n_395, n_396, n_397, n_398;
  wire n_399, n_400, n_401, n_402, n_403, n_404, n_405, n_406;
  wire n_407, n_408, n_409, n_410, n_411, n_412, n_413, n_414;
  wire n_415, n_416, n_418, n_419, n_420, n_421, n_422, n_423;
  wire n_424, n_425, n_426, n_427, n_428, n_429, n_430, n_431;
  wire n_432, n_433, n_434, n_435, n_436, n_437, n_438, n_439;
  wire n_440, n_441, n_442, n_446, n_451, n_453, n_455, n_456;
  wire n_457, n_458, n_459, n_460, n_461, n_462, n_463, n_464;
  wire n_465, n_466, n_467, n_468, n_469, n_470, n_471, n_472;
  wire n_473, n_474, n_475, n_476, n_477, n_478, n_479, n_480;
  wire n_481, n_482, n_483, n_484, n_485, n_486, n_487, n_488;
  wire n_489, n_490, n_491, n_492, n_493, n_494, n_495, n_496;
  wire n_497, n_502, n_503, n_504, n_505, n_506, n_507, n_508;
  wire n_570, n_572, n_583, n_599, n_600, n_616, n_617, n_635;
  wire n_636, n_637, n_638, n_639, n_640, n_641, n_642, n_643;
  wire n_644, n_645, n_646, n_647, rd_pipe_mt, sdr_init_done_1647;
  assign x2a_rddt[0] = sdr_din[0];
  assign x2a_rddt[1] = sdr_din[1];
  assign x2a_rddt[2] = sdr_din[2];
  assign x2a_rddt[3] = sdr_din[3];
  assign x2a_rddt[4] = sdr_din[4];
  assign x2a_rddt[5] = sdr_din[5];
  assign x2a_rddt[6] = sdr_din[6];
  assign x2a_rddt[7] = sdr_din[7];
  assign x2a_rddt[8] = sdr_din[8];
  assign x2a_rddt[9] = sdr_din[9];
  assign x2a_rddt[10] = sdr_din[10];
  assign x2a_rddt[11] = sdr_din[11];
  assign x2a_rddt[12] = sdr_din[12];
  assign x2a_rddt[13] = sdr_din[13];
  assign x2a_rddt[14] = sdr_din[14];
  assign x2a_rddt[15] = sdr_din[15];
  INVX1 g4621(.A (x2a_wrlast), .Y (n_453));
  INVX1 g4626(.A (x2b_pre_ok[2]), .Y (n_451));
  CLKINVX8 g4623(.A (n_502), .Y (x2b_pre_ok[3]));
  CLKINVX8 g4627(.A (n_502), .Y (x2b_pre_ok[2]));
  CLKINVX8 g4625(.A (n_502), .Y (x2b_pre_ok[1]));
  CLKINVX8 g4624(.A (n_502), .Y (x2b_pre_ok[0]));
  CLKINVX8 g4622(.A (n_635), .Y (x2a_wrlast));
  INVX1 g4628(.A (d_act_cmd), .Y (n_446));
  BUFX8 g4630(.A (sdr_init_done_1647), .Y (sdr_init_done));
  BUFX8 g4631(.A (l_ba[1]), .Y (xfr_bank_sel[1]));
  BUFX8 g4632(.A (l_ba[0]), .Y (xfr_bank_sel[0]));
  INVX1 g4629(.A (act_cmd), .Y (n_442));
  OR4X1 g4964__2398(.A (n_440), .B (n_434), .C (n_433), .D (n_441), .Y
       (n_635));
  NAND4XL g4965__5107(.A (n_432), .B (n_431), .C (n_430), .D (n_429),
       .Y (n_441));
  INVX1 g4966(.A (n_440), .Y (last_burst));
  AND3X1 g4967__6260(.A (b2x_start), .B (n_352), .C (n_420), .Y
       (n_439));
  OR2X1 g4968__4319(.A (n_422), .B (n_426), .Y (n_438));
  OR2X1 g4969__8428(.A (n_427), .B (n_428), .Y (n_437));
  OR2X1 g4970__5526(.A (n_425), .B (n_423), .Y (n_436));
  OR2X1 g4971__6783(.A (n_424), .B (n_421), .Y (n_435));
  AOI22X1 g4972__3680(.A0 (b2x_last), .A1 (n_420), .B0 (l_last), .B1
       (ld_xfr), .Y (n_440));
  MX2XL g4973__1617(.A (b2x_len[2]), .B (l_len[2]), .S0 (ld_xfr), .Y
       (n_434));
  MX2XL g4974__2802(.A (b2x_len[1]), .B (l_len[1]), .S0 (ld_xfr), .Y
       (n_433));
  AOI22XL g4975__1705(.A0 (b2x_len[6]), .A1 (n_420), .B0 (l_len[6]),
       .B1 (ld_xfr), .Y (n_432));
  AOI22XL g4976__5122(.A0 (b2x_len[5]), .A1 (n_420), .B0 (l_len[5]),
       .B1 (ld_xfr), .Y (n_431));
  AOI22XL g4977__8246(.A0 (b2x_len[4]), .A1 (n_420), .B0 (l_len[4]),
       .B1 (ld_xfr), .Y (n_430));
  AOI22XL g4978__7098(.A0 (b2x_len[3]), .A1 (n_420), .B0 (l_len[3]),
       .B1 (ld_xfr), .Y (n_429));
  NOR2BX1 g4979__6131(.AN (b2x_id[2]), .B (ld_xfr), .Y (n_428));
  NOR2BX1 g4980__1881(.AN (l_id[2]), .B (n_420), .Y (n_427));
  NOR2BX1 g4981__5115(.AN (b2x_id[3]), .B (ld_xfr), .Y (n_426));
  NOR2BX1 g4982__7482(.AN (l_id[1]), .B (n_420), .Y (n_425));
  NOR2BX1 g4983__4733(.AN (l_id[0]), .B (n_420), .Y (n_424));
  NOR2BX1 g4984__6161(.AN (b2x_id[1]), .B (ld_xfr), .Y (n_423));
  NOR2BX1 g4985__9315(.AN (l_id[3]), .B (n_420), .Y (n_422));
  NOR2BX1 g4986__9945(.AN (b2x_id[0]), .B (ld_xfr), .Y (n_421));
  INVX1 g4987(.A (ld_xfr), .Y (n_420));
  NAND2X2 g4988__2883(.A (n_361), .B (n_419), .Y (ld_xfr));
  CLKBUFX20 g4989(.A (n_419), .Y (x2b_ack));
  OAI21X1 g4990__2346(.A0 (n_504), .A1 (n_412), .B0 (n_636), .Y
       (n_419));
  OR2X1 g4991__1666(.A (n_415), .B (n_416), .Y (n_418));
  NOR3BX1 g4993__6417(.AN (b2x_req), .B (b2x_write), .C (n_409), .Y
       (n_416));
  OAI32X1 g4994__5477(.A0 (n_570), .A1 (b2x_write), .A2 (n_583), .B0
       (n_503), .B1 (n_408), .Y (n_415));
  OR2X1 g4995__2398(.A (n_398), .B (n_413), .Y (n_414));
  OAI21X1 g4996__5107(.A0 (n_583), .A1 (n_367), .B0 (n_409), .Y
       (n_413));
  NOR2X1 g4997__6260(.A (n_403), .B (n_410), .Y (n_412));
  OAI32X1 g4998__4319(.A0 (n_637), .A1 (n_616), .A2 (n_457), .B0
       (n_616), .B1 (n_402), .Y (n_411));
  NAND2X1 g4999__8428(.A (n_400), .B (n_404), .Y (n_410));
  AOI31X1 g5000__5526(.A0 (b2x_req), .A1 (n_352), .A2 (n_390), .B0
       (l_xfr_end), .Y (n_408));
  NAND3BXL g5001__6783(.AN (n_506), .B (rd_pipe_mt), .C (n_366), .Y
       (n_409));
  OR2X1 g5002__3680(.A (n_396), .B (n_386), .Y (n_407));
  OR2X1 g5003__1617(.A (n_395), .B (n_387), .Y (n_406));
  OR2X1 g5004__2802(.A (n_397), .B (n_385), .Y (n_405));
  OAI211X1 g5005__1705(.A0 (n_376), .A1 (n_373), .B0 (n_394), .C0
       (n_382), .Y (rd_pipe_mt));
  OAI211X1 g5006__5122(.A0 (n_354), .A1 (n_637), .B0 (n_375), .C0
       (n_392), .Y (n_404));
  NOR3X1 g5007__8246(.A (n_616), .B (n_352), .C (n_457), .Y (n_403));
  AOI21X1 g5008__7098(.A0 (n_361), .A1 (n_392), .B0 (n_391), .Y
       (n_402));
  OR2X1 g5009__6131(.A (n_374), .B (n_399), .Y (n_401));
  NAND2X1 g5010__1881(.A (b2x_req), .B (n_391), .Y (n_400));
  NOR2X1 g5012__5115(.A (n_503), .B (n_572), .Y (n_398));
  OAI2BB1X1 g5013__7482(.A0N (l_rd_next[2]), .A1N (n_360), .B0 (n_388),
       .Y (n_397));
  OAI2BB1X1 g5014__4733(.A0N (l_rd_last[2]), .A1N (n_360), .B0 (n_383),
       .Y (n_396));
  OAI2BB1X1 g5015__6161(.A0N (l_rd_start[2]), .A1N (n_360), .B0
       (n_384), .Y (n_395));
  AOI222X1 g5016__9315(.A0 (n_350), .A1 (n_360), .B0 (n_364), .B1
       (n_372), .C0 (n_362), .C1 (n_363), .Y (n_394));
  INVX1 g5017(.A (n_391), .Y (n_456));
  INVX1 g5018(.A (n_572), .Y (n_390));
  OAI21X1 g5019__9945(.A0 (n_506), .A1 (n_616), .B0 (n_570), .Y
       (n_389));
  AND2X1 g5023__2346(.A (n_617), .B (l_xfr_end), .Y (n_391));
  NAND2X1 g5024__1666(.A (n_366), .B (n_380), .Y (n_572));
  AOI22X1 g5025__7410(.A0 (l_rd_next[4]), .A1 (n_372), .B0
       (l_rd_next[3]), .B1 (n_363), .Y (n_388));
  OAI2BB1X1 g5026__6417(.A0N (l_rd_start[6]), .A1N (n_371), .B0
       (n_381), .Y (n_387));
  OAI2BB1X1 g5027__5477(.A0N (l_rd_last[6]), .A1N (n_371), .B0 (n_377),
       .Y (n_386));
  OAI2BB1X1 g5028__2398(.A0N (l_rd_next[6]), .A1N (n_371), .B0 (n_378),
       .Y (n_385));
  AOI22X1 g5029__5107(.A0 (l_rd_start[4]), .A1 (n_372), .B0
       (l_rd_start[3]), .B1 (n_363), .Y (n_384));
  AOI22X1 g5030__6260(.A0 (l_rd_last[4]), .A1 (n_372), .B0
       (l_rd_last[3]), .B1 (n_363), .Y (n_383));
  OR3XL g5031__4319(.A (l_rd_next[5]), .B (n_376), .C (n_370), .Y
       (n_382));
  NAND2BXL g5032__8428(.AN (n_373), .B (l_rd_start[5]), .Y (n_381));
  NAND2X1 g5034__5526(.A (sdr_init_done_1647), .B (n_375), .Y (n_570));
  INVX1 g5035(.A (l_xfr_end), .Y (n_380));
  NAND2BXL g5037__6783(.AN (n_373), .B (l_rd_next[5]), .Y (n_378));
  NAND2BXL g5038__3680(.AN (n_373), .B (l_rd_last[5]), .Y (n_377));
  OR3X1 g5039__1617(.A (n_369), .B (n_471), .C (n_470), .Y (l_xfr_end));
  INVX1 g5041(.A (n_616), .Y (n_375));
  NOR2BX1 g5042__2802(.AN (n_505), .B (n_367), .Y (n_374));
  NAND2X1 g5043__1705(.A (n_505), .B (n_367), .Y (n_455));
  NAND2BX1 g5044__5122(.AN (l_rd_next[4]), .B (n_364), .Y (n_376));
  NAND2X1 g5045__8246(.A (b2x_req), .B (n_366), .Y (n_616));
  INVX1 g5046(.A (n_371), .Y (n_370));
  NAND3BXL g5047__7098(.AN (n_472), .B (l_len[0]), .C (n_356), .Y
       (n_369));
  OAI221X1 g5048__6131(.A0 (n_346), .A1 (l_ba[1]), .B0 (n_347), .B1
       (b2x_ba[1]), .C0 (n_355), .Y (n_368));
  NOR4BX1 g5051__1881(.AN (n_358), .B (n_357), .C (n_360), .D (n_359),
       .Y (n_371));
  INVX1 g5052(.A (n_366), .Y (n_367));
  NAND2X1 g5054__5115(.A (n_599), .B (n_508), .Y (n_366));
  NOR2BX1 g5055__7482(.AN (n_362), .B (l_rd_next[3]), .Y (n_364));
  NOR2BX1 g5058__4733(.AN (n_350), .B (l_rd_next[2]), .Y (n_362));
  NAND2X1 g5059__6161(.A (b2x_write), .B (b2x_read), .Y (n_361));
  NAND2X1 g5060__9315(.A (xfr_caddr[0]), .B (n_351), .Y (n_617));
  NAND3BX1 g5062__9945(.AN (mgmt_st[2]), .B (mgmt_st[0]), .C
       (mgmt_st[1]), .Y (n_507));
  NAND2X1 g5063__2883(.A (n_506), .B (n_583), .Y (n_505));
  NOR3BX1 g5064__2346(.AN (cas_latency[0]), .B (cas_latency[2]), .C
       (cas_latency[1]), .Y (n_360));
  NOR4X1 g5065__1666(.A (1'b0), .B (n_475), .C (n_474), .D (n_473), .Y
       (n_356));
  XNOR2X1 g5066__7410(.A (l_ba[0]), .B (b2x_ba[0]), .Y (n_355));
  NOR3BX1 g5067__6417(.AN (cas_latency[2]), .B (cas_latency[0]), .C
       (cas_latency[1]), .Y (n_359));
  OR3X1 g5068__5477(.A (mgmt_st[1]), .B (mgmt_st[0]), .C (mgmt_st[2]),
       .Y (n_508));
  NAND2BX1 g5069__2398(.AN (n_349), .B (mgmt_st[1]), .Y (n_599));
  NAND3BXL g5070__5107(.AN (cas_latency[2]), .B (cas_latency[0]), .C
       (cas_latency[1]), .Y (n_358));
  NOR3BX1 g5071__6260(.AN (cas_latency[1]), .B (cas_latency[0]), .C
       (cas_latency[2]), .Y (n_357));
  INVX1 g5072(.A (b2x_read), .Y (n_354));
  INVX1 g5074(.A (n_503), .Y (n_353));
  INVX1 g5075(.A (b2x_write), .Y (n_352));
  NOR2X1 g5076__4319(.A (n_490), .B (l_wrap), .Y (n_351));
  NAND2BX1 g5077__8428(.AN (b2x_cmd[0]), .B (b2x_cmd[1]), .Y
       (b2x_read));
  NAND2BX1 g5078__5526(.AN (xfr_st[0]), .B (xfr_st[1]), .Y (n_504));
  NAND2BX1 g5079__6783(.AN (xfr_st[1]), .B (xfr_st[0]), .Y (n_503));
  NAND2X1 g5080__3680(.A (b2x_cmd[1]), .B (b2x_cmd[0]), .Y (b2x_write));
  NAND2X1 g5081__1617(.A (mgmt_st[0]), .B (mgmt_st[2]), .Y (n_349));
  AND2X4 g5082__2802(.A (n_442), .B (n_446), .Y (n_348));
  NOR2X1 g5083__1705(.A (l_rd_next[0]), .B (l_rd_next[1]), .Y (n_350));
  NAND2X1 g5084__5122(.A (xfr_st[0]), .B (xfr_st[1]), .Y (n_506));
  OR2X1 g5085__8246(.A (xfr_st[0]), .B (xfr_st[1]), .Y (n_583));
  INVX1 g5086(.A (l_ba[1]), .Y (n_347));
  INVX1 g5087(.A (b2x_ba[1]), .Y (n_346));
  CLKBUFX20 drc_bufs(.A (n_345), .Y (x2b_refresh));
  CLKBUFX20 drc_bufs5088(.A (n_439), .Y (x2a_wrstart));
  CLKBUFX20 drc_bufs5089(.A (n_348), .Y (x2b_act_ok));
  CLKBUFX20 drc_bufs5090(.A (n_438), .Y (x2a_id[3]));
  CLKBUFX20 drc_bufs5091(.A (n_405), .Y (x2a_rdok));
  CLKBUFX20 drc_bufs5092(.A (n_436), .Y (x2a_id[1]));
  CLKBUFX20 drc_bufs5093(.A (n_435), .Y (x2a_id[0]));
  CLKBUFX20 drc_bufs5094(.A (n_437), .Y (x2a_id[2]));
  CLKBUFX20 drc_bufs5095(.A (n_418), .Y (x2a_wrnext));
  CLKBUFX20 drc_bufs5096(.A (n_401), .Y (x2b_rdok));
  CLKBUFX20 drc_bufs5097(.A (n_406), .Y (x2a_rdstart));
  CLKBUFX20 drc_bufs5098(.A (n_414), .Y (x2b_wrok));
  CLKBUFX20 drc_bufs5099(.A (n_407), .Y (x2a_rdlast));
  NOR2XL g2__7098(.A (n_507), .B (n_455), .Y (n_345));
  NAND2BX4 g5128__6131(.AN (n_353), .B (n_504), .Y (n_502));
  DFFHQX1 act_cmd_reg(.CK (clk), .D (n_638), .Q (act_cmd));
  DFFHQX1 \cntr1_reg[0] (.CK (clk), .D (n_182), .Q (cntr1[0]));
  DFFHQX1 \cntr1_reg[1] (.CK (clk), .D (n_179), .Q (cntr1[1]));
  DFFHQX1 \cntr1_reg[2] (.CK (clk), .D (n_177), .Q (cntr1[2]));
  DFFHQX1 \cntr1_reg[3] (.CK (clk), .D (n_646), .Q (cntr1[3]));
  DFFHQX1 d_act_cmd_reg(.CK (clk), .D (n_48), .Q (d_act_cmd));
  DFFHQX1 \l_ba_reg[0] (.CK (clk), .D (n_109), .Q (l_ba[0]));
  DFFHQX1 \l_ba_reg[1] (.CK (clk), .D (n_110), .Q (l_ba[1]));
  DFFHQX1 \l_id_reg[0] (.CK (clk), .D (n_29), .Q (l_id[0]));
  DFFHQX1 \l_id_reg[1] (.CK (clk), .D (n_36), .Q (l_id[1]));
  DFFHQX1 \l_id_reg[2] (.CK (clk), .D (n_35), .Q (l_id[2]));
  DFFHQX1 \l_id_reg[3] (.CK (clk), .D (n_33), .Q (l_id[3]));
  DFFHQX1 l_last_reg(.CK (clk), .D (n_24), .Q (l_last));
  DFFHQX1 \l_len_reg[0] (.CK (clk), .D (n_156), .Q (l_len[0]));
  DFFHQX1 \l_len_reg[1] (.CK (clk), .D (n_639), .Q (l_len[1]));
  DFFHQX1 \l_len_reg[2] (.CK (clk), .D (n_161), .Q (l_len[2]));
  DFFHQX1 \l_len_reg[3] (.CK (clk), .D (n_150), .Q (l_len[3]));
  DFFHQX1 \l_len_reg[4] (.CK (clk), .D (n_155), .Q (l_len[4]));
  DFFHQX1 \l_len_reg[5] (.CK (clk), .D (n_640), .Q (l_len[5]));
  DFFHQX1 \l_len_reg[6] (.CK (clk), .D (n_153), .Q (l_len[6]));
  DFFHQX1 \l_rd_last_reg[0] (.CK (clk), .D (n_194), .Q (l_rd_last[0]));
  DFFHQX1 \l_rd_last_reg[1] (.CK (clk), .D (n_30), .Q (l_rd_last[1]));
  DFFHQX1 \l_rd_last_reg[2] (.CK (clk), .D (n_32), .Q (l_rd_last[2]));
  DFFHQX1 \l_rd_last_reg[3] (.CK (clk), .D (n_38), .Q (l_rd_last[3]));
  DFFHQX1 \l_rd_last_reg[4] (.CK (clk), .D (n_51), .Q (l_rd_last[4]));
  DFFHQX1 \l_rd_last_reg[5] (.CK (clk), .D (n_53), .Q (l_rd_last[5]));
  DFFHQX1 \l_rd_last_reg[6] (.CK (clk), .D (n_52), .Q (l_rd_last[6]));
  DFFHQX1 \l_rd_next_reg[0] (.CK (clk), .D (n_188), .Q (l_rd_next[0]));
  DFFHQX1 \l_rd_next_reg[1] (.CK (clk), .D (n_46), .Q (l_rd_next[1]));
  DFFHQX1 \l_rd_next_reg[2] (.CK (clk), .D (n_55), .Q (l_rd_next[2]));
  DFFHQX1 \l_rd_next_reg[3] (.CK (clk), .D (n_49), .Q (l_rd_next[3]));
  DFFHQX1 \l_rd_next_reg[4] (.CK (clk), .D (n_37), .Q (l_rd_next[4]));
  DFFHQX1 \l_rd_next_reg[5] (.CK (clk), .D (n_59), .Q (l_rd_next[5]));
  DFFHQX1 \l_rd_next_reg[6] (.CK (clk), .D (n_50), .Q (l_rd_next[6]));
  DFFHQX1 \l_rd_start_reg[0] (.CK (clk), .D (n_106), .Q
       (l_rd_start[0]));
  DFFHQX1 \l_rd_start_reg[1] (.CK (clk), .D (n_47), .Q (l_rd_start[1]));
  DFFHQX1 \l_rd_start_reg[2] (.CK (clk), .D (n_27), .Q (l_rd_start[2]));
  DFFHQX1 \l_rd_start_reg[3] (.CK (clk), .D (n_56), .Q (l_rd_start[3]));
  DFFHQX1 \l_rd_start_reg[4] (.CK (clk), .D (n_26), .Q (l_rd_start[4]));
  DFFHQX1 \l_rd_start_reg[5] (.CK (clk), .D (n_34), .Q (l_rd_start[5]));
  DFFHQX1 \l_rd_start_reg[6] (.CK (clk), .D (n_25), .Q (l_rd_start[6]));
  DFFHQX1 l_start_reg(.CK (clk), .D (n_160), .Q (l_start));
  DFFHQX1 l_wrap_reg(.CK (clk), .D (n_107), .Q (l_wrap));
  DFFHQX1 \mgmt_st_reg[0] (.CK (clk), .D (n_237), .Q (mgmt_st[0]));
  DFFHQX1 \mgmt_st_reg[1] (.CK (clk), .D (n_205), .Q (mgmt_st[1]));
  DFFHQX1 \mgmt_st_reg[2] (.CK (clk), .D (n_187), .Q (mgmt_st[2]));
  SDFFQX1 \rfsh_row_cnt_reg[0] (.CK (clk), .D (n_259), .SI (n_214), .SE
       (rfsh_row_cnt[0]), .Q (rfsh_row_cnt[0]));
  DFFHQX1 \rfsh_row_cnt_reg[1] (.CK (clk), .D (n_290), .Q
       (rfsh_row_cnt[1]));
  DFFHQX1 \rfsh_row_cnt_reg[2] (.CK (clk), .D (n_291), .Q
       (rfsh_row_cnt[2]));
  DFFHQX1 \rfsh_timer_reg[0] (.CK (clk), .D (n_225), .Q
       (rfsh_timer[0]));
  DFFHQX1 \rfsh_timer_reg[1] (.CK (clk), .D (n_224), .Q
       (rfsh_timer[1]));
  DFFHQX1 \rfsh_timer_reg[2] (.CK (clk), .D (n_223), .Q
       (rfsh_timer[2]));
  DFFHQX1 \rfsh_timer_reg[3] (.CK (clk), .D (n_222), .Q
       (rfsh_timer[3]));
  DFFHQX1 \rfsh_timer_reg[4] (.CK (clk), .D (n_221), .Q
       (rfsh_timer[4]));
  DFFHQX1 \rfsh_timer_reg[5] (.CK (clk), .D (n_220), .Q
       (rfsh_timer[5]));
  DFFHQX1 \rfsh_timer_reg[6] (.CK (clk), .D (n_219), .Q
       (rfsh_timer[6]));
  DFFHQX1 \rfsh_timer_reg[7] (.CK (clk), .D (n_218), .Q
       (rfsh_timer[7]));
  DFFHQX1 \rfsh_timer_reg[8] (.CK (clk), .D (n_217), .Q
       (rfsh_timer[8]));
  DFFHQX1 \rfsh_timer_reg[9] (.CK (clk), .D (n_216), .Q
       (rfsh_timer[9]));
  DFFHQX1 \rfsh_timer_reg[10] (.CK (clk), .D (n_213), .Q
       (rfsh_timer[10]));
  DFFHQX1 \rfsh_timer_reg[11] (.CK (clk), .D (n_212), .Q
       (rfsh_timer[11]));
  DFFHQX1 \sdr_addr_reg[0] (.CK (clk), .D (n_295), .Q (n_323));
  DFFHQX1 \sdr_addr_reg[1] (.CK (clk), .D (n_301), .Q (n_324));
  DFFHQX1 \sdr_addr_reg[2] (.CK (clk), .D (n_302), .Q (n_325));
  DFFHQX1 \sdr_addr_reg[3] (.CK (clk), .D (n_300), .Q (n_326));
  DFFHQX1 \sdr_addr_reg[4] (.CK (clk), .D (n_299), .Q (n_327));
  DFFHQX1 \sdr_addr_reg[5] (.CK (clk), .D (n_298), .Q (n_328));
  DFFHQX1 \sdr_addr_reg[6] (.CK (clk), .D (n_297), .Q (n_329));
  DFFHQX1 \sdr_addr_reg[7] (.CK (clk), .D (n_296), .Q (n_330));
  DFFHQX1 \sdr_addr_reg[8] (.CK (clk), .D (n_303), .Q (n_331));
  DFFHQX1 \sdr_addr_reg[9] (.CK (clk), .D (n_287), .Q (n_332));
  DFFHQX1 \sdr_addr_reg[10] (.CK (clk), .D (n_304), .Q (n_333));
  DFFHQX1 \sdr_addr_reg[11] (.CK (clk), .D (n_289), .Q (n_334));
  DFFHQX1 \sdr_addr_reg[12] (.CK (clk), .D (n_294), .Q (n_335));
  DFFHQX1 \sdr_ba_reg[0] (.CK (clk), .D (n_288), .Q (n_336));
  DFFHQX1 \sdr_ba_reg[1] (.CK (clk), .D (n_292), .Q (n_337));
  DFFHQX1 sdr_cas_n_reg(.CK (clk), .D (n_192), .Q (n_341));
  DFFHQX1 sdr_cke_reg(.CK (clk), .D (n_105), .Q (n_343));
  DFFHQX1 sdr_cs_n_reg(.CK (clk), .D (n_207), .Q (n_344));
  DFFHQX1 \sdr_den_n_reg[0] (.CK (clk), .D (n_44), .Q (n_305));
  DFFHQX1 \sdr_den_n_reg[1] (.CK (clk), .D (n_44), .Q (n_306));
  SDFFQX1 \sdr_dout_reg[0] (.CK (clk), .D (n_307), .SI (a2x_wrdt[0]),
       .SE (n_8), .Q (n_307));
  SDFFQX1 \sdr_dout_reg[1] (.CK (clk), .D (n_308), .SI (a2x_wrdt[1]),
       .SE (n_8), .Q (n_308));
  SDFFQX1 \sdr_dout_reg[2] (.CK (clk), .D (n_309), .SI (a2x_wrdt[2]),
       .SE (n_8), .Q (n_309));
  SDFFQX1 \sdr_dout_reg[3] (.CK (clk), .D (n_310), .SI (a2x_wrdt[3]),
       .SE (n_8), .Q (n_310));
  SDFFQX1 \sdr_dout_reg[4] (.CK (clk), .D (n_311), .SI (a2x_wrdt[4]),
       .SE (n_8), .Q (n_311));
  SDFFQX1 \sdr_dout_reg[5] (.CK (clk), .D (n_312), .SI (a2x_wrdt[5]),
       .SE (n_8), .Q (n_312));
  SDFFQX1 \sdr_dout_reg[6] (.CK (clk), .D (n_313), .SI (a2x_wrdt[6]),
       .SE (n_8), .Q (n_313));
  SDFFQX1 \sdr_dout_reg[7] (.CK (clk), .D (n_314), .SI (a2x_wrdt[7]),
       .SE (n_8), .Q (n_314));
  SDFFQX1 \sdr_dout_reg[8] (.CK (clk), .D (n_315), .SI (a2x_wrdt[8]),
       .SE (n_8), .Q (n_315));
  SDFFQX1 \sdr_dout_reg[9] (.CK (clk), .D (n_316), .SI (a2x_wrdt[9]),
       .SE (n_8), .Q (n_316));
  SDFFQX1 \sdr_dout_reg[10] (.CK (clk), .D (n_317), .SI (a2x_wrdt[10]),
       .SE (n_8), .Q (n_317));
  SDFFQX1 \sdr_dout_reg[11] (.CK (clk), .D (n_318), .SI (a2x_wrdt[11]),
       .SE (n_8), .Q (n_318));
  SDFFQX1 \sdr_dout_reg[12] (.CK (clk), .D (n_319), .SI (a2x_wrdt[12]),
       .SE (n_8), .Q (n_319));
  SDFFQX1 \sdr_dout_reg[13] (.CK (clk), .D (n_320), .SI (a2x_wrdt[13]),
       .SE (n_8), .Q (n_320));
  SDFFQX1 \sdr_dout_reg[14] (.CK (clk), .D (n_321), .SI (a2x_wrdt[14]),
       .SE (n_8), .Q (n_321));
  SDFFQX1 \sdr_dout_reg[15] (.CK (clk), .D (n_322), .SI (a2x_wrdt[15]),
       .SE (n_8), .Q (n_322));
  DFFHQX1 \sdr_dqm_reg[0] (.CK (clk), .D (n_104), .Q (n_338));
  DFFHQX1 \sdr_dqm_reg[1] (.CK (clk), .D (n_103), .Q (n_339));
  DFFHQX1 sdr_init_done_reg(.CK (clk), .D (n_108), .Q
       (sdr_init_done_1647));
  DFFHQX1 sdr_ras_n_reg(.CK (clk), .D (n_193), .Q (n_342));
  DFFHQX1 sdr_we_n_reg(.CK (clk), .D (n_211), .Q (n_340));
  DFFHQX1 \tmr0_reg[0] (.CK (clk), .D (n_209), .Q (tmr0[0]));
  DFFHQX1 \tmr0_reg[1] (.CK (clk), .D (n_204), .Q (tmr0[1]));
  DFFHQX1 \tmr0_reg[2] (.CK (clk), .D (n_203), .Q (tmr0[2]));
  DFFHQX1 \tmr0_reg[3] (.CK (clk), .D (n_208), .Q (tmr0[3]));
  DFFHQX1 \xfr_caddr_reg[0] (.CK (clk), .D (n_253), .Q (xfr_caddr[0]));
  DFFHQX1 \xfr_caddr_reg[1] (.CK (clk), .D (n_256), .Q (xfr_caddr[1]));
  DFFHQX1 \xfr_caddr_reg[2] (.CK (clk), .D (n_258), .Q (xfr_caddr[2]));
  DFFHQX1 \xfr_caddr_reg[3] (.CK (clk), .D (n_254), .Q (xfr_caddr[3]));
  DFFHQX1 \xfr_caddr_reg[4] (.CK (clk), .D (n_255), .Q (xfr_caddr[4]));
  DFFHQX1 \xfr_caddr_reg[5] (.CK (clk), .D (n_245), .Q (xfr_caddr[5]));
  DFFHQX1 \xfr_caddr_reg[6] (.CK (clk), .D (n_252), .Q (xfr_caddr[6]));
  DFFHQX1 \xfr_caddr_reg[7] (.CK (clk), .D (n_251), .Q (xfr_caddr[7]));
  DFFHQX1 \xfr_caddr_reg[8] (.CK (clk), .D (n_250), .Q (xfr_caddr[8]));
  DFFHQX1 \xfr_caddr_reg[9] (.CK (clk), .D (n_249), .Q (xfr_caddr[9]));
  DFFHQX1 \xfr_caddr_reg[10] (.CK (clk), .D (n_248), .Q
       (xfr_caddr[10]));
  DFFHQX1 \xfr_caddr_reg[11] (.CK (clk), .D (n_247), .Q
       (xfr_caddr[11]));
  DFFHQX1 \xfr_caddr_reg[12] (.CK (clk), .D (n_246), .Q
       (xfr_caddr[12]));
  DFFHQX1 \xfr_st_reg[0] (.CK (clk), .D (n_206), .Q (xfr_st[0]));
  DFFHQX1 \xfr_st_reg[1] (.CK (clk), .D (n_185), .Q (xfr_st[1]));
  NAND2X1 g6095__1881(.A (n_266), .B (n_293), .Y (n_304));
  NAND2X1 g6104__5115(.A (n_268), .B (n_270), .Y (n_303));
  NAND2X1 g6105__7482(.A (n_281), .B (n_286), .Y (n_302));
  NAND2X1 g6106__4733(.A (n_283), .B (n_282), .Y (n_301));
  NAND2X1 g6107__6161(.A (n_280), .B (n_279), .Y (n_300));
  NAND2X1 g6108__9315(.A (n_278), .B (n_277), .Y (n_299));
  NAND2X1 g6109__9945(.A (n_276), .B (n_275), .Y (n_298));
  NAND2X1 g6110__2883(.A (n_274), .B (n_273), .Y (n_297));
  NAND2X1 g6111__2346(.A (n_272), .B (n_271), .Y (n_296));
  OAI211X1 g6113__1666(.A0 (xfr_caddr[0]), .A1 (n_242), .B0 (n_284),
       .C0 (n_257), .Y (n_295));
  NAND2X1 g6114__7410(.A (n_264), .B (n_263), .Y (n_294));
  AOI222X1 g6115__6417(.A0 (n_333), .A1 (n_196), .B0 (n_467), .B1
       (n_243), .C0 (b2x_addr[10]), .C1 (n_241), .Y (n_293));
  OAI2BB1X1 g6116__5477(.A0N (b2x_ba[1]), .A1N (n_241), .B0 (n_261), .Y
       (n_292));
  AO22XL g6117__2398(.A0 (n_478), .A1 (n_259), .B0 (rfsh_row_cnt[2]),
       .B1 (n_214), .Y (n_291));
  AO22XL g6118__5107(.A0 (n_477), .A1 (n_259), .B0 (rfsh_row_cnt[1]),
       .B1 (n_214), .Y (n_290));
  OAI211X1 g6119__6260(.A0 (n_12), .A1 (n_242), .B0 (n_265), .C0
       (n_260), .Y (n_289));
  OAI211X1 g6120__4319(.A0 (n_11), .A1 (n_240), .B0 (n_262), .C0
       (n_260), .Y (n_288));
  NAND2X1 g6121__8428(.A (n_269), .B (n_267), .Y (n_287));
  AOI22X1 g6122__5526(.A0 (sdram_mode_reg[2]), .A1 (n_244), .B0
       (b2x_addr[2]), .B1 (n_241), .Y (n_286));
  AOI22X1 g6124__3680(.A0 (b2x_addr[0]), .A1 (n_241), .B0 (n_323), .B1
       (n_196), .Y (n_284));
  AOI22X1 g6125__1617(.A0 (b2x_addr[1]), .A1 (n_241), .B0 (n_324), .B1
       (n_196), .Y (n_283));
  AOI22X1 g6126__2802(.A0 (sdram_mode_reg[1]), .A1 (n_244), .B0
       (n_458), .B1 (n_243), .Y (n_282));
  AOI22X1 g6127__1705(.A0 (n_459), .A1 (n_243), .B0 (n_325), .B1
       (n_196), .Y (n_281));
  AOI22X1 g6141__5122(.A0 (b2x_addr[3]), .A1 (n_241), .B0 (n_326), .B1
       (n_196), .Y (n_280));
  AOI22X1 g6142__8246(.A0 (sdram_mode_reg[3]), .A1 (n_244), .B0
       (n_460), .B1 (n_243), .Y (n_279));
  AOI22X1 g6143__7098(.A0 (b2x_addr[4]), .A1 (n_241), .B0 (n_327), .B1
       (n_196), .Y (n_278));
  AOI22X1 g6144__6131(.A0 (sdram_mode_reg[4]), .A1 (n_244), .B0
       (n_461), .B1 (n_243), .Y (n_277));
  AOI22X1 g6145__1881(.A0 (n_462), .A1 (n_243), .B0 (n_328), .B1
       (n_196), .Y (n_276));
  AOI22X1 g6146__5115(.A0 (sdram_mode_reg[5]), .A1 (n_244), .B0
       (b2x_addr[5]), .B1 (n_241), .Y (n_275));
  AOI22X1 g6147__7482(.A0 (n_463), .A1 (n_243), .B0 (n_329), .B1
       (n_196), .Y (n_274));
  AOI22X1 g6148__4733(.A0 (sdram_mode_reg[6]), .A1 (n_244), .B0
       (b2x_addr[6]), .B1 (n_241), .Y (n_273));
  AOI22X1 g6149__6161(.A0 (n_464), .A1 (n_243), .B0 (n_330), .B1
       (n_196), .Y (n_272));
  AOI22X1 g6150__9315(.A0 (sdram_mode_reg[7]), .A1 (n_244), .B0
       (b2x_addr[7]), .B1 (n_241), .Y (n_271));
  AOI22X1 g6151__9945(.A0 (sdram_mode_reg[8]), .A1 (n_244), .B0
       (n_465), .B1 (n_243), .Y (n_270));
  AOI22X1 g6152__2883(.A0 (b2x_addr[9]), .A1 (n_241), .B0 (n_332), .B1
       (n_196), .Y (n_269));
  AOI22X1 g6153__2346(.A0 (b2x_addr[8]), .A1 (n_241), .B0 (n_331), .B1
       (n_196), .Y (n_268));
  AOI22X1 g6154__1666(.A0 (sdram_mode_reg[9]), .A1 (n_244), .B0
       (n_466), .B1 (n_243), .Y (n_267));
  AOI22X1 g6155__7410(.A0 (sdram_mode_reg[10]), .A1 (n_244), .B0 (n_1),
       .B1 (n_215), .Y (n_266));
  AOI22X1 g6156__6417(.A0 (b2x_addr[11]), .A1 (n_241), .B0 (n_334), .B1
       (n_196), .Y (n_265));
  AOI22X1 g6157__5477(.A0 (b2x_addr[12]), .A1 (n_241), .B0 (n_335), .B1
       (n_196), .Y (n_264));
  AOI22X1 g6158__2398(.A0 (sdram_mode_reg[12]), .A1 (n_244), .B0
       (n_469), .B1 (n_243), .Y (n_263));
  AOI22X1 g6159__5107(.A0 (l_ba[0]), .A1 (n_243), .B0 (n_336), .B1
       (n_196), .Y (n_262));
  AOI22X1 g6160__6260(.A0 (l_ba[1]), .A1 (n_243), .B0 (n_337), .B1
       (n_196), .Y (n_261));
  OAI2BB1X1 g6161__4319(.A0N (xfr_caddr[2]), .A1N (n_202), .B0 (n_234),
       .Y (n_258));
  NAND2X1 g6162__8428(.A (sdram_mode_reg[0]), .B (n_244), .Y (n_257));
  OAI2BB1X1 g6163__5526(.A0N (xfr_caddr[1]), .A1N (n_202), .B0 (n_233),
       .Y (n_256));
  OAI2BB1X1 g6164__6783(.A0N (xfr_caddr[4]), .A1N (n_202), .B0 (n_231),
       .Y (n_255));
  OAI2BB1X1 g6165__3680(.A0N (xfr_caddr[3]), .A1N (n_202), .B0 (n_232),
       .Y (n_254));
  NAND2X1 g6166__1617(.A (sdram_mode_reg[11]), .B (n_244), .Y (n_260));
  NOR3X1 g6167__2802(.A (n_599), .B (n_14), .C (n_214), .Y (n_259));
  OAI211X1 g6169__1705(.A0 (xfr_caddr[0]), .A1 (n_198), .B0 (n_210),
       .C0 (n_99), .Y (n_253));
  OAI2BB1X1 g6170__5122(.A0N (xfr_caddr[6]), .A1N (n_202), .B0 (n_229),
       .Y (n_252));
  OAI2BB1X1 g6171__8246(.A0N (xfr_caddr[7]), .A1N (n_202), .B0 (n_228),
       .Y (n_251));
  OAI2BB1X1 g6172__7098(.A0N (xfr_caddr[8]), .A1N (n_202), .B0 (n_227),
       .Y (n_250));
  OAI2BB1X1 g6173__6131(.A0N (xfr_caddr[9]), .A1N (n_202), .B0 (n_226),
       .Y (n_249));
  OAI2BB1X1 g6174__1881(.A0N (n_467), .A1N (n_197), .B0 (n_230), .Y
       (n_248));
  OAI2BB1X1 g6175__5115(.A0N (n_468), .A1N (n_197), .B0 (n_236), .Y
       (n_247));
  OAI2BB1X1 g6176__7482(.A0N (xfr_caddr[12]), .A1N (n_202), .B0
       (n_235), .Y (n_246));
  OAI2BB1X1 g6177__4733(.A0N (n_462), .A1N (n_197), .B0 (n_239), .Y
       (n_245));
  INVX1 g6196(.A (n_243), .Y (n_242));
  INVX1 g6197(.A (n_241), .Y (n_240));
  AOI22X1 g6198__6161(.A0 (xfr_caddr[5]), .A1 (n_202), .B0
       (b2x_addr[5]), .B1 (n_40), .Y (n_239));
  NAND4XL g6199__9315(.A (1'b1), .B (n_195), .C (n_184), .D (n_201), .Y
       (n_238));
  AOI31X1 g6200__9945(.A0 (n_170), .A1 (n_0), .A2 (n_178), .B0 (n_14),
       .Y (n_237));
  AOI22X1 g6201__2883(.A0 (xfr_caddr[11]), .A1 (n_202), .B0
       (b2x_addr[11]), .B1 (n_40), .Y (n_236));
  AOI22X1 g6202__2346(.A0 (n_469), .A1 (n_197), .B0 (b2x_addr[12]), .B1
       (n_40), .Y (n_235));
  AOI22X1 g6203__1666(.A0 (n_459), .A1 (n_197), .B0 (b2x_addr[2]), .B1
       (n_40), .Y (n_234));
  AOI22X1 g6204__7410(.A0 (n_458), .A1 (n_197), .B0 (b2x_addr[1]), .B1
       (n_40), .Y (n_233));
  AOI22X1 g6205__6417(.A0 (n_460), .A1 (n_197), .B0 (b2x_addr[3]), .B1
       (n_40), .Y (n_232));
  AOI22X1 g6206__5477(.A0 (n_461), .A1 (n_197), .B0 (b2x_addr[4]), .B1
       (n_40), .Y (n_231));
  AOI22X1 g6207__2398(.A0 (xfr_caddr[10]), .A1 (n_202), .B0
       (b2x_addr[10]), .B1 (n_40), .Y (n_230));
  AOI22X1 g6208__5107(.A0 (n_463), .A1 (n_197), .B0 (b2x_addr[6]), .B1
       (n_40), .Y (n_229));
  AOI22X1 g6209__6260(.A0 (n_464), .A1 (n_197), .B0 (b2x_addr[7]), .B1
       (n_40), .Y (n_228));
  AOI22X1 g6210__4319(.A0 (n_465), .A1 (n_197), .B0 (b2x_addr[8]), .B1
       (n_40), .Y (n_227));
  AOI22X1 g6211__8428(.A0 (n_466), .A1 (n_197), .B0 (b2x_addr[9]), .B1
       (n_40), .Y (n_226));
  AND2X1 g6214__5526(.A (n_85), .B (n_215), .Y (n_244));
  AND3XL g6215__6783(.A (n_16), .B (n_455), .C (n_195), .Y (n_243));
  NOR2XL g6220__3680(.A (rfsh_timer[0]), .B (n_199), .Y (n_225));
  AND2XL g6221__1617(.A (n_479), .B (n_200), .Y (n_224));
  AND2XL g6222__2802(.A (n_480), .B (n_200), .Y (n_223));
  AND2XL g6223__1705(.A (n_481), .B (n_200), .Y (n_222));
  AND2XL g6224__5122(.A (n_482), .B (n_200), .Y (n_221));
  AND2XL g6225__8246(.A (n_483), .B (n_200), .Y (n_220));
  AND2XL g6226__7098(.A (n_484), .B (n_200), .Y (n_219));
  AND2XL g6227__6131(.A (n_485), .B (n_200), .Y (n_218));
  AND2XL g6228__1881(.A (n_486), .B (n_200), .Y (n_217));
  AND2XL g6229__5115(.A (n_487), .B (n_200), .Y (n_216));
  NOR2BX1 g6230__7482(.AN (n_488), .B (n_199), .Y (n_213));
  NOR2BX1 g6231__4733(.AN (n_489), .B (n_199), .Y (n_212));
  OR2XL g6232__6161(.A (n_14), .B (n_201), .Y (n_211));
  NAND2X1 g6233__9315(.A (xfr_caddr[0]), .B (n_202), .Y (n_210));
  OAI22X1 g6234__9945(.A0 (n_176), .A1 (n_174), .B0 (tmr0[0]), .B1
       (n_183), .Y (n_209));
  OAI22X1 g6235__2883(.A0 (n_176), .A1 (n_152), .B0 (n_21), .B1
       (n_183), .Y (n_208));
  NAND2X1 g6236__2346(.A (reset_n), .B (n_195), .Y (n_207));
  NOR2X1 g6237__1666(.A (n_14), .B (n_191), .Y (n_206));
  AOI21X1 g6238__7410(.A0 (n_647), .A1 (n_186), .B0 (n_14), .Y (n_205));
  OAI22X1 g6239__6417(.A0 (n_176), .A1 (n_175), .B0 (n_22), .B1
       (n_183), .Y (n_204));
  OAI22X1 g6240__5477(.A0 (n_176), .A1 (n_167), .B0 (n_13), .B1
       (n_183), .Y (n_203));
  NOR2X1 g6241__2398(.A (n_455), .B (n_196), .Y (n_215));
  NOR2X1 g6242__5107(.A (n_599), .B (n_199), .Y (n_214));
  NOR2BX1 g6249__6260(.AN (n_189), .B (n_61), .Y (n_202));
  INVX1 g6250(.A (n_200), .Y (n_199));
  INVX1 g6251(.A (n_197), .Y (n_198));
  INVX1 g6252(.A (n_196), .Y (n_195));
  NOR3BX1 g6253__4319(.AN (n_172), .B (n_14), .C (n_453), .Y (n_194));
  NAND2X1 g6254__8428(.A (reset_n), .B (n_190), .Y (n_193));
  OR2XL g6255__5526(.A (n_14), .B (n_184), .Y (n_192));
  AOI31X1 g6256__6783(.A0 (n_17), .A1 (n_65), .A2 (n_41), .B0 (n_180),
       .Y (n_191));
  OAI211X1 g6257__3680(.A0 (n_15), .A1 (n_157), .B0 (n_151), .C0
       (n_149), .Y (n_201));
  NOR2X1 g6258__1617(.A (n_14), .B (n_181), .Y (n_200));
  NOR2X1 g6259__2802(.A (n_61), .B (n_189), .Y (n_197));
  OR3X1 g6260__1705(.A (n_642), .B (n_90), .C (n_173), .Y (n_196));
  NOR2BX1 g6261__5122(.AN (n_172), .B (n_14), .Y (n_188));
  NOR2X1 g6262__8246(.A (n_14), .B (n_169), .Y (n_187));
  NOR2X1 g6263__7098(.A (n_123), .B (n_164), .Y (n_186));
  NOR2X1 g6264__6131(.A (n_14), .B (n_168), .Y (n_185));
  AOI21X1 g6265__1881(.A0 (n_455), .A1 (n_66), .B0 (n_173), .Y (n_190));
  NOR2X1 g6266__5115(.A (n_8), .B (n_172), .Y (n_189));
  NAND3BXL g6268__7482(.AN (n_162), .B (n_171), .C (reset_n), .Y
       (n_182));
  NOR4X1 g6269__4733(.A (n_126), .B (n_127), .C (n_131), .D (n_130), .Y
       (n_181));
  OAI221X1 g6270__6161(.A0 (n_506), .A1 (n_146), .B0 (n_503), .B1
       (n_143), .C0 (n_112), .Y (n_180));
  NAND3BXL g6271__9315(.AN (n_162), .B (n_166), .C (reset_n), .Y
       (n_179));
  OAI222X1 g6272__9945(.A0 (n_9), .A1 (n_455), .B0 (sdram_enable), .B1
       (n_144), .C0 (n_9), .C1 (n_118), .Y (n_178));
  NAND3BXL g6273__2883(.AN (n_162), .B (n_165), .C (reset_n), .Y
       (n_177));
  OR4X1 g6274__2346(.A (n_145), .B (n_93), .C (1'b0), .D (n_148), .Y
       (n_184));
  NAND3BXL g6275__1666(.AN (n_86), .B (reset_n), .C (n_163), .Y
       (n_183));
  AOI221X1 g6276__7410(.A0 (trp_delay[1]), .A1 (n_116), .B0
       (trcar_delay[1]), .B1 (n_119), .C0 (n_147), .Y (n_175));
  AOI221X1 g6278__6417(.A0 (trp_delay[0]), .A1 (n_116), .B0
       (trcar_delay[0]), .B1 (n_119), .C0 (n_147), .Y (n_174));
  OR2X1 g6286__5477(.A (n_14), .B (n_163), .Y (n_176));
  AOI22X1 g6287__2398(.A0 (rfsh_row_cnt[0]), .A1 (n_3), .B0 (n_491),
       .B1 (n_117), .Y (n_171));
  AOI221X1 g6288__5107(.A0 (n_86), .A1 (n_124), .B0 (n_644), .B1
       (n_84), .C0 (n_129), .Y (n_170));
  NOR4XL g6289__6260(.A (n_85), .B (n_123), .C (x2b_refresh), .D
       (n_138), .Y (n_169));
  AOI211XL g6290__4319(.A0 (n_23), .A1 (n_42), .B0 (n_65), .C0 (n_140),
       .Y (n_168));
  AOI221X1 g6292__8428(.A0 (trp_delay[2]), .A1 (n_116), .B0
       (trcar_delay[2]), .B1 (n_119), .C0 (n_147), .Y (n_167));
  AOI22X1 g6293__5526(.A0 (rfsh_row_cnt[1]), .A1 (n_3), .B0 (n_492),
       .B1 (n_117), .Y (n_166));
  AOI22X1 g6294__6783(.A0 (rfsh_row_cnt[2]), .A1 (n_3), .B0 (n_493),
       .B1 (n_117), .Y (n_165));
  OAI221X1 g6295__3680(.A0 (n_83), .A1 (n_644), .B0 (n_125), .B1
       (n_128), .C0 (n_5), .Y (n_164));
  OAI2BB1X1 g6296__1617(.A0N (n_83), .A1N (n_148), .B0 (n_149), .Y
       (n_173));
  OAI21X1 g6297__2802(.A0 (n_503), .A1 (n_91), .B0 (n_158), .Y (n_172));
  OAI2BB1X1 g6299__1705(.A0N (l_start), .A1N (n_96), .B0 (n_135), .Y
       (n_160));
  NOR4X1 g6301__8246(.A (n_98), .B (n_113), .C (n_62), .D (n_97), .Y
       (n_158));
  AOI211XL g6302__7098(.A0 (n_7), .A1 (n_18), .B0 (n_641), .C0 (n_64),
       .Y (n_157));
  AOI21X1 g6303__6131(.A0 (n_15), .A1 (n_118), .B0 (n_120), .Y (n_163));
  OAI211X1 g6305__1881(.A0 (l_len[0]), .A1 (n_81), .B0 (n_114), .C0
       (n_67), .Y (n_156));
  AOI22X1 g6309__7482(.A0 (trp_delay[3]), .A1 (n_116), .B0
       (trcar_delay[3]), .B1 (n_119), .Y (n_152));
  AOI22X1 g6310__4733(.A0 (n_83), .A1 (n_122), .B0 (b2x_cmd[0]), .B1
       (n_93), .Y (n_151));
  AOI2BB1XL g6313__6161(.A0N (rd_pipe_mt), .A1N (n_42), .B0 (n_643), .Y
       (n_146));
  NAND2BXL g6314__9315(.AN (n_90), .B (n_111), .Y (n_145));
  NOR2X1 g6319__9945(.A (l_xfr_end), .B (n_643), .Y (n_143));
  NAND2BX1 g6320__2883(.AN (b2x_tras_ok), .B (n_120), .Y (n_149));
  NOR2X1 g6321__2346(.A (n_455), .B (n_118), .Y (n_148));
  AOI22X1 g6327__1666(.A0 (n_472), .A1 (n_82), .B0 (b2x_len[3]), .B1
       (n_40), .Y (n_141));
  OR4X1 g6329__7410(.A (n_62), .B (n_97), .C (n_31), .D (n_98), .Y
       (n_140));
  AOI21X1 g6331__5477(.A0 (n_94), .A1 (n_86), .B0 (n_645), .Y (n_138));
  AOI22X1 g6333__5107(.A0 (n_471), .A1 (n_82), .B0 (b2x_len[2]), .B1
       (n_40), .Y (n_136));
  NAND4XL g6334__6260(.A (reset_n), .B (b2x_start), .C (n_45), .D
       (n_95), .Y (n_135));
  AOI22X1 g6335__4319(.A0 (n_473), .A1 (n_82), .B0 (b2x_len[4]), .B1
       (n_40), .Y (n_134));
  AOI22X1 g6337__5526(.A0 (n_475), .A1 (n_82), .B0 (b2x_len[6]), .B1
       (n_40), .Y (n_132));
  NAND4XL g6338__6783(.A (n_69), .B (n_68), .C (n_80), .D (n_74), .Y
       (n_131));
  NAND4XL g6339__3680(.A (n_75), .B (n_76), .C (n_77), .D (n_78), .Y
       (n_130));
  NAND3X1 g6340__1617(.A (n_599), .B (reset_n), .C (n_89), .Y (n_142));
  INVX1 g6342(.A (n_128), .Y (n_129));
  NAND2X1 g6343__2802(.A (n_71), .B (n_70), .Y (n_127));
  NAND2X1 g6344__1705(.A (n_73), .B (n_72), .Y (n_126));
  NOR2X1 g6345__5122(.A (sdr_init_done_1647), .B (n_94), .Y (n_125));
  NAND2BX1 g6358__8246(.AN (n_645), .B (n_86), .Y (n_128));
  NOR2X1 g6368__6131(.A (n_504), .B (n_91), .Y (n_113));
  OR4X1 g6369__1881(.A (n_583), .B (b2x_write), .C (1'b0), .D (n_570),
       .Y (n_112));
  OAI211X1 g6370__5115(.A0 (n_17), .A1 (n_617), .B0 (n_57), .C0 (n_16),
       .Y (n_111));
  OAI2BB1X1 g6371__7482(.A0N (b2x_ba[1]), .A1N (n_40), .B0 (n_101), .Y
       (n_110));
  OAI22XL g6372__4733(.A0 (n_11), .A1 (n_39), .B0 (n_10), .B1 (n_61),
       .Y (n_109));
  AOI21X1 g6373__6161(.A0 (n_58), .A1 (n_0), .B0 (n_14), .Y (n_108));
  OAI2BB1X1 g6374__9315(.A0N (b2x_wrap), .A1N (n_40), .B0 (n_100), .Y
       (n_107));
  NOR4BX1 g6375__9945(.AN (b2x_start), .B (n_14), .C (b2x_read), .D
       (ld_xfr), .Y (n_106));
  NAND4XL g6376__2883(.A (n_28), .B (n_54), .C (reset_n), .D
       (r2x_idle), .Y (n_105));
  OAI2BB1X1 g6377__2346(.A0N (a2x_wren_n[0]), .A1N (n_43), .B0
       (reset_n), .Y (n_104));
  OAI2BB1X1 g6378__1666(.A0N (a2x_wren_n[1]), .A1N (n_43), .B0
       (reset_n), .Y (n_103));
  OAI21X1 g6379__7410(.A0 (n_600), .A1 (n_0), .B0 (n_87), .Y (n_123));
  NOR2X1 g6380__6417(.A (n_455), .B (n_85), .Y (n_122));
  NOR2X1 g6382__2398(.A (n_455), .B (n_83), .Y (n_120));
  NAND2X1 g6384__5107(.A (n_507), .B (n_1), .Y (n_118));
  NOR2X1 g6385__6260(.A (n_14), .B (n_89), .Y (n_117));
  NAND2X1 g6387__4319(.A (l_ba[1]), .B (n_60), .Y (n_101));
  NAND2X1 g6400__8428(.A (l_wrap), .B (n_60), .Y (n_100));
  NAND2XL g6401__5526(.A (b2x_addr[0]), .B (n_40), .Y (n_99));
  NOR2X1 g6416__6783(.A (l_xfr_end), .B (n_61), .Y (n_102));
  INVX1 g6417(.A (n_95), .Y (n_96));
  INVX1 g6419(.A (n_1), .Y (n_85));
  INVX1 g6420(.A (n_83), .Y (n_84));
  INVX1 g6421(.A (n_82), .Y (n_81));
  XNOR2X1 g6422__3680(.A (rfsh_timer[9]), .B (rfsh_time[9]), .Y (n_80));
  XNOR2X1 g6424__1617(.A (rfsh_timer[0]), .B (rfsh_time[0]), .Y (n_78));
  XNOR2X1 g6425__2802(.A (rfsh_timer[1]), .B (rfsh_time[1]), .Y (n_77));
  XNOR2X1 g6426__1705(.A (rfsh_timer[2]), .B (rfsh_time[2]), .Y (n_76));
  XNOR2X1 g6427__5122(.A (rfsh_timer[3]), .B (rfsh_time[3]), .Y (n_75));
  XNOR2X1 g6428__8246(.A (rfsh_timer[8]), .B (rfsh_time[8]), .Y (n_74));
  XNOR2X1 g6429__7098(.A (rfsh_timer[5]), .B (rfsh_time[5]), .Y (n_73));
  XNOR2X1 g6430__6131(.A (rfsh_timer[4]), .B (rfsh_time[4]), .Y (n_72));
  XNOR2X1 g6431__1881(.A (rfsh_timer[7]), .B (rfsh_time[7]), .Y (n_71));
  XNOR2X1 g6432__5115(.A (rfsh_timer[6]), .B (rfsh_time[6]), .Y (n_70));
  XNOR2X1 g6433__7482(.A (rfsh_timer[11]), .B (rfsh_time[11]), .Y
       (n_69));
  XNOR2X1 g6434__4733(.A (rfsh_timer[10]), .B (rfsh_time[10]), .Y
       (n_68));
  NAND2XL g6435__6161(.A (b2x_len[0]), .B (n_40), .Y (n_67));
  NOR2X1 g6436__9315(.A (n_506), .B (n_41), .Y (n_98));
  NOR3X1 g6437__9945(.A (n_570), .B (n_583), .C (b2x_read), .Y (n_97));
  NAND2XL g6438__2883(.A (n_60), .B (n_45), .Y (n_95));
  OR4X1 g6439__2346(.A (cntr1[0]), .B (cntr1[1]), .C (cntr1[2]), .D
       (cntr1[3]), .Y (n_94));
  NAND3BXL g6442__7410(.AN (n_572), .B (b2x_req), .C (n_18), .Y (n_91));
  AND2XL g6443__6417(.A (n_455), .B (n_64), .Y (n_90));
  MX2X1 g6444__5477(.A (n_600), .B (n_9), .S0 (n_599), .Y (n_89));
  NAND3BXL g6446__5107(.AN (mgmt_st[0]), .B (mgmt_st[2]), .C
       (mgmt_st[1]), .Y (n_87));
  NOR4X1 g6447__6260(.A (tmr0[0]), .B (tmr0[1]), .C (tmr0[2]), .D
       (tmr0[3]), .Y (n_86));
  OR3X1 g6450__4319(.A (mgmt_st[2]), .B (n_19), .C (mgmt_st[1]), .Y
       (n_83));
  INVX1 g6452(.A (n_61), .Y (n_60));
  NOR2BX1 g6453__8428(.AN (l_rd_next[4]), .B (n_14), .Y (n_59));
  NAND2X1 g6454__5526(.A (sdr_init_done_1647), .B (sdram_enable), .Y
       (n_58));
  NOR2BX1 g6456__6783(.AN (l_rd_start[2]), .B (n_14), .Y (n_56));
  NOR2BX1 g6457__3680(.AN (l_rd_next[1]), .B (n_14), .Y (n_55));
  NOR2BX1 g6458__1617(.AN (b2x_idle), .B (n_600), .Y (n_54));
  NOR2BX1 g6459__2802(.AN (l_rd_last[4]), .B (n_14), .Y (n_53));
  NOR2BX1 g6460__1705(.AN (l_rd_last[5]), .B (n_14), .Y (n_52));
  NOR2BX1 g6461__5122(.AN (l_rd_last[3]), .B (n_14), .Y (n_51));
  NOR2BX1 g6462__8246(.AN (l_rd_next[5]), .B (n_14), .Y (n_50));
  NOR2BX1 g6463__7098(.AN (l_rd_next[2]), .B (n_14), .Y (n_49));
  NOR2BX1 g6464__6131(.AN (act_cmd), .B (n_14), .Y (n_48));
  NOR2BX1 g6465__1881(.AN (l_rd_start[0]), .B (n_14), .Y (n_47));
  NOR2BX1 g6466__5115(.AN (l_rd_next[0]), .B (n_14), .Y (n_46));
  NAND2BX1 g6467__7482(.AN (b2x_cmd[1]), .B (n_7), .Y (n_66));
  NOR2BX1 g6468__4733(.AN (sdr_init_done_1647), .B (n_504), .Y (n_65));
  NOR2BX1 g6469__6161(.AN (n_505), .B (n_7), .Y (n_64));
  AND2XL g6470__9315(.A (n_457), .B (n_456), .Y (n_63));
  NOR2X1 g6471__9945(.A (n_17), .B (n_504), .Y (n_62));
  NAND2X1 g6472__2883(.A (reset_n), .B (ld_xfr), .Y (n_61));
  INVX1 g6473(.A (n_44), .Y (n_43));
  INVX1 g6474(.A (n_42), .Y (n_41));
  INVX1 g6475(.A (n_40), .Y (n_39));
  NOR2BX1 g6476__2346(.AN (l_rd_last[2]), .B (n_14), .Y (n_38));
  NOR2BX1 g6477__1666(.AN (l_rd_next[3]), .B (n_14), .Y (n_37));
  NOR2BX1 g6478__7410(.AN (x2a_id[1]), .B (n_14), .Y (n_36));
  NOR2BX1 g6479__6417(.AN (x2a_id[2]), .B (n_14), .Y (n_35));
  NOR2BX1 g6480__5477(.AN (l_rd_start[4]), .B (n_14), .Y (n_34));
  NOR2BX1 g6481__2398(.AN (x2a_id[3]), .B (n_14), .Y (n_33));
  NOR2BX1 g6482__5107(.AN (l_rd_last[1]), .B (n_14), .Y (n_32));
  NOR2XL g6483__6260(.A (n_506), .B (rd_pipe_mt), .Y (n_31));
  NOR2BX1 g6484__4319(.AN (l_rd_last[0]), .B (n_14), .Y (n_30));
  NOR2BX1 g6485__8428(.AN (x2a_id[0]), .B (n_14), .Y (n_29));
  NOR2X1 g6486__5526(.A (n_583), .B (n_599), .Y (n_28));
  NOR2BX1 g6487__6783(.AN (l_rd_start[1]), .B (n_14), .Y (n_27));
  NOR2BX1 g6488__3680(.AN (l_rd_start[3]), .B (n_14), .Y (n_26));
  NOR2BX1 g6489__1617(.AN (l_rd_start[5]), .B (n_14), .Y (n_25));
  NOR2BX1 g6490__2802(.AN (last_burst), .B (n_14), .Y (n_24));
  NOR2X1 g6491__1705(.A (n_503), .B (l_xfr_end), .Y (n_23));
  NOR2XL g6492__5122(.A (n_8), .B (x2a_rdok), .Y (n_45));
  NAND2X1 g6494__8246(.A (reset_n), .B (n_8), .Y (n_44));
  NOR2X1 g6495__7098(.A (b2x_read), .B (n_616), .Y (n_42));
  NOR2X2 g6496__6131(.A (n_14), .B (ld_xfr), .Y (n_40));
  INVX1 g6497(.A (n_495), .Y (n_22));
  INVX1 g6498(.A (n_497), .Y (n_21));
  INVX1 g6500(.A (mgmt_st[0]), .Y (n_19));
  INVX1 g6501(.A (b2x_read), .Y (n_18));
  INVX1 g6502(.A (l_xfr_end), .Y (n_17));
  INVX1 g6503(.A (n_7), .Y (n_16));
  INVX1 g6504(.A (n_455), .Y (n_15));
  CLKINVX4 g6505(.A (reset_n), .Y (n_14));
  INVX1 g6506(.A (n_496), .Y (n_13));
  INVX1 g6508(.A (n_468), .Y (n_12));
  INVX1 g6509(.A (b2x_ba[0]), .Y (n_11));
  INVX1 g6510(.A (l_ba[0]), .Y (n_10));
  INVX1 g6511(.A (n_508), .Y (n_9));
  CLKBUFX20 drc_bufs6524(.A (n_337), .Y (sdr_ba[1]));
  CLKBUFX20 drc_bufs6528(.A (n_336), .Y (sdr_ba[0]));
  CLKBUFX20 drc_bufs6532(.A (n_335), .Y (sdr_addr[12]));
  CLKBUFX20 drc_bufs6536(.A (n_334), .Y (sdr_addr[11]));
  CLKBUFX20 drc_bufs6540(.A (n_333), .Y (sdr_addr[10]));
  CLKBUFX20 drc_bufs6544(.A (n_332), .Y (sdr_addr[9]));
  CLKBUFX20 drc_bufs6548(.A (n_331), .Y (sdr_addr[8]));
  CLKBUFX20 drc_bufs6552(.A (n_330), .Y (sdr_addr[7]));
  CLKBUFX20 drc_bufs6556(.A (n_329), .Y (sdr_addr[6]));
  CLKBUFX20 drc_bufs6560(.A (n_328), .Y (sdr_addr[5]));
  CLKBUFX20 drc_bufs6564(.A (n_327), .Y (sdr_addr[4]));
  CLKBUFX20 drc_bufs6568(.A (n_326), .Y (sdr_addr[3]));
  CLKBUFX20 drc_bufs6572(.A (n_325), .Y (sdr_addr[2]));
  CLKBUFX20 drc_bufs6576(.A (n_324), .Y (sdr_addr[1]));
  CLKBUFX20 drc_bufs6580(.A (n_323), .Y (sdr_addr[0]));
  CLKBUFX20 drc_bufs6584(.A (n_321), .Y (sdr_dout[14]));
  CLKBUFX20 drc_bufs6588(.A (n_320), .Y (sdr_dout[13]));
  CLKBUFX20 drc_bufs6592(.A (n_319), .Y (sdr_dout[12]));
  CLKBUFX20 drc_bufs6596(.A (n_318), .Y (sdr_dout[11]));
  CLKBUFX20 drc_bufs6600(.A (n_317), .Y (sdr_dout[10]));
  CLKBUFX20 drc_bufs6604(.A (n_316), .Y (sdr_dout[9]));
  CLKBUFX20 drc_bufs6608(.A (n_310), .Y (sdr_dout[3]));
  CLKBUFX20 drc_bufs6612(.A (n_315), .Y (sdr_dout[8]));
  CLKBUFX20 drc_bufs6616(.A (n_314), .Y (sdr_dout[7]));
  CLKBUFX20 drc_bufs6620(.A (n_313), .Y (sdr_dout[6]));
  CLKBUFX20 drc_bufs6624(.A (n_312), .Y (sdr_dout[5]));
  CLKBUFX20 drc_bufs6628(.A (n_311), .Y (sdr_dout[4]));
  CLKBUFX20 drc_bufs6632(.A (n_309), .Y (sdr_dout[2]));
  CLKBUFX20 drc_bufs6636(.A (n_308), .Y (sdr_dout[1]));
  CLKBUFX20 drc_bufs6640(.A (n_307), .Y (sdr_dout[0]));
  CLKBUFX20 drc_bufs6644(.A (n_322), .Y (sdr_dout[15]));
  CLKBUFX20 drc_bufs6645(.A (n_343), .Y (sdr_cke));
  CLKBUFX20 drc_bufs6646(.A (n_344), .Y (sdr_cs_n));
  CLKBUFX20 drc_bufs6647(.A (n_342), .Y (sdr_ras_n));
  CLKBUFX20 drc_bufs6648(.A (n_306), .Y (sdr_den_n[1]));
  CLKBUFX20 drc_bufs6649(.A (n_341), .Y (sdr_cas_n));
  CLKBUFX20 drc_bufs6650(.A (n_305), .Y (sdr_den_n[0]));
  CLKBUFX20 drc_bufs6651(.A (n_340), .Y (sdr_we_n));
  CLKBUFX20 drc_bufs6652(.A (n_339), .Y (sdr_dqm[1]));
  CLKBUFX20 drc_bufs6653(.A (n_338), .Y (sdr_dqm[0]));
  INVX1 drc_bufs6654(.A (n_6), .Y (n_7));
  INVXL drc_bufs6656(.A (x2b_ack), .Y (n_6));
  BUFX2 drc_bufs6666(.A (x2a_wrnext), .Y (n_8));
  AO21XL g5129__1881(.A0 (n_455), .A1 (n_507), .B0 (n_122), .Y (n_5));
  NAND3BX1 g6756__4733(.AN (mgmt_st[1]), .B (mgmt_st[2]), .C
       (mgmt_st[0]), .Y (n_1));
  NAND2BX1 g6757__6161(.AN (n_599), .B (sdram_enable), .Y (n_0));
  XNOR2X1 dec_SUB_UNS_OP_g39__9315(.A (cntr1[3]), .B
       (dec_SUB_UNS_OP_n_6), .Y (n_494));
  OAI2BB1X1 dec_SUB_UNS_OP_g40__9945(.A0N (cntr1[2]), .A1N
       (dec_SUB_UNS_OP_n_4), .B0 (dec_SUB_UNS_OP_n_6), .Y (n_493));
  OR2XL dec_SUB_UNS_OP_g41__2883(.A (cntr1[2]), .B
       (dec_SUB_UNS_OP_n_4), .Y (dec_SUB_UNS_OP_n_6));
  OAI2BB1X1 dec_SUB_UNS_OP_g42__2346(.A0N (cntr1[1]), .A1N
       (dec_SUB_UNS_OP_n_2), .B0 (dec_SUB_UNS_OP_n_4), .Y (n_492));
  OR2XL dec_SUB_UNS_OP_g43__1666(.A (cntr1[1]), .B
       (dec_SUB_UNS_OP_n_2), .Y (dec_SUB_UNS_OP_n_4));
  OAI2BB1X1 dec_SUB_UNS_OP_g44__7410(.A0N (cntr1[0]), .A1N
       (dec_SUB_UNS_OP_n_1), .B0 (dec_SUB_UNS_OP_n_2), .Y (n_491));
  NAND2BX1 dec_SUB_UNS_OP_g45__6417(.AN (cntr1[0]), .B
       (dec_SUB_UNS_OP_n_0), .Y (dec_SUB_UNS_OP_n_2));
  INVX1 dec_SUB_UNS_OP_drc_bufs48(.A (dec_SUB_UNS_OP_n_0), .Y
       (dec_SUB_UNS_OP_n_1));
  BUFX2 dec_SUB_UNS_OP_drc_bufs50(.A (x2b_refresh), .Y
       (dec_SUB_UNS_OP_n_0));
  XNOR2X1 dec_sub_281_31_g71__5477(.A (l_len[5]), .B
       (dec_sub_281_31_n_5), .Y (n_474));
  AO21X1 dec_sub_281_31_g72__2398(.A0 (l_len[6]), .A1
       (dec_sub_281_31_n_6), .B0 (n_476), .Y (n_475));
  NOR2X1 dec_sub_281_31_g73__5107(.A (l_len[6]), .B
       (dec_sub_281_31_n_6), .Y (n_476));
  XNOR2X1 dec_sub_281_31_g74__6260(.A (l_len[3]), .B
       (dec_sub_281_31_n_2), .Y (n_472));
  OAI2BB1X1 dec_sub_281_31_g75__4319(.A0N (l_len[4]), .A1N
       (dec_sub_281_31_n_3), .B0 (dec_sub_281_31_n_5), .Y (n_473));
  OR3XL dec_sub_281_31_g76__8428(.A (l_len[4]), .B (l_len[5]), .C
       (dec_sub_281_31_n_3), .Y (dec_sub_281_31_n_6));
  OR2XL dec_sub_281_31_g77__5526(.A (l_len[4]), .B
       (dec_sub_281_31_n_3), .Y (dec_sub_281_31_n_5));
  OAI2BB1X1 dec_sub_281_31_g78__6783(.A0N (l_len[2]), .A1N
       (dec_sub_281_31_n_0), .B0 (dec_sub_281_31_n_2), .Y (n_471));
  OR3XL dec_sub_281_31_g79__3680(.A (l_len[2]), .B (l_len[3]), .C
       (dec_sub_281_31_n_0), .Y (dec_sub_281_31_n_3));
  OR2XL dec_sub_281_31_g80__1617(.A (l_len[2]), .B
       (dec_sub_281_31_n_0), .Y (dec_sub_281_31_n_2));
  OAI2BB1X1 dec_sub_281_31_g81__2802(.A0N (l_len[1]), .A1N (l_len[0]),
       .B0 (dec_sub_281_31_n_0), .Y (n_470));
  OR2X1 dec_sub_281_31_g82__1705(.A (l_len[1]), .B (l_len[0]), .Y
       (dec_sub_281_31_n_0));
  XNOR2X1 dec_sub_616_23_g62__5122(.A (tmr0[3]), .B
       (dec_sub_616_23_n_2), .Y (n_497));
  OAI2BB1X1 dec_sub_616_23_g63__8246(.A0N (tmr0[2]), .A1N
       (dec_sub_616_23_n_0), .B0 (dec_sub_616_23_n_2), .Y (n_496));
  OR2XL dec_sub_616_23_g64__7098(.A (tmr0[2]), .B (dec_sub_616_23_n_0),
       .Y (dec_sub_616_23_n_2));
  OAI2BB1X1 dec_sub_616_23_g65__6131(.A0N (tmr0[1]), .A1N (tmr0[0]),
       .B0 (dec_sub_616_23_n_0), .Y (n_495));
  OR2XL dec_sub_616_23_g66__1881(.A (tmr0[1]), .B (tmr0[0]), .Y
       (dec_sub_616_23_n_0));
  OAI22X1 gte_631_35_g51__5115(.A0 (gte_631_35_n_1), .A1
       (gte_631_35_n_4), .B0 (gte_631_35_n_0), .B1 (rfsh_rmax[2]), .Y
       (n_600));
  AOI21X1 gte_631_35_g52__7482(.A0 (rfsh_row_cnt[1]), .A1
       (gte_631_35_n_2), .B0 (gte_631_35_n_3), .Y (gte_631_35_n_4));
  AOI2BB1X1 gte_631_35_g53__4733(.A0N (rfsh_row_cnt[1]), .A1N
       (gte_631_35_n_2), .B0 (rfsh_rmax[1]), .Y (gte_631_35_n_3));
  NAND2BX1 gte_631_35_g54__6161(.AN (rfsh_row_cnt[0]), .B
       (rfsh_rmax[0]), .Y (gte_631_35_n_2));
  AND2X1 gte_631_35_g55__9315(.A (rfsh_rmax[2]), .B (gte_631_35_n_0),
       .Y (gte_631_35_n_1));
  INVX1 gte_631_35_g56(.A (rfsh_row_cnt[2]), .Y (gte_631_35_n_0));
  XNOR2X1 inc_add_239_40_g145__9945(.A (xfr_caddr[12]), .B
       (inc_add_239_40_n_20), .Y (n_469));
  XNOR2X1 inc_add_239_40_g146__2883(.A (xfr_caddr[11]), .B
       (inc_add_239_40_n_16), .Y (n_468));
  NAND2BX1 inc_add_239_40_g147__2346(.AN (inc_add_239_40_n_16), .B
       (xfr_caddr[11]), .Y (inc_add_239_40_n_20));
  XNOR2X1 inc_add_239_40_g148__1666(.A (xfr_caddr[9]), .B
       (inc_add_239_40_n_13), .Y (n_466));
  OA21X1 inc_add_239_40_g149__7410(.A0 (xfr_caddr[10]), .A1
       (inc_add_239_40_n_12), .B0 (inc_add_239_40_n_16), .Y (n_467));
  XNOR2X1 inc_add_239_40_g150__6417(.A (xfr_caddr[7]), .B
       (inc_add_239_40_n_8), .Y (n_464));
  NAND2X1 inc_add_239_40_g151__5477(.A (xfr_caddr[10]), .B
       (inc_add_239_40_n_12), .Y (inc_add_239_40_n_16));
  OA21X1 inc_add_239_40_g152__2398(.A0 (xfr_caddr[8]), .A1
       (inc_add_239_40_n_11), .B0 (inc_add_239_40_n_13), .Y (n_465));
  XNOR2X1 inc_add_239_40_g153__5107(.A (xfr_caddr[5]), .B
       (inc_add_239_40_n_6), .Y (n_462));
  NAND2X1 inc_add_239_40_g154__6260(.A (xfr_caddr[8]), .B
       (inc_add_239_40_n_11), .Y (inc_add_239_40_n_13));
  AND3XL inc_add_239_40_g155__4319(.A (inc_add_239_40_n_11), .B
       (xfr_caddr[9]), .C (xfr_caddr[8]), .Y (inc_add_239_40_n_12));
  AND3XL inc_add_239_40_g156__8428(.A (xfr_caddr[6]), .B
       (xfr_caddr[7]), .C (inc_add_239_40_n_5), .Y
       (inc_add_239_40_n_11));
  OA21X1 inc_add_239_40_g157__5526(.A0 (xfr_caddr[6]), .A1
       (inc_add_239_40_n_5), .B0 (inc_add_239_40_n_8), .Y (n_463));
  XNOR2X1 inc_add_239_40_g158__6783(.A (xfr_caddr[3]), .B
       (inc_add_239_40_n_2), .Y (n_460));
  NAND2X1 inc_add_239_40_g159__3680(.A (xfr_caddr[6]), .B
       (inc_add_239_40_n_5), .Y (inc_add_239_40_n_8));
  OA21X1 inc_add_239_40_g160__1617(.A0 (xfr_caddr[4]), .A1
       (inc_add_239_40_n_4), .B0 (inc_add_239_40_n_6), .Y (n_461));
  NAND2X1 inc_add_239_40_g161__2802(.A (xfr_caddr[4]), .B
       (inc_add_239_40_n_4), .Y (inc_add_239_40_n_6));
  AND3XL inc_add_239_40_g162__1705(.A (inc_add_239_40_n_4), .B
       (xfr_caddr[5]), .C (xfr_caddr[4]), .Y (inc_add_239_40_n_5));
  AND3XL inc_add_239_40_g163__5122(.A (xfr_caddr[3]), .B
       (xfr_caddr[2]), .C (inc_add_239_40_n_0), .Y
       (inc_add_239_40_n_4));
  OA21X1 inc_add_239_40_g164__8246(.A0 (xfr_caddr[2]), .A1
       (inc_add_239_40_n_0), .B0 (inc_add_239_40_n_2), .Y (n_459));
  NAND2X1 inc_add_239_40_g165__7098(.A (xfr_caddr[2]), .B
       (inc_add_239_40_n_0), .Y (inc_add_239_40_n_2));
  AOI2BB1X1 inc_add_239_40_g166__6131(.A0N (xfr_caddr[1]), .A1N
       (xfr_caddr[0]), .B0 (inc_add_239_40_n_0), .Y (n_458));
  AND2XL inc_add_239_40_g167__1881(.A (xfr_caddr[1]), .B
       (xfr_caddr[0]), .Y (inc_add_239_40_n_0));
  XNOR2X1 inc_add_620_50_g133__5115(.A (rfsh_timer[11]), .B
       (inc_add_620_50_n_17), .Y (n_489));
  XNOR2X1 inc_add_620_50_g134__7482(.A (rfsh_timer[9]), .B
       (inc_add_620_50_n_12), .Y (n_487));
  OA21X1 inc_add_620_50_g135__4733(.A0 (rfsh_timer[10]), .A1
       (inc_add_620_50_n_14), .B0 (inc_add_620_50_n_17), .Y (n_488));
  NAND2X1 inc_add_620_50_g136__6161(.A (rfsh_timer[10]), .B
       (inc_add_620_50_n_14), .Y (inc_add_620_50_n_17));
  XNOR2X1 inc_add_620_50_g137__9315(.A (rfsh_timer[7]), .B
       (inc_add_620_50_n_8), .Y (n_485));
  OA21X1 inc_add_620_50_g138__9945(.A0 (rfsh_timer[8]), .A1
       (inc_add_620_50_n_11), .B0 (inc_add_620_50_n_12), .Y (n_486));
  AND3XL inc_add_620_50_g139__2883(.A (rfsh_timer[9]), .B
       (rfsh_timer[8]), .C (inc_add_620_50_n_11), .Y
       (inc_add_620_50_n_14));
  XNOR2X1 inc_add_620_50_g140__2346(.A (rfsh_timer[5]), .B
       (inc_add_620_50_n_6), .Y (n_483));
  NAND2X1 inc_add_620_50_g141__1666(.A (rfsh_timer[8]), .B
       (inc_add_620_50_n_11), .Y (inc_add_620_50_n_12));
  AND3XL inc_add_620_50_g142__7410(.A (rfsh_timer[6]), .B
       (rfsh_timer[7]), .C (inc_add_620_50_n_5), .Y
       (inc_add_620_50_n_11));
  OA21X1 inc_add_620_50_g143__6417(.A0 (rfsh_timer[6]), .A1
       (inc_add_620_50_n_5), .B0 (inc_add_620_50_n_8), .Y (n_484));
  XNOR2X1 inc_add_620_50_g144__5477(.A (rfsh_timer[3]), .B
       (inc_add_620_50_n_2), .Y (n_481));
  NAND2X1 inc_add_620_50_g145__2398(.A (rfsh_timer[6]), .B
       (inc_add_620_50_n_5), .Y (inc_add_620_50_n_8));
  OA21X1 inc_add_620_50_g146__5107(.A0 (rfsh_timer[4]), .A1
       (inc_add_620_50_n_4), .B0 (inc_add_620_50_n_6), .Y (n_482));
  NAND2X1 inc_add_620_50_g147__6260(.A (rfsh_timer[4]), .B
       (inc_add_620_50_n_4), .Y (inc_add_620_50_n_6));
  AND3XL inc_add_620_50_g148__4319(.A (inc_add_620_50_n_4), .B
       (rfsh_timer[5]), .C (rfsh_timer[4]), .Y (inc_add_620_50_n_5));
  AND3XL inc_add_620_50_g149__8428(.A (rfsh_timer[3]), .B
       (rfsh_timer[2]), .C (inc_add_620_50_n_0), .Y
       (inc_add_620_50_n_4));
  OA21X1 inc_add_620_50_g150__5526(.A0 (rfsh_timer[2]), .A1
       (inc_add_620_50_n_0), .B0 (inc_add_620_50_n_2), .Y (n_480));
  NAND2X1 inc_add_620_50_g151__6783(.A (rfsh_timer[2]), .B
       (inc_add_620_50_n_0), .Y (inc_add_620_50_n_2));
  AOI2BB1XL inc_add_620_50_g152__3680(.A0N (rfsh_timer[1]), .A1N
       (rfsh_timer[0]), .B0 (inc_add_620_50_n_0), .Y (n_479));
  AND2XL inc_add_620_50_g153__1617(.A (rfsh_timer[1]), .B
       (rfsh_timer[0]), .Y (inc_add_620_50_n_0));
  XNOR2X1 inc_add_622_36_g23__2802(.A (rfsh_row_cnt[2]), .B
       (inc_add_622_36_n_0), .Y (n_478));
  OA21X1 inc_add_622_36_g24__1705(.A0 (rfsh_row_cnt[1]), .A1
       (rfsh_row_cnt[0]), .B0 (inc_add_622_36_n_0), .Y (n_477));
  NAND2X1 inc_add_622_36_g25__5122(.A (rfsh_row_cnt[1]), .B
       (rfsh_row_cnt[0]), .Y (inc_add_622_36_n_0));
  INVXL g6758(.A (l_wrap), .Y (n_457));
  INVXL g6759(.A (xfr_caddr[1]), .Y (n_490));
  INVXL g6760(.A (n_359), .Y (n_373));
  INVXL g6761(.A (n_358), .Y (n_372));
  CLKBUFX2 g6762(.A (n_357), .Y (n_363));
  INVXL g6763(.A (n_507), .Y (n_119));
  INVXL g6764(.A (n_1), .Y (n_147));
  INVXL g6765(.A (n_647), .Y (n_124));
  CLKBUFX2 g6766(.A (n_118), .Y (n_144));
  INVXL g6767(.A (n_83), .Y (n_116));
  INVX2 g6768(.A (x2b_pre_ok[2]), .Y (n_57));
  CLKBUFX2 g6769(.A (n_89), .Y (n_3));
  INVXL g6770(.A (n_142), .Y (n_162));
  INVXL g6771(.A (l_xfr_end), .Y (n_392));
  INVXL g6772(.A (n_572), .Y (n_399));
  INVXL g6773(.A (n_62), .Y (n_79));
  INVXL g6774(.A (n_61), .Y (n_82));
  INVXL g6775(.A (n_6), .Y (n_241));
  INVXL g6776(.A (n_102), .Y (n_114));
  INVXL g6777(.A (n_66), .Y (n_93));
  INVXL g6778(.A (n_136), .Y (n_161));
  INVXL g6779(.A (n_134), .Y (n_155));
  INVXL g6780(.A (n_132), .Y (n_153));
  INVXL g6781(.A (n_141), .Y (n_150));
  AOI22X1 g2(.A0 (n_505), .A1 (n_389), .B0 (n_353), .B1 (n_411), .Y
       (n_636));
  NOR2X1 g6782(.A (b2x_cmd[0]), .B (n_368), .Y (n_637));
  NOR2X1 g6783(.A (n_238), .B (n_14), .Y (n_638));
  AO22XL g6784(.A0 (n_470), .A1 (n_82), .B0 (b2x_len[1]), .B1 (n_40),
       .Y (n_639));
  AO22XL g6785(.A0 (n_474), .A1 (n_82), .B0 (b2x_len[5]), .B1 (n_40),
       .Y (n_640));
  AOI21X1 g6786(.A0 (n_63), .A1 (n_79), .B0 (n_7), .Y (n_641));
  NOR3BXL g6787(.AN (n_451), .B (n_63), .C (n_7), .Y (n_642));
  NOR2X1 g6788(.A (b2x_write), .B (n_616), .Y (n_643));
  NAND2BX1 g6789(.AN (n_451), .B (b2x_tras_ok), .Y (n_644));
  NAND2X1 g6790(.A (mgmt_st[2]), .B (n_19), .Y (n_645));
  OAI2BB1X1 g6791(.A0N (n_494), .A1N (n_117), .B0 (n_142), .Y (n_646));
  NAND2X1 g6792(.A (mgmt_st[1]), .B (n_19), .Y (n_647));
endmodule

