
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jul  5 2024 11:55:26 IST (Jul  5 2024 06:25:26 UTC)

// Verification Directory fv/sdrc_req_gen 

module sdrc_req_gen(clk, reset_n, cfg_colbits, sdr_width, req, req_id,
     req_addr, req_len, req_wrap, req_wr_n, req_ack, r2x_idle, r2b_req,
     r2b_req_id, r2b_start, r2b_last, r2b_wrap, r2b_ba, r2b_raddr,
     r2b_caddr, r2b_len, r2b_write, b2r_ack, b2r_arb_ok);
  input clk, reset_n, req, req_wrap, req_wr_n, b2r_ack, b2r_arb_ok;
  input [1:0] cfg_colbits, sdr_width;
  input [3:0] req_id;
  input [25:0] req_addr;
  input [8:0] req_len;
  output req_ack, r2x_idle, r2b_req, r2b_start, r2b_last, r2b_wrap,
       r2b_write;
  output [3:0] r2b_req_id;
  output [1:0] r2b_ba;
  output [12:0] r2b_raddr, r2b_caddr;
  output [6:0] r2b_len;
  wire clk, reset_n, req, req_wrap, req_wr_n, b2r_ack, b2r_arb_ok;
  wire [1:0] cfg_colbits, sdr_width;
  wire [3:0] req_id;
  wire [25:0] req_addr;
  wire [8:0] req_len;
  wire req_ack, r2x_idle, r2b_req, r2b_start, r2b_last, r2b_wrap,
       r2b_write;
  wire [3:0] r2b_req_id;
  wire [1:0] r2b_ba;
  wire [12:0] r2b_raddr, r2b_caddr;
  wire [6:0] r2b_len;
  wire [12:0] max_r2b_len_r;
  wire [6:0] lcl_req_len;
  wire [1:0] req_st;
  wire [25:0] curr_sdr_addr;
  wire ADD_TC_OP82_n_0, ADD_TC_OP82_n_2, ADD_TC_OP82_n_4,
       ADD_TC_OP82_n_6, ADD_TC_OP82_n_8, ADD_TC_OP82_n_10,
       ADD_TC_OP82_n_13, ADD_TC_OP82_n_14;
  wire ADD_TC_OP82_n_16, ADD_TC_OP82_n_18, ADD_TC_OP82_n_20,
       ADD_TC_OP82_n_22, ADD_TC_OP82_n_24, ADD_TC_OP82_n_26,
       ADD_TC_OP82_n_28, ADD_TC_OP82_n_30;
  wire ADD_TC_OP82_n_32, ADD_TC_OP82_n_34, ADD_TC_OP82_n_36,
       ADD_TC_OP82_n_38, ADD_TC_OP82_n_40, ADD_TC_OP82_n_42,
       ADD_TC_OP82_n_44, ADD_TC_OP82_n_46;
  wire ADD_TC_OP82_n_48, ADD_TC_OP85_n_2, ADD_TC_OP85_n_4,
       ADD_TC_OP85_n_6, ADD_TC_OP85_n_8, ADD_TC_OP85_n_10,
       ADD_TC_OP85_n_12, ADD_TC_OP85_n_14;
  wire ADD_TC_OP86_n_2, ADD_TC_OP86_n_4, ADD_TC_OP86_n_6,
       ADD_TC_OP86_n_8, ADD_TC_OP86_n_10, ADD_TC_OP86_n_12,
       ADD_TC_OP_n_2, ADD_TC_OP_n_4;
  wire ADD_TC_OP_n_6, ADD_TC_OP_n_8, ADD_TC_OP_n_10, ADD_TC_OP_n_12,
       ADD_TC_OP_n_14, ADD_TC_OP_n_16, SUB_TC_OP84_n_0, SUB_TC_OP84_n_1;
  wire SUB_TC_OP84_n_2, SUB_TC_OP84_n_3, SUB_TC_OP84_n_4,
       SUB_TC_OP84_n_5, SUB_TC_OP84_n_6, SUB_TC_OP84_n_7,
       SUB_TC_OP84_n_9, SUB_TC_OP84_n_11;
  wire SUB_TC_OP84_n_13, SUB_TC_OP84_n_15, SUB_TC_OP84_n_17,
       SUB_TC_OP_1_n_1, SUB_TC_OP_1_n_2, SUB_TC_OP_1_n_3,
       SUB_TC_OP_1_n_4, SUB_TC_OP_1_n_5;
  wire SUB_TC_OP_1_n_6, SUB_TC_OP_1_n_8, SUB_TC_OP_1_n_10,
       SUB_TC_OP_1_n_12, SUB_TC_OP_1_n_14, SUB_TC_OP_1_n_16,
       SUB_TC_OP_1_n_18, SUB_TC_OP_1_n_20;
  wire SUB_TC_OP_1_n_22, SUB_UNS_OP_n_1, SUB_UNS_OP_n_2,
       SUB_UNS_OP_n_3, SUB_UNS_OP_n_4, SUB_UNS_OP_n_5, SUB_UNS_OP_n_6,
       SUB_UNS_OP_n_7;
  wire SUB_UNS_OP_n_8, SUB_UNS_OP_n_9, SUB_UNS_OP_n_10,
       SUB_UNS_OP_n_11, SUB_UNS_OP_n_12, SUB_UNS_OP_n_13,
       SUB_UNS_OP_n_14, SUB_UNS_OP_n_15;
  wire SUB_UNS_OP_n_16, SUB_UNS_OP_n_17, SUB_UNS_OP_n_18,
       SUB_UNS_OP_n_19, SUB_UNS_OP_n_20, SUB_UNS_OP_n_21,
       SUB_UNS_OP_n_22, SUB_UNS_OP_n_23;
  wire SUB_UNS_OP_n_24, SUB_UNS_OP_n_25, n_0, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_137, n_142, n_143, n_146, n_149, n_150, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_172, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_268, n_269, n_270, n_271;
  wire n_272, n_279, n_280, n_281, n_282, n_283, n_284, n_290;
  wire n_291, n_292, n_293, n_294, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_309, n_368, n_369, n_370, n_371, n_372;
  wire n_373, n_374, n_375, n_376, n_377, n_378, n_379, n_380;
  wire n_381, n_900, n_901, n_902, n_903, n_904, n_905, n_906;
  wire n_907, n_941, n_942, n_943, n_944, n_945, n_946, n_947;
  wire n_948, n_949, n_996, n_997, n_998, n_999, n_1000, n_1001;
  wire n_1002, n_1003, n_1005, page_ovflw_r;
  INVX1 g1396(.A (n_177), .Y (n_172));
  INVX1 g1395(.A (n_309), .Y (req_ack));
  INVXL g1397(.A (n_174), .Y (n_170));
  INVX1 g1399(.A (req_wr_n), .Y (n_169));
  INVX1 g1398(.A (b2r_arb_ok), .Y (n_168));
  OAI2BB1X1 g1511__2398(.A0N (req_addr[4]), .A1N (n_159), .B0 (n_166),
       .Y (n_189));
  OAI2BB1X1 g1512__5107(.A0N (req_addr[6]), .A1N (n_158), .B0 (n_167),
       .Y (n_192));
  OAI2BB1X1 g1513__6260(.A0N (req_addr[9]), .A1N (n_159), .B0 (n_161),
       .Y (n_194));
  OAI2BB1X1 g1514__4319(.A0N (req_addr[2]), .A1N (n_158), .B0 (n_164),
       .Y (n_188));
  OAI2BB1X1 g1515__8428(.A0N (req_addr[1]), .A1N (n_158), .B0 (n_162),
       .Y (n_187));
  OAI2BB1X1 g1516__5526(.A0N (req_addr[5]), .A1N (n_158), .B0 (n_163),
       .Y (n_191));
  OAI2BB1X1 g1517__6783(.A0N (req_addr[7]), .A1N (n_158), .B0 (n_160),
       .Y (n_193));
  OAI2BB1X1 g1518__3680(.A0N (req_addr[5]), .A1N (n_159), .B0 (n_165),
       .Y (n_190));
  AOI22X1 g1519__1617(.A0 (req_addr[7]), .A1 (n_159), .B0
       (sdr_width[1]), .B1 (req_addr[5]), .Y (n_167));
  AOI22X1 g1520__2802(.A0 (req_addr[3]), .A1 (n_158), .B0
       (sdr_width[1]), .B1 (req_addr[2]), .Y (n_166));
  AOI22X1 g1521__1705(.A0 (req_addr[4]), .A1 (n_158), .B0
       (sdr_width[1]), .B1 (req_addr[3]), .Y (n_165));
  AOI22X1 g1522__5122(.A0 (req_addr[3]), .A1 (n_159), .B0
       (sdr_width[1]), .B1 (req_addr[1]), .Y (n_164));
  AOI22X1 g1523__8246(.A0 (req_addr[6]), .A1 (n_159), .B0
       (sdr_width[1]), .B1 (req_addr[4]), .Y (n_163));
  AOI22X1 g1524__7098(.A0 (req_addr[2]), .A1 (n_159), .B0
       (sdr_width[1]), .B1 (req_addr[0]), .Y (n_162));
  AOI22X1 g1525__6131(.A0 (req_addr[8]), .A1 (n_158), .B0
       (sdr_width[1]), .B1 (req_addr[7]), .Y (n_161));
  AO22X1 g1526__1881(.A0 (req_addr[1]), .A1 (n_159), .B0 (req_addr[0]),
       .B1 (n_158), .Y (n_186));
  AOI22X1 g1527__5115(.A0 (req_addr[8]), .A1 (n_159), .B0
       (sdr_width[1]), .B1 (req_addr[6]), .Y (n_160));
  AND2X1 g1528__7482(.A (req_addr[0]), .B (n_159), .Y (n_272));
  INVX1 g1529(.A (n_159), .Y (n_176));
  NOR2X1 g1530__4733(.A (sdr_width[1]), .B (sdr_width[0]), .Y (n_159));
  INVX1 g1531(.A (n_158), .Y (n_175));
  NOR2BX1 g1532__6161(.AN (sdr_width[0]), .B (sdr_width[1]), .Y
       (n_158));
  OAI211X1 g1400__9315(.A0 (n_155), .A1 (n_176), .B0 (n_157), .C0
       (n_156), .Y (n_195));
  NAND2BXL g1401__9945(.AN (n_175), .B (req_addr[9]), .Y (n_157));
  NAND2X1 g1402__2883(.A (sdr_width[1]), .B (req_addr[8]), .Y (n_156));
  INVX1 g1403(.A (req_addr[10]), .Y (n_155));
  NOR2BX1 g1797__2346(.AN (r2b_len[2]), .B (n_135), .Y (n_245));
  NOR2BX1 g1798__1666(.AN (r2b_len[5]), .B (n_135), .Y (n_248));
  NOR2BX1 g1799__7410(.AN (r2b_len[4]), .B (n_135), .Y (n_247));
  NOR2BX1 g1800__6417(.AN (r2b_len[3]), .B (n_135), .Y (n_246));
  NOR2BX1 g1801__5477(.AN (r2b_len[6]), .B (n_135), .Y (n_249));
  NOR2BX1 g1802__2398(.AN (r2b_len[1]), .B (n_135), .Y (n_244));
  NOR2BX1 g1803__5107(.AN (r2b_len[0]), .B (n_135), .Y (n_243));
  NAND2X1 g1804__6260(.A (n_149), .B (n_146), .Y (n_258));
  OAI2BB1X1 g1805__4319(.A0N (n_270), .A1N (n_126), .B0 (n_150), .Y
       (n_259));
  NAND2X1 g1808__5526(.A (n_143), .B (n_142), .Y (n_257));
  NAND2X1 g1813__6783(.A (n_154), .B (n_153), .Y (n_253));
  OR3X4 g1814__3680(.A (n_168), .B (n_122), .C (r2b_req), .Y (n_309));
  OAI2BB1X1 g1815__1617(.A0N (req_len[7]), .A1N (n_121), .B0 (n_134),
       .Y (n_185));
  OAI2BB1X1 g1816__2802(.A0N (req_len[6]), .A1N (n_121), .B0 (n_133),
       .Y (n_184));
  OAI2BB1X1 g1817__1705(.A0N (req_len[5]), .A1N (n_121), .B0 (n_132),
       .Y (n_183));
  OAI2BB1X1 g1818__5122(.A0N (req_len[5]), .A1N (n_120), .B0 (n_131),
       .Y (n_182));
  OAI2BB1X1 g1819__8246(.A0N (req_len[3]), .A1N (n_121), .B0 (n_130),
       .Y (n_181));
  OAI2BB1X1 g1820__7098(.A0N (req_len[3]), .A1N (n_120), .B0 (n_129),
       .Y (n_180));
  OAI2BB1X1 g1821__6131(.A0N (req_len[1]), .A1N (n_121), .B0 (n_128),
       .Y (n_179));
  AOI22X1 g1826__5115(.A0 (n_293), .A1 (n_125), .B0 (n_281), .B1
       (n_124), .Y (n_150));
  AOI22X1 g1827__7482(.A0 (n_269), .A1 (n_126), .B0 (n_280), .B1
       (n_124), .Y (n_149));
  AOI22X1 g1830__4733(.A0 (n_302), .A1 (n_127), .B0 (n_292), .B1
       (n_125), .Y (n_146));
  AOI22X1 g1833__9315(.A0 (n_291), .A1 (n_125), .B0 (n_279), .B1
       (n_124), .Y (n_143));
  AOI22X1 g1834__9945(.A0 (n_301), .A1 (n_127), .B0 (n_268), .B1
       (n_126), .Y (n_142));
  AO22XL g1838__2346(.A0 (n_271), .A1 (n_126), .B0 (n_282), .B1
       (n_124), .Y (n_260));
  MX2XL g1842__1666(.A (max_r2b_len_r[5]), .B (lcl_req_len[5]), .S0
       (n_123), .Y (r2b_len[5]));
  MX2XL g1843__7410(.A (max_r2b_len_r[1]), .B (lcl_req_len[1]), .S0
       (n_123), .Y (r2b_len[1]));
  MX2XL g1844__6417(.A (max_r2b_len_r[0]), .B (lcl_req_len[0]), .S0
       (n_123), .Y (r2b_len[0]));
  MX2XL g1845__5477(.A (max_r2b_len_r[4]), .B (lcl_req_len[4]), .S0
       (n_123), .Y (r2b_len[4]));
  MX2XL g1846__2398(.A (max_r2b_len_r[3]), .B (lcl_req_len[3]), .S0
       (n_123), .Y (r2b_len[3]));
  MX2XL g1847__5107(.A (max_r2b_len_r[6]), .B (lcl_req_len[6]), .S0
       (n_123), .Y (r2b_len[6]));
  MX2XL g1848__6260(.A (max_r2b_len_r[2]), .B (lcl_req_len[2]), .S0
       (n_123), .Y (r2b_len[2]));
  AO22XL g1849__4319(.A0 (req_len[0]), .A1 (n_121), .B0 (req_len[1]),
       .B1 (n_120), .Y (n_178));
  NAND2X1 g1850__8428(.A (n_283), .B (n_124), .Y (n_177));
  NOR2X1 g1851__5526(.A (req), .B (r2b_req), .Y (r2x_idle));
  AOI22X1 g1852__6783(.A0 (req_len[8]), .A1 (n_120), .B0
       (sdr_width[1]), .B1 (req_len[6]), .Y (n_134));
  AOI22X1 g1853__3680(.A0 (req_len[7]), .A1 (n_120), .B0
       (sdr_width[1]), .B1 (req_len[5]), .Y (n_133));
  NAND2X1 g1854__1617(.A (b2r_ack), .B (r2b_req), .Y (n_135));
  AOI22X1 g1855__2802(.A0 (req_len[6]), .A1 (n_120), .B0
       (sdr_width[1]), .B1 (req_len[4]), .Y (n_132));
  AOI22X1 g1856__1705(.A0 (req_len[4]), .A1 (n_121), .B0
       (sdr_width[1]), .B1 (req_len[3]), .Y (n_131));
  AOI22X1 g1857__5122(.A0 (req_len[4]), .A1 (n_120), .B0
       (sdr_width[1]), .B1 (req_len[2]), .Y (n_130));
  OAI22XL g1858__8246(.A0 (n_119), .A1 (page_ovflw_r), .B0 (n_118), .B1
       (req_st[0]), .Y (r2b_last));
  AOI22X1 g1859__7098(.A0 (req_len[2]), .A1 (n_121), .B0
       (sdr_width[1]), .B1 (req_len[1]), .Y (n_129));
  AOI22X1 g1860__6131(.A0 (req_len[2]), .A1 (n_120), .B0
       (sdr_width[1]), .B1 (req_len[0]), .Y (n_128));
  INVX1 g1861(.A (n_127), .Y (n_306));
  INVX2 g1862(.A (n_126), .Y (n_303));
  NAND2X1 g1863__1881(.A (req_len[0]), .B (n_120), .Y (n_174));
  NOR2X1 g1864__5115(.A (cfg_colbits[1]), .B (cfg_colbits[0]), .Y
       (n_127));
  NOR2BX1 g1865__7482(.AN (cfg_colbits[1]), .B (cfg_colbits[0]), .Y
       (n_126));
  INVX2 g1866(.A (n_125), .Y (n_305));
  INVX1 g1867(.A (n_304), .Y (n_124));
  NAND2BX1 g1868__4733(.AN (req_st[0]), .B (n_118), .Y (r2b_req));
  NOR2BX1 g1869__6161(.AN (cfg_colbits[0]), .B (cfg_colbits[1]), .Y
       (n_125));
  NAND2X2 g1870__9315(.A (cfg_colbits[1]), .B (cfg_colbits[0]), .Y
       (n_304));
  NAND2X1 g1871__9945(.A (page_ovflw_r), .B (r2b_start), .Y (n_123));
  INVX1 g1872(.A (req), .Y (n_122));
  INVX1 g1873(.A (n_175), .Y (n_121));
  INVX1 g1874(.A (n_176), .Y (n_120));
  INVX1 g1875(.A (r2b_start), .Y (n_119));
  INVX1 g1876(.A (req_st[1]), .Y (n_118));
  DFFHQX1 \curr_sdr_addr_reg[0] (.CK (clk), .D (n_36), .Q
       (curr_sdr_addr[0]));
  DFFHQX1 \curr_sdr_addr_reg[1] (.CK (clk), .D (n_35), .Q
       (curr_sdr_addr[1]));
  DFFHQX1 \curr_sdr_addr_reg[2] (.CK (clk), .D (n_34), .Q
       (curr_sdr_addr[2]));
  DFFHQX1 \curr_sdr_addr_reg[3] (.CK (clk), .D (n_33), .Q
       (curr_sdr_addr[3]));
  DFFHQX1 \curr_sdr_addr_reg[4] (.CK (clk), .D (n_30), .Q
       (curr_sdr_addr[4]));
  DFFHQX1 \curr_sdr_addr_reg[5] (.CK (clk), .D (n_32), .Q
       (curr_sdr_addr[5]));
  DFFHQX1 \curr_sdr_addr_reg[6] (.CK (clk), .D (n_31), .Q
       (curr_sdr_addr[6]));
  DFFHQX1 \curr_sdr_addr_reg[7] (.CK (clk), .D (n_37), .Q
       (curr_sdr_addr[7]));
  DFFHQX1 \curr_sdr_addr_reg[8] (.CK (clk), .D (n_29), .Q
       (curr_sdr_addr[8]));
  DFFHQX1 \curr_sdr_addr_reg[9] (.CK (clk), .D (n_27), .Q
       (curr_sdr_addr[9]));
  DFFHQX1 \curr_sdr_addr_reg[10] (.CK (clk), .D (n_24), .Q
       (curr_sdr_addr[10]));
  DFFHQX1 \curr_sdr_addr_reg[11] (.CK (clk), .D (n_68), .Q
       (curr_sdr_addr[11]));
  DFFHQX1 \curr_sdr_addr_reg[12] (.CK (clk), .D (n_60), .Q
       (curr_sdr_addr[12]));
  DFFHQX1 \curr_sdr_addr_reg[13] (.CK (clk), .D (n_64), .Q
       (curr_sdr_addr[13]));
  DFFHQX1 \curr_sdr_addr_reg[14] (.CK (clk), .D (n_62), .Q
       (curr_sdr_addr[14]));
  DFFHQX1 \curr_sdr_addr_reg[15] (.CK (clk), .D (n_84), .Q
       (curr_sdr_addr[15]));
  DFFHQX1 \curr_sdr_addr_reg[16] (.CK (clk), .D (n_87), .Q
       (curr_sdr_addr[16]));
  DFFHQX1 \curr_sdr_addr_reg[17] (.CK (clk), .D (n_86), .Q
       (curr_sdr_addr[17]));
  DFFHQX1 \curr_sdr_addr_reg[18] (.CK (clk), .D (n_82), .Q
       (curr_sdr_addr[18]));
  DFFHQX1 \curr_sdr_addr_reg[19] (.CK (clk), .D (n_80), .Q
       (curr_sdr_addr[19]));
  DFFHQX1 \curr_sdr_addr_reg[20] (.CK (clk), .D (n_77), .Q
       (curr_sdr_addr[20]));
  DFFHQX1 \curr_sdr_addr_reg[21] (.CK (clk), .D (n_76), .Q
       (curr_sdr_addr[21]));
  DFFHQX1 \curr_sdr_addr_reg[22] (.CK (clk), .D (n_65), .Q
       (curr_sdr_addr[22]));
  DFFHQX1 \curr_sdr_addr_reg[23] (.CK (clk), .D (n_70), .Q
       (curr_sdr_addr[23]));
  DFFHQX1 \curr_sdr_addr_reg[24] (.CK (clk), .D (n_72), .Q
       (curr_sdr_addr[24]));
  DFFHQX1 \curr_sdr_addr_reg[25] (.CK (clk), .D (n_74), .Q
       (curr_sdr_addr[25]));
  SDFFQX1 \lcl_req_len_reg[0] (.CK (clk), .D (n_3), .SI (n_236), .SE
       (n_309), .Q (lcl_req_len[0]));
  SDFFQX1 \lcl_req_len_reg[1] (.CK (clk), .D (n_178), .SI (n_237), .SE
       (n_309), .Q (lcl_req_len[1]));
  SDFFQX1 \lcl_req_len_reg[2] (.CK (clk), .D (n_179), .SI (n_238), .SE
       (n_309), .Q (lcl_req_len[2]));
  SDFFQX1 \lcl_req_len_reg[3] (.CK (clk), .D (n_180), .SI (n_239), .SE
       (n_309), .Q (lcl_req_len[3]));
  SDFFQX1 \lcl_req_len_reg[4] (.CK (clk), .D (n_181), .SI (n_240), .SE
       (n_309), .Q (lcl_req_len[4]));
  SDFFQX1 \lcl_req_len_reg[5] (.CK (clk), .D (n_182), .SI (n_241), .SE
       (n_309), .Q (lcl_req_len[5]));
  SDFFQX1 \lcl_req_len_reg[6] (.CK (clk), .D (n_183), .SI (n_242), .SE
       (n_309), .Q (lcl_req_len[6]));
  SDFFQX1 lcl_wrap_reg(.CK (clk), .D (req_wrap), .SI (r2b_wrap), .SE
       (n_309), .Q (r2b_wrap));
  DFFHQX1 \max_r2b_len_r_reg[0] (.CK (clk), .D (n_21), .Q
       (max_r2b_len_r[0]));
  DFFHQX1 \max_r2b_len_r_reg[1] (.CK (clk), .D (n_18), .Q
       (max_r2b_len_r[1]));
  DFFHQX1 \max_r2b_len_r_reg[2] (.CK (clk), .D (n_16), .Q
       (max_r2b_len_r[2]));
  DFFHQX1 \max_r2b_len_r_reg[3] (.CK (clk), .D (n_12), .Q
       (max_r2b_len_r[3]));
  DFFHQX1 \max_r2b_len_r_reg[4] (.CK (clk), .D (n_17), .Q
       (max_r2b_len_r[4]));
  DFFHQX1 \max_r2b_len_r_reg[5] (.CK (clk), .D (n_11), .Q
       (max_r2b_len_r[5]));
  DFFHQX1 \max_r2b_len_r_reg[6] (.CK (clk), .D (n_20), .Q
       (max_r2b_len_r[6]));
  DFFQXL \max_r2b_len_r_reg[7] (.CK (clk), .D (n_9), .Q
       (max_r2b_len_r[7]));
  DFFQXL \max_r2b_len_r_reg[8] (.CK (clk), .D (n_6), .Q
       (max_r2b_len_r[8]));
  DFFHQX1 \max_r2b_len_r_reg[9] (.CK (clk), .D (n_8), .Q
       (max_r2b_len_r[9]));
  DFFQXL \max_r2b_len_r_reg[10] (.CK (clk), .D (n_7), .Q
       (max_r2b_len_r[10]));
  DFFQXL \max_r2b_len_r_reg[11] (.CK (clk), .D (n_10), .Q
       (max_r2b_len_r[11]));
  DFFHQX1 \max_r2b_len_r_reg[12] (.CK (clk), .D (1'b0), .Q
       (max_r2b_len_r[12]));
  DFFHQX1 page_ovflw_r_reg(.CK (clk), .D (n_22), .Q (page_ovflw_r));
  DFFHQX1 \r2b_ba_reg[0] (.CK (clk), .D (n_111), .Q (r2b_ba[0]));
  DFFHQX1 \r2b_ba_reg[1] (.CK (clk), .D (n_114), .Q (r2b_ba[1]));
  DFFHQX1 \r2b_caddr_reg[0] (.CK (clk), .D (n_36), .Q (r2b_caddr[0]));
  DFFHQX1 \r2b_caddr_reg[1] (.CK (clk), .D (n_35), .Q (r2b_caddr[1]));
  DFFHQX1 \r2b_caddr_reg[2] (.CK (clk), .D (n_34), .Q (r2b_caddr[2]));
  DFFHQX1 \r2b_caddr_reg[3] (.CK (clk), .D (n_33), .Q (r2b_caddr[3]));
  DFFHQX1 \r2b_caddr_reg[4] (.CK (clk), .D (n_30), .Q (r2b_caddr[4]));
  DFFHQX1 \r2b_caddr_reg[5] (.CK (clk), .D (n_32), .Q (r2b_caddr[5]));
  DFFHQX1 \r2b_caddr_reg[6] (.CK (clk), .D (n_31), .Q (r2b_caddr[6]));
  DFFHQX1 \r2b_caddr_reg[7] (.CK (clk), .D (n_37), .Q (r2b_caddr[7]));
  DFFHQX1 \r2b_caddr_reg[8] (.CK (clk), .D (n_0), .Q (r2b_caddr[8]));
  DFFHQX1 \r2b_caddr_reg[9] (.CK (clk), .D (n_45), .Q (r2b_caddr[9]));
  DFFHQX1 \r2b_caddr_reg[10] (.CK (clk), .D (n_44), .Q (r2b_caddr[10]));
  DFFHQX1 \r2b_caddr_reg[11] (.CK (clk), .D (1'b0), .Q (r2b_caddr[11]));
  DFFHQX1 \r2b_caddr_reg[12] (.CK (clk), .D (1'b0), .Q (r2b_caddr[12]));
  DFFHQX1 \r2b_raddr_reg[0] (.CK (clk), .D (n_113), .Q (r2b_raddr[0]));
  DFFHQX1 \r2b_raddr_reg[1] (.CK (clk), .D (n_112), .Q (r2b_raddr[1]));
  DFFHQX1 \r2b_raddr_reg[2] (.CK (clk), .D (n_105), .Q (r2b_raddr[2]));
  DFFHQX1 \r2b_raddr_reg[3] (.CK (clk), .D (n_117), .Q (r2b_raddr[3]));
  DFFHQX1 \r2b_raddr_reg[4] (.CK (clk), .D (n_106), .Q (r2b_raddr[4]));
  DFFHQX1 \r2b_raddr_reg[5] (.CK (clk), .D (n_109), .Q (r2b_raddr[5]));
  DFFHQX1 \r2b_raddr_reg[6] (.CK (clk), .D (n_108), .Q (r2b_raddr[6]));
  DFFHQX1 \r2b_raddr_reg[7] (.CK (clk), .D (n_104), .Q (r2b_raddr[7]));
  DFFHQX1 \r2b_raddr_reg[8] (.CK (clk), .D (n_103), .Q (r2b_raddr[8]));
  DFFHQX1 \r2b_raddr_reg[9] (.CK (clk), .D (n_107), .Q (r2b_raddr[9]));
  DFFHQX1 \r2b_raddr_reg[10] (.CK (clk), .D (n_110), .Q
       (r2b_raddr[10]));
  DFFHQX1 \r2b_raddr_reg[11] (.CK (clk), .D (n_115), .Q
       (r2b_raddr[11]));
  DFFHQX1 \r2b_raddr_reg[12] (.CK (clk), .D (n_116), .Q
       (r2b_raddr[12]));
  SDFFQX1 \r2b_req_id_reg[0] (.CK (clk), .D (req_id[0]), .SI
       (r2b_req_id[0]), .SE (n_309), .Q (r2b_req_id[0]));
  SDFFQX1 \r2b_req_id_reg[1] (.CK (clk), .D (req_id[1]), .SI
       (r2b_req_id[1]), .SE (n_309), .Q (r2b_req_id[1]));
  SDFFQX1 \r2b_req_id_reg[2] (.CK (clk), .D (req_id[2]), .SI
       (r2b_req_id[2]), .SE (n_309), .Q (r2b_req_id[2]));
  SDFFQX1 \r2b_req_id_reg[3] (.CK (clk), .D (req_id[3]), .SI
       (r2b_req_id[3]), .SE (n_309), .Q (r2b_req_id[3]));
  SDFFQX1 r2b_start_reg(.CK (clk), .D (n_2), .SI (r2b_start), .SE
       (n_15), .Q (r2b_start));
  SDFFQX1 r2b_write_reg(.CK (clk), .D (n_169), .SI (r2b_write), .SE
       (n_309), .Q (r2b_write));
  DFFHQX1 \req_st_reg[0] (.CK (clk), .D (n_43), .Q (req_st[0]));
  DFFHQX1 \req_st_reg[1] (.CK (clk), .D (n_57), .Q (req_st[1]));
  OAI221X1 g2084__2883(.A0 (n_304), .A1 (n_88), .B0 (n_303), .B1
       (n_83), .C0 (n_102), .Y (n_117));
  OAI221X1 g2085__2346(.A0 (n_305), .A1 (n_69), .B0 (n_304), .B1
       (n_73), .C0 (n_96), .Y (n_116));
  OAI221X1 g2086__1666(.A0 (n_303), .A1 (n_69), .B0 (n_304), .B1
       (n_71), .C0 (n_100), .Y (n_115));
  OAI221X1 g2087__7410(.A0 (n_306), .A1 (n_26), .B0 (n_305), .B1
       (n_25), .C0 (n_99), .Y (n_114));
  OAI221X1 g2088__6417(.A0 (n_305), .A1 (n_67), .B0 (n_306), .B1
       (n_25), .C0 (n_98), .Y (n_113));
  OAI221X1 g2089__5477(.A0 (n_303), .A1 (n_63), .B0 (n_304), .B1
       (n_61), .C0 (n_97), .Y (n_112));
  OAI221X1 g2090__2398(.A0 (n_304), .A1 (n_67), .B0 (n_303), .B1
       (n_25), .C0 (n_56), .Y (n_111));
  OAI221X1 g2091__5107(.A0 (n_303), .A1 (n_66), .B0 (n_305), .B1
       (n_75), .C0 (n_92), .Y (n_110));
  OAI221X1 g2092__6260(.A0 (n_303), .A1 (n_85), .B0 (n_304), .B1
       (n_81), .C0 (n_94), .Y (n_109));
  OAI221X1 g2093__4319(.A0 (n_304), .A1 (n_79), .B0 (n_303), .B1
       (n_81), .C0 (n_93), .Y (n_108));
  OAI221X1 g2094__8428(.A0 (n_306), .A1 (n_79), .B0 (n_303), .B1
       (n_75), .C0 (n_101), .Y (n_107));
  OAI221X1 g2095__5526(.A0 (n_304), .A1 (n_85), .B0 (n_305), .B1
       (n_83), .C0 (n_89), .Y (n_106));
  OAI221X1 g2096__6783(.A0 (n_305), .A1 (n_63), .B0 (n_303), .B1
       (n_61), .C0 (n_91), .Y (n_105));
  OAI221X1 g2097__3680(.A0 (n_303), .A1 (n_79), .B0 (n_305), .B1
       (n_81), .C0 (n_90), .Y (n_104));
  OAI221X1 g2098__1617(.A0 (n_305), .A1 (n_79), .B0 (n_303), .B1
       (n_78), .C0 (n_95), .Y (n_103));
  OA22X1 g2099__2802(.A0 (n_306), .A1 (n_63), .B0 (n_305), .B1 (n_61),
       .Y (n_102));
  OA22X1 g2100__1705(.A0 (n_304), .A1 (n_66), .B0 (n_305), .B1 (n_78),
       .Y (n_101));
  OA22X1 g2101__5122(.A0 (n_305), .A1 (n_66), .B0 (n_306), .B1 (n_75),
       .Y (n_100));
  OA22X1 g2102__8246(.A0 (n_303), .A1 (n_67), .B0 (n_304), .B1 (n_59),
       .Y (n_99));
  OA22X1 g2103__7098(.A0 (n_304), .A1 (n_63), .B0 (n_303), .B1 (n_59),
       .Y (n_98));
  OA22X1 g2104__6131(.A0 (n_306), .A1 (n_67), .B0 (n_305), .B1 (n_59),
       .Y (n_97));
  OA22X1 g2105__1881(.A0 (n_306), .A1 (n_66), .B0 (n_303), .B1 (n_71),
       .Y (n_96));
  OA22X1 g2106__5115(.A0 (n_306), .A1 (n_81), .B0 (n_304), .B1 (n_75),
       .Y (n_95));
  OA22X1 g2107__7482(.A0 (n_305), .A1 (n_88), .B0 (n_306), .B1 (n_83),
       .Y (n_94));
  OA22X1 g2108__4733(.A0 (n_306), .A1 (n_88), .B0 (n_305), .B1 (n_85),
       .Y (n_93));
  OA22X1 g2109__6161(.A0 (n_304), .A1 (n_69), .B0 (n_306), .B1 (n_78),
       .Y (n_92));
  OA22X1 g2110__9315(.A0 (n_306), .A1 (n_59), .B0 (n_304), .B1 (n_83),
       .Y (n_91));
  OA22X1 g2111__9945(.A0 (n_306), .A1 (n_85), .B0 (n_304), .B1 (n_78),
       .Y (n_90));
  OA22X1 g2112__2883(.A0 (n_303), .A1 (n_88), .B0 (n_306), .B1 (n_61),
       .Y (n_89));
  INVX1 g2128(.A (n_88), .Y (n_87));
  INVX1 g2129(.A (n_85), .Y (n_86));
  INVX1 g2130(.A (n_83), .Y (n_84));
  INVX1 g2131(.A (n_81), .Y (n_82));
  INVX1 g2132(.A (n_79), .Y (n_80));
  INVX1 g2133(.A (n_78), .Y (n_77));
  INVX1 g2134(.A (n_75), .Y (n_76));
  AOI221X1 g2136__2346(.A0 (req_addr[14]), .A1 (n_14), .B0 (n_226), .B1
       (n_309), .C0 (n_58), .Y (n_88));
  AOI221X1 g2137__1666(.A0 (req_addr[15]), .A1 (n_14), .B0 (n_227), .B1
       (n_309), .C0 (n_50), .Y (n_85));
  AOI221X1 g2138__7410(.A0 (req_addr[15]), .A1 (n_23), .B0 (n_225), .B1
       (n_309), .C0 (n_41), .Y (n_83));
  AOI221X1 g2139__6417(.A0 (req_addr[18]), .A1 (n_23), .B0 (n_228), .B1
       (n_309), .C0 (n_47), .Y (n_81));
  AOI221X1 g2140__5477(.A0 (req_addr[18]), .A1 (n_13), .B0 (n_229), .B1
       (n_309), .C0 (n_55), .Y (n_79));
  AOI221X1 g2141__2398(.A0 (req_addr[20]), .A1 (n_23), .B0 (n_230), .B1
       (n_309), .C0 (n_40), .Y (n_78));
  AOI221X1 g2142__5107(.A0 (req_addr[21]), .A1 (n_23), .B0 (n_231), .B1
       (n_309), .C0 (n_39), .Y (n_75));
  INVX1 g2143(.A (n_73), .Y (n_74));
  INVX1 g2144(.A (n_71), .Y (n_72));
  INVX1 g2145(.A (n_69), .Y (n_70));
  INVX1 g2146(.A (n_67), .Y (n_68));
  INVX1 g2147(.A (n_66), .Y (n_65));
  INVX1 g2148(.A (n_63), .Y (n_64));
  INVX1 g2149(.A (n_61), .Y (n_62));
  INVX1 g2150(.A (n_59), .Y (n_60));
  AOI221X1 g2151__6260(.A0 (req_addr[24]), .A1 (n_13), .B0
       (req_addr[23]), .B1 (n_14), .C0 (n_53), .Y (n_73));
  AOI221X1 g2152__4319(.A0 (req_addr[24]), .A1 (n_23), .B0
       (req_addr[22]), .B1 (n_14), .C0 (n_46), .Y (n_71));
  AOI221X1 g2153__8428(.A0 (req_addr[21]), .A1 (n_14), .B0 (n_233), .B1
       (n_309), .C0 (n_54), .Y (n_69));
  AOI221X1 g2154__5526(.A0 (req_addr[11]), .A1 (n_23), .B0
       (req_addr[9]), .B1 (n_14), .C0 (n_48), .Y (n_67));
  AOI221X1 g2155__6783(.A0 (req_addr[22]), .A1 (n_23), .B0
       (req_addr[20]), .B1 (n_14), .C0 (n_38), .Y (n_66));
  AOI221X1 g2156__3680(.A0 (req_addr[13]), .A1 (n_23), .B0
       (req_addr[11]), .B1 (n_14), .C0 (n_49), .Y (n_63));
  AOI221X1 g2157__1617(.A0 (req_addr[13]), .A1 (n_13), .B0
       (req_addr[12]), .B1 (n_14), .C0 (n_51), .Y (n_61));
  AOI221X1 g2158__2802(.A0 (req_addr[11]), .A1 (n_13), .B0
       (req_addr[10]), .B1 (n_14), .C0 (n_52), .Y (n_59));
  AO22XL g2159__1705(.A0 (req_addr[16]), .A1 (n_23), .B0
       (req_addr[15]), .B1 (n_13), .Y (n_58));
  NOR2BX1 g2163__5122(.AN (reset_n), .B (n_42), .Y (n_57));
  OA22X1 g2166__8246(.A0 (n_306), .A1 (n_28), .B0 (n_305), .B1 (n_26),
       .Y (n_56));
  AO22XL g2167__7098(.A0 (req_addr[19]), .A1 (n_23), .B0
       (req_addr[17]), .B1 (n_14), .Y (n_55));
  AO22XL g2168__6131(.A0 (req_addr[23]), .A1 (n_23), .B0
       (req_addr[22]), .B1 (n_13), .Y (n_54));
  AO22XL g2169__1881(.A0 (req_addr[25]), .A1 (n_23), .B0 (n_235), .B1
       (n_309), .Y (n_53));
  AO22XL g2170__5115(.A0 (req_addr[12]), .A1 (n_23), .B0 (n_222), .B1
       (n_309), .Y (n_52));
  AO22XL g2171__7482(.A0 (req_addr[14]), .A1 (n_23), .B0 (n_224), .B1
       (n_309), .Y (n_51));
  AO22XL g2172__4733(.A0 (req_addr[17]), .A1 (n_23), .B0
       (req_addr[16]), .B1 (n_13), .Y (n_50));
  AO22XL g2196__6161(.A0 (req_addr[12]), .A1 (n_13), .B0 (n_223), .B1
       (n_309), .Y (n_49));
  AO22XL g2197__9315(.A0 (req_addr[10]), .A1 (n_13), .B0 (n_221), .B1
       (n_309), .Y (n_48));
  AO22XL g2198__9945(.A0 (req_addr[17]), .A1 (n_13), .B0
       (req_addr[16]), .B1 (n_14), .Y (n_47));
  AO22XL g2205__2883(.A0 (req_addr[23]), .A1 (n_13), .B0 (n_234), .B1
       (n_309), .Y (n_46));
  NOR2BX1 g2206__2346(.AN (cfg_colbits[1]), .B (n_26), .Y (n_45));
  NOR2X1 g2208__1666(.A (n_304), .B (n_25), .Y (n_44));
  OA21X1 g2209__7410(.A0 (n_2), .A1 (n_19), .B0 (reset_n), .Y (n_43));
  AOI32X1 g2210__6417(.A0 (b2r_ack), .A1 (page_ovflw_r), .A2
       (req_st[0]), .B0 (req_st[1]), .B1 (n_4), .Y (n_42));
  AO22XL g2211__5477(.A0 (req_addr[14]), .A1 (n_13), .B0
       (req_addr[13]), .B1 (n_14), .Y (n_41));
  AO22XL g2212__2398(.A0 (req_addr[19]), .A1 (n_13), .B0
       (req_addr[18]), .B1 (n_14), .Y (n_40));
  AO22XL g2213__5107(.A0 (req_addr[20]), .A1 (n_13), .B0
       (req_addr[19]), .B1 (n_14), .Y (n_39));
  AO22XL g2214__6260(.A0 (req_addr[21]), .A1 (n_13), .B0 (n_232), .B1
       (n_309), .Y (n_38));
  INVX1 g2231(.A (n_28), .Y (n_29));
  INVX1 g2232(.A (n_26), .Y (n_27));
  INVX1 g2233(.A (n_25), .Y (n_24));
  NOR3BX1 g2234__4319(.AN (n_209), .B (n_309), .C (r2b_wrap), .Y
       (n_22));
  MX2XL g2235__8428(.A (n_192), .B (n_217), .S0 (n_309), .Y (n_37));
  MX2XL g2236__5526(.A (n_272), .B (n_210), .S0 (n_309), .Y (n_36));
  MX2XL g2237__6783(.A (n_186), .B (n_211), .S0 (n_309), .Y (n_35));
  MX2XL g2238__3680(.A (n_187), .B (n_212), .S0 (n_309), .Y (n_34));
  MX2XL g2239__1617(.A (n_188), .B (n_213), .S0 (n_309), .Y (n_33));
  MX2XL g2240__2802(.A (n_190), .B (n_215), .S0 (n_309), .Y (n_32));
  MX2XL g2241__1705(.A (n_191), .B (n_216), .S0 (n_309), .Y (n_31));
  MX2XL g2242__5122(.A (n_189), .B (n_214), .S0 (n_309), .Y (n_30));
  AOI22X1 g2243__8246(.A0 (n_193), .A1 (n_2), .B0 (n_218), .B1 (n_309),
       .Y (n_28));
  AOI22X1 g2244__7098(.A0 (n_194), .A1 (n_2), .B0 (n_219), .B1 (n_309),
       .Y (n_26));
  AOI22X1 g2245__6131(.A0 (n_195), .A1 (n_2), .B0 (n_220), .B1 (n_309),
       .Y (n_25));
  NOR2BX1 g2246__1881(.AN (n_5), .B (sdr_width[1]), .Y (n_23));
  NOR2BX1 g2249__5115(.AN (n_250), .B (n_309), .Y (n_21));
  NOR2BX1 g2250__7482(.AN (n_256), .B (n_309), .Y (n_20));
  NOR2BX1 g2252__4733(.AN (req_st[0]), .B (b2r_ack), .Y (n_19));
  NOR2BX1 g2253__6161(.AN (n_369), .B (n_309), .Y (n_18));
  NOR2BX1 g2254__9315(.AN (n_254), .B (n_309), .Y (n_17));
  NOR2BX1 g2255__9945(.AN (n_252), .B (n_309), .Y (n_16));
  NOR2XL g2256__2883(.A (n_2), .B (b2r_ack), .Y (n_15));
  NOR2BX1 g2257__2346(.AN (n_253), .B (n_309), .Y (n_12));
  NOR2BX1 g2258__1666(.AN (n_255), .B (n_309), .Y (n_11));
  NOR2XL g2259__7410(.A (n_309), .B (n_177), .Y (n_10));
  NOR2BX1 g2260__6417(.AN (n_257), .B (n_309), .Y (n_9));
  NOR2BX1 g2261__5477(.AN (n_259), .B (n_309), .Y (n_8));
  NOR2BX1 g2262__2398(.AN (n_260), .B (n_309), .Y (n_7));
  NOR2BX1 g2263__5107(.AN (n_258), .B (n_309), .Y (n_6));
  NOR2X1 g2264__6260(.A (sdr_width[0]), .B (n_309), .Y (n_5));
  AND2X1 g2265__4319(.A (sdr_width[1]), .B (n_2), .Y (n_14));
  NOR2X1 g2266__8428(.A (n_309), .B (n_175), .Y (n_13));
  INVX1 g2267(.A (b2r_ack), .Y (n_4));
  INVX1 g2268(.A (n_174), .Y (n_3));
  INVX1 g2270(.A (n_309), .Y (n_2));
  NOR2BX1 g2__5526(.AN (n_306), .B (n_28), .Y (n_0));
  ADDHX1 ADD_TC_OP_g171__6783(.A (n_996), .B (ADD_TC_OP_n_16), .CO
       (n_271), .S (n_270));
  AOI2BB1XL ADD_TC_OP_g172__3680(.A0N (n_997), .A1N (ADD_TC_OP_n_14),
       .B0 (ADD_TC_OP_n_16), .Y (n_269));
  AND2XL ADD_TC_OP_g173__1617(.A (n_997), .B (ADD_TC_OP_n_14), .Y
       (ADD_TC_OP_n_16));
  AOI2BB1X1 ADD_TC_OP_g174__2802(.A0N (n_998), .A1N (ADD_TC_OP_n_12),
       .B0 (ADD_TC_OP_n_14), .Y (n_268));
  AND2XL ADD_TC_OP_g175__1705(.A (n_998), .B (ADD_TC_OP_n_12), .Y
       (ADD_TC_OP_n_14));
  AND2XL ADD_TC_OP_g177__5122(.A (n_999), .B (ADD_TC_OP_n_10), .Y
       (ADD_TC_OP_n_12));
  AND2XL ADD_TC_OP_g179__7098(.A (n_1000), .B (ADD_TC_OP_n_8), .Y
       (ADD_TC_OP_n_10));
  AND2XL ADD_TC_OP_g181__1881(.A (n_1001), .B (ADD_TC_OP_n_6), .Y
       (ADD_TC_OP_n_8));
  AND2XL ADD_TC_OP_g183__7482(.A (n_1002), .B (ADD_TC_OP_n_4), .Y
       (ADD_TC_OP_n_6));
  AND2XL ADD_TC_OP_g185__6161(.A (n_1003), .B (ADD_TC_OP_n_2), .Y
       (ADD_TC_OP_n_4));
  NOR2BX1 ADD_TC_OP_g187__9945(.AN (n_370), .B (n_261), .Y
       (ADD_TC_OP_n_2));
  INVX1 ADD_TC_OP_g188(.A (n_1005), .Y (n_261));
  XNOR2X1 ADD_TC_OP82_g441__2883(.A (curr_sdr_addr[25]), .B
       (ADD_TC_OP82_n_48), .Y (n_235));
  OA21X1 ADD_TC_OP82_g442__2346(.A0 (curr_sdr_addr[24]), .A1
       (ADD_TC_OP82_n_46), .B0 (ADD_TC_OP82_n_48), .Y (n_234));
  NAND2X1 ADD_TC_OP82_g443__1666(.A (curr_sdr_addr[24]), .B
       (ADD_TC_OP82_n_46), .Y (ADD_TC_OP82_n_48));
  AOI2BB1XL ADD_TC_OP82_g444__7410(.A0N (curr_sdr_addr[23]), .A1N
       (ADD_TC_OP82_n_44), .B0 (ADD_TC_OP82_n_46), .Y (n_233));
  AND2XL ADD_TC_OP82_g445__6417(.A (curr_sdr_addr[23]), .B
       (ADD_TC_OP82_n_44), .Y (ADD_TC_OP82_n_46));
  AOI2BB1XL ADD_TC_OP82_g446__5477(.A0N (curr_sdr_addr[22]), .A1N
       (ADD_TC_OP82_n_42), .B0 (ADD_TC_OP82_n_44), .Y (n_232));
  AND2XL ADD_TC_OP82_g447__2398(.A (curr_sdr_addr[22]), .B
       (ADD_TC_OP82_n_42), .Y (ADD_TC_OP82_n_44));
  AOI2BB1XL ADD_TC_OP82_g448__5107(.A0N (curr_sdr_addr[21]), .A1N
       (ADD_TC_OP82_n_40), .B0 (ADD_TC_OP82_n_42), .Y (n_231));
  AND2XL ADD_TC_OP82_g449__6260(.A (curr_sdr_addr[21]), .B
       (ADD_TC_OP82_n_40), .Y (ADD_TC_OP82_n_42));
  AOI2BB1XL ADD_TC_OP82_g450__4319(.A0N (curr_sdr_addr[20]), .A1N
       (ADD_TC_OP82_n_38), .B0 (ADD_TC_OP82_n_40), .Y (n_230));
  AND2XL ADD_TC_OP82_g451__8428(.A (curr_sdr_addr[20]), .B
       (ADD_TC_OP82_n_38), .Y (ADD_TC_OP82_n_40));
  AOI2BB1XL ADD_TC_OP82_g452__5526(.A0N (curr_sdr_addr[19]), .A1N
       (ADD_TC_OP82_n_36), .B0 (ADD_TC_OP82_n_38), .Y (n_229));
  AND2XL ADD_TC_OP82_g453__6783(.A (curr_sdr_addr[19]), .B
       (ADD_TC_OP82_n_36), .Y (ADD_TC_OP82_n_38));
  AOI2BB1XL ADD_TC_OP82_g454__3680(.A0N (curr_sdr_addr[18]), .A1N
       (ADD_TC_OP82_n_34), .B0 (ADD_TC_OP82_n_36), .Y (n_228));
  AND2XL ADD_TC_OP82_g455__1617(.A (curr_sdr_addr[18]), .B
       (ADD_TC_OP82_n_34), .Y (ADD_TC_OP82_n_36));
  AOI2BB1XL ADD_TC_OP82_g456__2802(.A0N (curr_sdr_addr[17]), .A1N
       (ADD_TC_OP82_n_32), .B0 (ADD_TC_OP82_n_34), .Y (n_227));
  AND2XL ADD_TC_OP82_g457__1705(.A (curr_sdr_addr[17]), .B
       (ADD_TC_OP82_n_32), .Y (ADD_TC_OP82_n_34));
  AOI2BB1XL ADD_TC_OP82_g458__5122(.A0N (curr_sdr_addr[16]), .A1N
       (ADD_TC_OP82_n_30), .B0 (ADD_TC_OP82_n_32), .Y (n_226));
  AND2XL ADD_TC_OP82_g459__8246(.A (curr_sdr_addr[16]), .B
       (ADD_TC_OP82_n_30), .Y (ADD_TC_OP82_n_32));
  AOI2BB1XL ADD_TC_OP82_g460__7098(.A0N (curr_sdr_addr[15]), .A1N
       (ADD_TC_OP82_n_28), .B0 (ADD_TC_OP82_n_30), .Y (n_225));
  AND2XL ADD_TC_OP82_g461__6131(.A (curr_sdr_addr[15]), .B
       (ADD_TC_OP82_n_28), .Y (ADD_TC_OP82_n_30));
  AOI2BB1XL ADD_TC_OP82_g462__1881(.A0N (curr_sdr_addr[14]), .A1N
       (ADD_TC_OP82_n_26), .B0 (ADD_TC_OP82_n_28), .Y (n_224));
  AND2XL ADD_TC_OP82_g463__5115(.A (curr_sdr_addr[14]), .B
       (ADD_TC_OP82_n_26), .Y (ADD_TC_OP82_n_28));
  AOI2BB1XL ADD_TC_OP82_g464__7482(.A0N (curr_sdr_addr[13]), .A1N
       (ADD_TC_OP82_n_24), .B0 (ADD_TC_OP82_n_26), .Y (n_223));
  AND2XL ADD_TC_OP82_g465__4733(.A (curr_sdr_addr[13]), .B
       (ADD_TC_OP82_n_24), .Y (ADD_TC_OP82_n_26));
  AOI2BB1XL ADD_TC_OP82_g466__6161(.A0N (curr_sdr_addr[12]), .A1N
       (ADD_TC_OP82_n_22), .B0 (ADD_TC_OP82_n_24), .Y (n_222));
  AND2XL ADD_TC_OP82_g467__9315(.A (curr_sdr_addr[12]), .B
       (ADD_TC_OP82_n_22), .Y (ADD_TC_OP82_n_24));
  AOI2BB1XL ADD_TC_OP82_g468__9945(.A0N (curr_sdr_addr[11]), .A1N
       (ADD_TC_OP82_n_20), .B0 (ADD_TC_OP82_n_22), .Y (n_221));
  AND2XL ADD_TC_OP82_g469__2883(.A (curr_sdr_addr[11]), .B
       (ADD_TC_OP82_n_20), .Y (ADD_TC_OP82_n_22));
  AOI2BB1X1 ADD_TC_OP82_g470__2346(.A0N (curr_sdr_addr[10]), .A1N
       (ADD_TC_OP82_n_18), .B0 (ADD_TC_OP82_n_20), .Y (n_220));
  AND2XL ADD_TC_OP82_g471__1666(.A (curr_sdr_addr[10]), .B
       (ADD_TC_OP82_n_18), .Y (ADD_TC_OP82_n_20));
  AOI2BB1XL ADD_TC_OP82_g472__7410(.A0N (curr_sdr_addr[9]), .A1N
       (ADD_TC_OP82_n_16), .B0 (ADD_TC_OP82_n_18), .Y (n_219));
  AND2XL ADD_TC_OP82_g473__6417(.A (curr_sdr_addr[9]), .B
       (ADD_TC_OP82_n_16), .Y (ADD_TC_OP82_n_18));
  AOI2BB1X1 ADD_TC_OP82_g474__5477(.A0N (curr_sdr_addr[8]), .A1N
       (ADD_TC_OP82_n_14), .B0 (ADD_TC_OP82_n_16), .Y (n_218));
  AND2XL ADD_TC_OP82_g475__2398(.A (curr_sdr_addr[8]), .B
       (ADD_TC_OP82_n_14), .Y (ADD_TC_OP82_n_16));
  AOI2BB1XL ADD_TC_OP82_g476__5107(.A0N (curr_sdr_addr[7]), .A1N
       (ADD_TC_OP82_n_13), .B0 (ADD_TC_OP82_n_14), .Y (n_217));
  AND2XL ADD_TC_OP82_g477__6260(.A (curr_sdr_addr[7]), .B
       (ADD_TC_OP82_n_13), .Y (ADD_TC_OP82_n_14));
  ADDFX1 ADD_TC_OP82_g478__4319(.A (ADD_TC_OP82_n_10), .B (n_249), .CI
       (curr_sdr_addr[6]), .CO (ADD_TC_OP82_n_13), .S (n_216));
  ADDFX1 ADD_TC_OP82_g479__8428(.A (ADD_TC_OP82_n_8), .B (n_248), .CI
       (curr_sdr_addr[5]), .CO (ADD_TC_OP82_n_10), .S (n_215));
  ADDFX1 ADD_TC_OP82_g480__5526(.A (ADD_TC_OP82_n_6), .B (n_247), .CI
       (curr_sdr_addr[4]), .CO (ADD_TC_OP82_n_8), .S (n_214));
  ADDFX1 ADD_TC_OP82_g481__6783(.A (ADD_TC_OP82_n_4), .B (n_246), .CI
       (curr_sdr_addr[3]), .CO (ADD_TC_OP82_n_6), .S (n_213));
  ADDFX1 ADD_TC_OP82_g482__3680(.A (ADD_TC_OP82_n_2), .B (n_245), .CI
       (curr_sdr_addr[2]), .CO (ADD_TC_OP82_n_4), .S (n_212));
  ADDFX1 ADD_TC_OP82_g483__1617(.A (ADD_TC_OP82_n_0), .B (n_244), .CI
       (curr_sdr_addr[1]), .CO (ADD_TC_OP82_n_2), .S (n_211));
  AOI2BB1XL ADD_TC_OP82_g484__2802(.A0N (curr_sdr_addr[0]), .A1N
       (n_243), .B0 (ADD_TC_OP82_n_0), .Y (n_210));
  AND2XL ADD_TC_OP82_g485__1705(.A (curr_sdr_addr[0]), .B (n_243), .Y
       (ADD_TC_OP82_n_0));
  ADDHX1 ADD_TC_OP85_g161__5122(.A (n_941), .B (ADD_TC_OP85_n_14), .CO
       (n_293), .S (n_292));
  AOI2BB1XL ADD_TC_OP85_g162__8246(.A0N (n_942), .A1N
       (ADD_TC_OP85_n_12), .B0 (ADD_TC_OP85_n_14), .Y (n_291));
  AND2XL ADD_TC_OP85_g163__7098(.A (n_942), .B (ADD_TC_OP85_n_12), .Y
       (ADD_TC_OP85_n_14));
  AOI2BB1XL ADD_TC_OP85_g164__6131(.A0N (n_943), .A1N
       (ADD_TC_OP85_n_10), .B0 (ADD_TC_OP85_n_12), .Y (n_290));
  AND2XL ADD_TC_OP85_g165__1881(.A (n_943), .B (ADD_TC_OP85_n_10), .Y
       (ADD_TC_OP85_n_12));
  AND2XL ADD_TC_OP85_g167__7482(.A (n_944), .B (ADD_TC_OP85_n_8), .Y
       (ADD_TC_OP85_n_10));
  AND2XL ADD_TC_OP85_g169__6161(.A (n_945), .B (ADD_TC_OP85_n_6), .Y
       (ADD_TC_OP85_n_8));
  AND2XL ADD_TC_OP85_g171__9315(.A (n_946), .B (ADD_TC_OP85_n_4), .Y
       (ADD_TC_OP85_n_6));
  AND2XL ADD_TC_OP85_g173__9945(.A (n_947), .B (ADD_TC_OP85_n_2), .Y
       (ADD_TC_OP85_n_4));
  NOR2BX1 ADD_TC_OP85_g175__2346(.AN (n_948), .B (n_284), .Y
       (ADD_TC_OP85_n_2));
  INVX1 ADD_TC_OP85_g176(.A (n_949), .Y (n_284));
  ADDHX1 ADD_TC_OP86_g151__1666(.A (n_900), .B (ADD_TC_OP86_n_12), .CO
       (n_302), .S (n_301));
  AND2XL ADD_TC_OP86_g153__7410(.A (n_901), .B (ADD_TC_OP86_n_10), .Y
       (ADD_TC_OP86_n_12));
  AND2XL ADD_TC_OP86_g155__6417(.A (n_902), .B (ADD_TC_OP86_n_8), .Y
       (ADD_TC_OP86_n_10));
  AND2XL ADD_TC_OP86_g157__5477(.A (n_903), .B (ADD_TC_OP86_n_6), .Y
       (ADD_TC_OP86_n_8));
  AND2XL ADD_TC_OP86_g159__5107(.A (n_904), .B (ADD_TC_OP86_n_4), .Y
       (ADD_TC_OP86_n_6));
  AND2XL ADD_TC_OP86_g161__6260(.A (n_905), .B (ADD_TC_OP86_n_2), .Y
       (ADD_TC_OP86_n_4));
  NOR2BX1 ADD_TC_OP86_g163__4319(.AN (n_906), .B (n_294), .Y
       (ADD_TC_OP86_n_2));
  INVX1 ADD_TC_OP86_g164(.A (n_907), .Y (n_294));
  XOR2XL SUB_TC_OP84_g272__8428(.A (SUB_TC_OP84_n_7), .B
       (SUB_TC_OP84_n_17), .Y (n_242));
  ADDFX1 SUB_TC_OP84_g273__5526(.A (SUB_TC_OP84_n_15), .B
       (lcl_req_len[5]), .CI (SUB_TC_OP84_n_0), .CO (SUB_TC_OP84_n_17),
       .S (n_241));
  ADDFX1 SUB_TC_OP84_g274__6783(.A (SUB_TC_OP84_n_13), .B
       (lcl_req_len[4]), .CI (SUB_TC_OP84_n_1), .CO (SUB_TC_OP84_n_15),
       .S (n_240));
  ADDFX1 SUB_TC_OP84_g275__3680(.A (SUB_TC_OP84_n_11), .B
       (lcl_req_len[3]), .CI (SUB_TC_OP84_n_3), .CO (SUB_TC_OP84_n_13),
       .S (n_239));
  ADDFX1 SUB_TC_OP84_g276__1617(.A (SUB_TC_OP84_n_9), .B
       (lcl_req_len[2]), .CI (SUB_TC_OP84_n_5), .CO (SUB_TC_OP84_n_11),
       .S (n_238));
  ADDFX1 SUB_TC_OP84_g277__2802(.A (SUB_TC_OP84_n_6), .B
       (lcl_req_len[1]), .CI (SUB_TC_OP84_n_2), .CO (SUB_TC_OP84_n_9),
       .S (n_237));
  OAI2BB1X1 SUB_TC_OP84_g278__1705(.A0N (lcl_req_len[0]), .A1N
       (SUB_TC_OP84_n_4), .B0 (SUB_TC_OP84_n_6), .Y (n_236));
  XNOR2X1 SUB_TC_OP84_g279__5122(.A (lcl_req_len[6]), .B (n_249), .Y
       (SUB_TC_OP84_n_7));
  NAND2BX1 SUB_TC_OP84_g280__8246(.AN (lcl_req_len[0]), .B (n_243), .Y
       (SUB_TC_OP84_n_6));
  INVX1 SUB_TC_OP84_g281(.A (n_245), .Y (SUB_TC_OP84_n_5));
  INVX1 SUB_TC_OP84_g282(.A (n_243), .Y (SUB_TC_OP84_n_4));
  INVX1 SUB_TC_OP84_g283(.A (n_246), .Y (SUB_TC_OP84_n_3));
  INVX1 SUB_TC_OP84_g284(.A (n_244), .Y (SUB_TC_OP84_n_2));
  INVX1 SUB_TC_OP84_g285(.A (n_247), .Y (SUB_TC_OP84_n_1));
  INVX1 SUB_TC_OP84_g286(.A (n_248), .Y (SUB_TC_OP84_n_0));
  ADDHX1 SUB_TC_OP_1_g184__7098(.A (SUB_TC_OP_1_n_2), .B
       (SUB_TC_OP_1_n_22), .CO (n_283), .S (n_282));
  AOI21X1 SUB_TC_OP_1_g185__6131(.A0 (n_194), .A1 (SUB_TC_OP_1_n_20),
       .B0 (SUB_TC_OP_1_n_22), .Y (n_281));
  NOR2X1 SUB_TC_OP_1_g186__1881(.A (n_194), .B (SUB_TC_OP_1_n_20), .Y
       (SUB_TC_OP_1_n_22));
  OA21X1 SUB_TC_OP_1_g187__5115(.A0 (SUB_TC_OP_1_n_1), .A1
       (SUB_TC_OP_1_n_18), .B0 (SUB_TC_OP_1_n_20), .Y (n_280));
  NAND2X1 SUB_TC_OP_1_g188__7482(.A (SUB_TC_OP_1_n_1), .B
       (SUB_TC_OP_1_n_18), .Y (SUB_TC_OP_1_n_20));
  AOI21X1 SUB_TC_OP_1_g189__4733(.A0 (n_192), .A1 (SUB_TC_OP_1_n_16),
       .B0 (SUB_TC_OP_1_n_18), .Y (n_279));
  NOR2X1 SUB_TC_OP_1_g190__6161(.A (n_192), .B (SUB_TC_OP_1_n_16), .Y
       (SUB_TC_OP_1_n_18));
  NAND2X1 SUB_TC_OP_1_g192__9315(.A (SUB_TC_OP_1_n_5), .B
       (SUB_TC_OP_1_n_14), .Y (SUB_TC_OP_1_n_16));
  NOR2X1 SUB_TC_OP_1_g194__9945(.A (n_190), .B (SUB_TC_OP_1_n_12), .Y
       (SUB_TC_OP_1_n_14));
  NAND2X1 SUB_TC_OP_1_g196__2883(.A (SUB_TC_OP_1_n_4), .B
       (SUB_TC_OP_1_n_10), .Y (SUB_TC_OP_1_n_12));
  NOR2X1 SUB_TC_OP_1_g198__2346(.A (n_188), .B (SUB_TC_OP_1_n_8), .Y
       (SUB_TC_OP_1_n_10));
  NAND2X1 SUB_TC_OP_1_g200__7410(.A (SUB_TC_OP_1_n_3), .B
       (SUB_TC_OP_1_n_6), .Y (SUB_TC_OP_1_n_8));
  NOR2X1 SUB_TC_OP_1_g202__6417(.A (n_186), .B (n_272), .Y
       (SUB_TC_OP_1_n_6));
  INVX1 SUB_TC_OP_1_g203(.A (n_191), .Y (SUB_TC_OP_1_n_5));
  INVX1 SUB_TC_OP_1_g204(.A (n_189), .Y (SUB_TC_OP_1_n_4));
  INVX1 SUB_TC_OP_1_g205(.A (n_187), .Y (SUB_TC_OP_1_n_3));
  INVX1 SUB_TC_OP_1_g206(.A (n_195), .Y (SUB_TC_OP_1_n_2));
  INVX1 SUB_TC_OP_1_g207(.A (n_193), .Y (SUB_TC_OP_1_n_1));
  NOR3BX1 SUB_UNS_OP_g190__5477(.AN (SUB_UNS_OP_n_25), .B (n_260), .C
       (n_172), .Y (n_209));
  AOI221X1 SUB_UNS_OP_g191__2398(.A0 (n_258), .A1 (SUB_UNS_OP_n_8), .B0
       (SUB_UNS_OP_n_11), .B1 (SUB_UNS_OP_n_24), .C0 (n_259), .Y
       (SUB_UNS_OP_n_25));
  OAI22X1 SUB_UNS_OP_g192__5107(.A0 (SUB_UNS_OP_n_15), .A1
       (SUB_UNS_OP_n_23), .B0 (SUB_UNS_OP_n_4), .B1 (n_184), .Y
       (SUB_UNS_OP_n_24));
  AOI22X1 SUB_UNS_OP_g193__6260(.A0 (SUB_UNS_OP_n_10), .A1
       (SUB_UNS_OP_n_22), .B0 (n_256), .B1 (SUB_UNS_OP_n_7), .Y
       (SUB_UNS_OP_n_23));
  OAI22X1 SUB_UNS_OP_g194__4319(.A0 (SUB_UNS_OP_n_9), .A1
       (SUB_UNS_OP_n_21), .B0 (SUB_UNS_OP_n_3), .B1 (n_182), .Y
       (SUB_UNS_OP_n_22));
  AOI22X1 SUB_UNS_OP_g195__8428(.A0 (SUB_UNS_OP_n_16), .A1
       (SUB_UNS_OP_n_20), .B0 (n_254), .B1 (SUB_UNS_OP_n_2), .Y
       (SUB_UNS_OP_n_21));
  OAI22X1 SUB_UNS_OP_g196__5526(.A0 (SUB_UNS_OP_n_13), .A1
       (SUB_UNS_OP_n_19), .B0 (SUB_UNS_OP_n_1), .B1 (n_180), .Y
       (SUB_UNS_OP_n_20));
  AOI22X1 SUB_UNS_OP_g197__6783(.A0 (SUB_UNS_OP_n_12), .A1
       (SUB_UNS_OP_n_18), .B0 (n_252), .B1 (SUB_UNS_OP_n_5), .Y
       (SUB_UNS_OP_n_19));
  OAI22X1 SUB_UNS_OP_g198__3680(.A0 (n_178), .A1 (SUB_UNS_OP_n_17), .B0
       (SUB_UNS_OP_n_6), .B1 (SUB_UNS_OP_n_14), .Y (SUB_UNS_OP_n_18));
  NOR2BX1 SUB_UNS_OP_g199__1617(.AN (SUB_UNS_OP_n_14), .B (n_369), .Y
       (SUB_UNS_OP_n_17));
  OR2XL SUB_UNS_OP_g200__2802(.A (SUB_UNS_OP_n_2), .B (n_254), .Y
       (SUB_UNS_OP_n_16));
  NOR2BX1 SUB_UNS_OP_g201__1705(.AN (n_184), .B (n_257), .Y
       (SUB_UNS_OP_n_15));
  NOR2BX1 SUB_UNS_OP_g202__5122(.AN (n_170), .B (n_250), .Y
       (SUB_UNS_OP_n_14));
  NOR2BX1 SUB_UNS_OP_g203__8246(.AN (n_180), .B (n_253), .Y
       (SUB_UNS_OP_n_13));
  OR2XL SUB_UNS_OP_g204__7098(.A (SUB_UNS_OP_n_5), .B (n_252), .Y
       (SUB_UNS_OP_n_12));
  OR2XL SUB_UNS_OP_g205__6131(.A (SUB_UNS_OP_n_8), .B (n_258), .Y
       (SUB_UNS_OP_n_11));
  OR2XL SUB_UNS_OP_g206__1881(.A (SUB_UNS_OP_n_7), .B (n_256), .Y
       (SUB_UNS_OP_n_10));
  NOR2BX1 SUB_UNS_OP_g207__5115(.AN (n_182), .B (n_255), .Y
       (SUB_UNS_OP_n_9));
  INVX1 SUB_UNS_OP_g208(.A (n_185), .Y (SUB_UNS_OP_n_8));
  INVX1 SUB_UNS_OP_g209(.A (n_183), .Y (SUB_UNS_OP_n_7));
  INVX1 SUB_UNS_OP_g210(.A (n_369), .Y (SUB_UNS_OP_n_6));
  INVX1 SUB_UNS_OP_g211(.A (n_179), .Y (SUB_UNS_OP_n_5));
  INVX1 SUB_UNS_OP_g212(.A (n_257), .Y (SUB_UNS_OP_n_4));
  INVX1 SUB_UNS_OP_g213(.A (n_255), .Y (SUB_UNS_OP_n_3));
  INVX1 SUB_UNS_OP_g214(.A (n_181), .Y (SUB_UNS_OP_n_2));
  INVX1 SUB_UNS_OP_g215(.A (n_253), .Y (SUB_UNS_OP_n_1));
  INVX1 csa_tree_SUB_TC_OP33_g11(.A (n_272), .Y (n_1005));
  INVX1 csa_tree_SUB_TC_OP33_g13(.A (n_187), .Y (n_1003));
  INVX1 csa_tree_SUB_TC_OP33_g14(.A (n_188), .Y (n_1002));
  INVX1 csa_tree_SUB_TC_OP33_g15(.A (n_189), .Y (n_1001));
  INVX1 csa_tree_SUB_TC_OP33_g16(.A (n_190), .Y (n_1000));
  INVX1 csa_tree_SUB_TC_OP33_g17(.A (n_191), .Y (n_999));
  INVX1 csa_tree_SUB_TC_OP33_g18(.A (n_192), .Y (n_998));
  INVX1 csa_tree_SUB_TC_OP33_g19(.A (n_193), .Y (n_997));
  INVX1 csa_tree_SUB_TC_OP33_g20(.A (n_194), .Y (n_996));
  INVX1 csa_tree_SUB_TC_OP_2_g10(.A (n_272), .Y (n_949));
  INVX1 csa_tree_SUB_TC_OP_2_g11(.A (n_186), .Y (n_948));
  INVX1 csa_tree_SUB_TC_OP_2_g12(.A (n_187), .Y (n_947));
  INVX1 csa_tree_SUB_TC_OP_2_g13(.A (n_188), .Y (n_946));
  INVX1 csa_tree_SUB_TC_OP_2_g14(.A (n_189), .Y (n_945));
  INVX1 csa_tree_SUB_TC_OP_2_g15(.A (n_190), .Y (n_944));
  INVX1 csa_tree_SUB_TC_OP_2_g16(.A (n_191), .Y (n_943));
  INVX1 csa_tree_SUB_TC_OP_2_g17(.A (n_192), .Y (n_942));
  INVX1 csa_tree_SUB_TC_OP_2_g18(.A (n_193), .Y (n_941));
  INVX1 csa_tree_SUB_TC_OP_3_g9(.A (n_272), .Y (n_907));
  INVX1 csa_tree_SUB_TC_OP_3_g10(.A (n_186), .Y (n_906));
  INVX1 csa_tree_SUB_TC_OP_3_g11(.A (n_187), .Y (n_905));
  INVX1 csa_tree_SUB_TC_OP_3_g12(.A (n_188), .Y (n_904));
  INVX1 csa_tree_SUB_TC_OP_3_g13(.A (n_189), .Y (n_903));
  INVX1 csa_tree_SUB_TC_OP_3_g14(.A (n_190), .Y (n_902));
  INVX1 csa_tree_SUB_TC_OP_3_g15(.A (n_191), .Y (n_901));
  INVX1 csa_tree_SUB_TC_OP_3_g16(.A (n_192), .Y (n_900));
  CLKBUFX2 g2271(.A (n_1005), .Y (n_137));
  INVXL g2272(.A (n_137), .Y (n_250));
  INVXL g2275(.A (n_371), .Y (n_252));
  INVXL g2276(.A (n_376), .Y (n_154));
  INVXL g2277(.A (n_380), .Y (n_153));
  INVXL g2278(.A (n_372), .Y (n_254));
  INVXL g2280(.A (n_373), .Y (n_255));
  CLKBUFX2 g2281(.A (n_290), .Y (n_256));
  OAI21X1 g2(.A0 (n_186), .A1 (ADD_TC_OP_n_2), .B0 (n_368), .Y (n_369));
  NAND2BX1 g3(.AN (ADD_TC_OP85_n_2), .B (n_949), .Y (n_368));
  INVX1 csa_tree_SUB_TC_OP33_g2282(.A (n_186), .Y (n_370));
  NOR2XL g2283(.A (n_377), .B (n_381), .Y (n_371));
  NOR2XL g2284(.A (n_375), .B (n_379), .Y (n_372));
  NOR2XL g2285(.A (n_374), .B (n_378), .Y (n_373));
  NOR2BX1 g2286(.AN (n_1000), .B (ADD_TC_OP_n_10), .Y (n_374));
  NOR2BX1 g2287(.AN (n_1001), .B (ADD_TC_OP_n_8), .Y (n_375));
  NOR2BX1 g2288(.AN (n_1002), .B (ADD_TC_OP_n_6), .Y (n_376));
  NOR2BX1 g2289(.AN (n_1003), .B (ADD_TC_OP_n_4), .Y (n_377));
  NOR2BX1 g2290(.AN (ADD_TC_OP85_n_8), .B (ADD_TC_OP85_n_10), .Y
       (n_378));
  NOR2BX1 g2291(.AN (ADD_TC_OP85_n_6), .B (ADD_TC_OP85_n_8), .Y
       (n_379));
  NOR2BX1 g2292(.AN (ADD_TC_OP86_n_4), .B (ADD_TC_OP86_n_6), .Y
       (n_380));
  AND2XL g2293(.A (SUB_TC_OP_1_n_6), .B (SUB_TC_OP_1_n_8), .Y (n_381));
endmodule

