
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jul  5 2024 11:38:26 IST (Jul  5 2024 06:08:26 UTC)

// Verification Directory fv/sdrc_bank_fsm 

module sdrc_bank_fsm(clk, reset_n, r2b_req, r2b_req_id, r2b_start,
     r2b_last, r2b_wrap, r2b_raddr, r2b_caddr, r2b_len, r2b_write,
     b2r_ack, sdr_dma_last, b2x_req, b2x_start, b2x_last, b2x_wrap,
     b2x_id, b2x_addr, b2x_len, b2x_cmd, x2b_ack, tras_ok, xfr_ok,
     x2b_refresh, x2b_pre_ok, x2b_act_ok, x2b_rdok, x2b_wrok, bank_row,
     tras_delay, trp_delay, trcd_delay);
  input clk, reset_n, r2b_req, r2b_start, r2b_last, r2b_wrap,
       r2b_write, sdr_dma_last, x2b_ack, xfr_ok, x2b_refresh,
       x2b_pre_ok, x2b_act_ok, x2b_rdok, x2b_wrok;
  input [3:0] r2b_req_id, tras_delay, trp_delay, trcd_delay;
  input [12:0] r2b_raddr, r2b_caddr;
  input [6:0] r2b_len;
  output b2r_ack, b2x_req, b2x_start, b2x_last, b2x_wrap, tras_ok;
  output [3:0] b2x_id;
  output [12:0] b2x_addr, bank_row;
  output [6:0] b2x_len;
  output [1:0] b2x_cmd;
  wire clk, reset_n, r2b_req, r2b_start, r2b_last, r2b_wrap, r2b_write,
       sdr_dma_last, x2b_ack, xfr_ok, x2b_refresh, x2b_pre_ok,
       x2b_act_ok, x2b_rdok, x2b_wrok;
  wire [3:0] r2b_req_id, tras_delay, trp_delay, trcd_delay;
  wire [12:0] r2b_raddr, r2b_caddr;
  wire [6:0] r2b_len;
  wire b2r_ack, b2x_req, b2x_start, b2x_last, b2x_wrap, tras_ok;
  wire [3:0] b2x_id;
  wire [12:0] b2x_addr, bank_row;
  wire [6:0] b2x_len;
  wire [1:0] b2x_cmd;
  wire [12:0] l_raddr;
  wire [1:0] x2b_pre_ok_r;
  wire [1:0] x2b_act_ok_r;
  wire [1:0] timer0_tc_r;
  wire [6:0] l_len;
  wire [3:0] l_id;
  wire [12:0] l_caddr;
  wire [2:0] bank_st;
  wire [3:0] timer0;
  wire [3:0] tras_cntr;
  wire [1:0] tras_ok_r;
  wire bank_valid, dec_SUB_UNS_OP_n_0, dec_SUB_UNS_OP_n_1,
       dec_SUB_UNS_OP_n_3, dec_SUB_UNS_OP_n_5, dec_sub_210_41_n_0,
       dec_sub_210_41_n_2, l_last;
  wire l_sdr_dma_last, l_start, l_wrap, l_write, n_1, n_2, n_3, n_4;
  wire n_5, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_216, n_217, n_218, n_220, n_299, n_300, n_301;
  wire timer0_tc_t, x2b_rdok_r, x2b_wrok_r, xfr_ok_r;
  INVX1 g1762(.A (timer0_tc_t), .Y (n_192));
  INVX1 g1761(.A (n_193), .Y (b2r_ack));
  INVX1 g1763(.A (r2b_req), .Y (n_190));
  INVX2 g1764(.A (reset_n), .Y (n_189));
  OAI21XL g2070__2398(.A0 (n_220), .A1 (n_173), .B0 (n_188), .Y
       (b2x_req));
  OAI2BB1X1 g2071__5107(.A0N (l_raddr[11]), .A1N (n_216), .B0 (n_184),
       .Y (b2x_addr[11]));
  OAI2BB1X1 g2072__6260(.A0N (l_raddr[1]), .A1N (n_216), .B0 (n_183),
       .Y (b2x_addr[1]));
  OAI2BB1X1 g2073__4319(.A0N (l_raddr[0]), .A1N (n_216), .B0 (n_186),
       .Y (b2x_addr[0]));
  OAI2BB1X1 g2074__8428(.A0N (l_raddr[9]), .A1N (n_216), .B0 (n_182),
       .Y (b2x_addr[9]));
  OAI2BB1X1 g2075__5526(.A0N (l_raddr[8]), .A1N (n_216), .B0 (n_181),
       .Y (b2x_addr[8]));
  OAI2BB1X1 g2076__6783(.A0N (l_raddr[7]), .A1N (n_216), .B0 (n_175),
       .Y (b2x_addr[7]));
  OAI2BB1X1 g2077__3680(.A0N (l_raddr[6]), .A1N (n_216), .B0 (n_178),
       .Y (b2x_addr[6]));
  OAI2BB1X1 g2078__1617(.A0N (l_raddr[5]), .A1N (n_216), .B0 (n_177),
       .Y (b2x_addr[5]));
  OAI2BB1X1 g2079__2802(.A0N (l_raddr[4]), .A1N (n_216), .B0 (n_176),
       .Y (b2x_addr[4]));
  OAI2BB1X1 g2080__1705(.A0N (l_raddr[3]), .A1N (n_216), .B0 (n_179),
       .Y (b2x_addr[3]));
  OAI2BB1X1 g2081__5122(.A0N (l_raddr[2]), .A1N (n_216), .B0 (n_174),
       .Y (b2x_addr[2]));
  AOI33XL g2082__8246(.A0 (tras_ok), .A1 (x2b_pre_ok_r[0]), .A2
       (n_180), .B0 (x2b_act_ok_r[0]), .B1 (timer0_tc_r[0]), .B2
       (n_171), .Y (n_188));
  MX2XL g2083__7098(.A (r2b_len[6]), .B (l_len[6]), .S0 (n_202), .Y
       (b2x_len[6]));
  OAI2BB1X1 g2084__6131(.A0N (l_raddr[12]), .A1N (n_171), .B0 (n_185),
       .Y (b2x_addr[12]));
  OAI2BB1X1 g2085__1881(.A0N (l_raddr[10]), .A1N (n_171), .B0 (n_187),
       .Y (b2x_addr[10]));
  MX2XL g2086__5115(.A (r2b_req_id[0]), .B (l_id[0]), .S0 (n_202), .Y
       (b2x_id[0]));
  MX2XL g2087__7482(.A (r2b_start), .B (l_start), .S0 (n_202), .Y
       (b2x_start));
  MX2XL g2088__4733(.A (r2b_len[5]), .B (l_len[5]), .S0 (n_202), .Y
       (b2x_len[5]));
  MX2XL g2089__6161(.A (r2b_len[4]), .B (l_len[4]), .S0 (n_202), .Y
       (b2x_len[4]));
  OR2X1 g2090__9315(.A (n_171), .B (n_180), .Y (n_216));
  MX2XL g2091__9945(.A (r2b_req_id[1]), .B (l_id[1]), .S0 (n_202), .Y
       (b2x_id[1]));
  MX2XL g2092__2883(.A (r2b_len[2]), .B (l_len[2]), .S0 (n_202), .Y
       (b2x_len[2]));
  MX2XL g2093__2346(.A (r2b_len[1]), .B (l_len[1]), .S0 (n_202), .Y
       (b2x_len[1]));
  MX2XL g2094__1666(.A (r2b_last), .B (l_last), .S0 (n_202), .Y
       (b2x_last));
  MX2XL g2095__7410(.A (r2b_len[0]), .B (l_len[0]), .S0 (n_202), .Y
       (b2x_len[0]));
  MX2XL g2096__6417(.A (r2b_wrap), .B (l_wrap), .S0 (n_202), .Y
       (b2x_wrap));
  MX2XL g2097__5477(.A (r2b_req_id[3]), .B (l_id[3]), .S0 (n_202), .Y
       (b2x_id[3]));
  MX2XL g2098__2398(.A (r2b_req_id[2]), .B (l_id[2]), .S0 (n_202), .Y
       (b2x_id[2]));
  MX2XL g2099__5107(.A (r2b_len[3]), .B (l_len[3]), .S0 (n_202), .Y
       (b2x_len[3]));
  NAND2X1 g2100__6260(.A (l_caddr[10]), .B (n_172), .Y (n_187));
  NAND2X1 g2101__4319(.A (l_caddr[0]), .B (n_172), .Y (n_186));
  NAND2X1 g2102__8428(.A (l_caddr[12]), .B (n_172), .Y (n_185));
  NAND2X1 g2103__5526(.A (l_caddr[11]), .B (n_172), .Y (n_184));
  NAND2X1 g2104__6783(.A (l_caddr[1]), .B (n_172), .Y (n_183));
  NAND2X1 g2105__3680(.A (l_caddr[9]), .B (n_172), .Y (n_182));
  OR2X2 g2106__1617(.A (n_190), .B (n_202), .Y (n_193));
  NAND2X1 g2107__2802(.A (l_caddr[8]), .B (n_172), .Y (n_181));
  NAND2X1 g2108__1705(.A (l_caddr[3]), .B (n_172), .Y (n_179));
  NAND2X1 g2109__5122(.A (l_caddr[6]), .B (n_172), .Y (n_178));
  NAND2X1 g2110__8246(.A (l_caddr[5]), .B (n_172), .Y (n_177));
  NAND2X1 g2111__7098(.A (l_caddr[4]), .B (n_172), .Y (n_176));
  NAND2X1 g2112__6131(.A (l_caddr[7]), .B (n_172), .Y (n_175));
  NAND2X1 g2113__1881(.A (l_caddr[2]), .B (n_172), .Y (n_174));
  AOI33XL g2114__5115(.A0 (n_169), .A1 (x2b_rdok_r), .A2 (xfr_ok_r),
       .B0 (n_167), .B1 (l_write), .B2 (xfr_ok_r), .Y (n_173));
  NAND2XL g2115__7482(.A (n_217), .B (n_218), .Y (n_180));
  INVX1 g2116(.A (n_220), .Y (n_172));
  NAND2X1 g2117__4733(.A (bank_st[0]), .B (n_170), .Y (n_218));
  OR2X1 g2118__6161(.A (bank_st[2]), .B (n_168), .Y (n_220));
  INVX1 g2120(.A (n_194), .Y (n_171));
  NOR4X1 g2121__9315(.A (timer0[2]), .B (timer0[1]), .C (timer0[3]), .D
       (timer0[0]), .Y (timer0_tc_t));
  NAND3BXL g2122__9945(.AN (bank_st[1]), .B (bank_st[2]), .C (n_165),
       .Y (n_217));
  OR3X1 g2123__2883(.A (bank_st[2]), .B (n_166), .C (bank_st[0]), .Y
       (n_194));
  NOR2BX1 g2125__2346(.AN (timer0_tc_r[0]), .B (l_write), .Y (n_169));
  NOR2X1 g2126__1666(.A (bank_st[1]), .B (bank_st[2]), .Y (n_170));
  NAND2X1 g2127__7410(.A (bank_st[0]), .B (bank_st[1]), .Y (n_168));
  AND2XL g2128__6417(.A (timer0_tc_r[0]), .B (x2b_wrok_r), .Y (n_167));
  INVX1 g2129(.A (bank_st[1]), .Y (n_166));
  INVX1 g2130(.A (bank_st[0]), .Y (n_165));
  NAND2BX2 g2__5477(.AN (bank_st[0]), .B (n_170), .Y (n_202));
  DFFHQX1 \b2x_cmd_r_reg[0] (.CK (clk), .D (n_164), .Q (b2x_cmd[0]));
  DFFHQX1 \b2x_cmd_r_reg[1] (.CK (clk), .D (n_160), .Q (b2x_cmd[1]));
  SDFFQX1 \bank_row_reg[0] (.CK (clk), .D (b2x_addr[0]), .SI
       (bank_row[0]), .SE (n_194), .Q (bank_row[0]));
  SDFFQX1 \bank_row_reg[1] (.CK (clk), .D (b2x_addr[1]), .SI
       (bank_row[1]), .SE (n_194), .Q (bank_row[1]));
  SDFFQX1 \bank_row_reg[2] (.CK (clk), .D (b2x_addr[2]), .SI
       (bank_row[2]), .SE (n_194), .Q (bank_row[2]));
  SDFFQX1 \bank_row_reg[3] (.CK (clk), .D (b2x_addr[3]), .SI
       (bank_row[3]), .SE (n_194), .Q (bank_row[3]));
  SDFFQX1 \bank_row_reg[4] (.CK (clk), .D (b2x_addr[4]), .SI
       (bank_row[4]), .SE (n_194), .Q (bank_row[4]));
  SDFFQX1 \bank_row_reg[5] (.CK (clk), .D (b2x_addr[5]), .SI
       (bank_row[5]), .SE (n_194), .Q (bank_row[5]));
  SDFFQX1 \bank_row_reg[6] (.CK (clk), .D (b2x_addr[6]), .SI
       (bank_row[6]), .SE (n_194), .Q (bank_row[6]));
  SDFFQX1 \bank_row_reg[7] (.CK (clk), .D (b2x_addr[7]), .SI
       (bank_row[7]), .SE (n_194), .Q (bank_row[7]));
  SDFFQX1 \bank_row_reg[8] (.CK (clk), .D (b2x_addr[8]), .SI
       (bank_row[8]), .SE (n_194), .Q (bank_row[8]));
  SDFFQX1 \bank_row_reg[9] (.CK (clk), .D (b2x_addr[9]), .SI
       (bank_row[9]), .SE (n_194), .Q (bank_row[9]));
  SDFFQX1 \bank_row_reg[10] (.CK (clk), .D (b2x_addr[10]), .SI
       (bank_row[10]), .SE (n_194), .Q (bank_row[10]));
  SDFFQX1 \bank_row_reg[11] (.CK (clk), .D (b2x_addr[11]), .SI
       (bank_row[11]), .SE (n_194), .Q (bank_row[11]));
  SDFFQX1 \bank_row_reg[12] (.CK (clk), .D (b2x_addr[12]), .SI
       (bank_row[12]), .SE (n_194), .Q (bank_row[12]));
  DFFHQX1 \bank_st_reg[0] (.CK (clk), .D (n_151), .Q (bank_st[0]));
  DFFHQX1 \bank_st_reg[1] (.CK (clk), .D (n_163), .Q (bank_st[1]));
  DFFHQX1 \bank_st_reg[2] (.CK (clk), .D (n_152), .Q (bank_st[2]));
  DFFHQX1 bank_valid_reg(.CK (clk), .D (n_155), .Q (bank_valid));
  DFFHQX1 \l_caddr_reg[0] (.CK (clk), .D (n_116), .Q (l_caddr[0]));
  DFFHQX1 \l_caddr_reg[1] (.CK (clk), .D (n_115), .Q (l_caddr[1]));
  DFFHQX1 \l_caddr_reg[2] (.CK (clk), .D (n_114), .Q (l_caddr[2]));
  DFFHQX1 \l_caddr_reg[3] (.CK (clk), .D (n_113), .Q (l_caddr[3]));
  DFFHQX1 \l_caddr_reg[4] (.CK (clk), .D (n_112), .Q (l_caddr[4]));
  DFFHQX1 \l_caddr_reg[5] (.CK (clk), .D (n_111), .Q (l_caddr[5]));
  DFFHQX1 \l_caddr_reg[6] (.CK (clk), .D (n_125), .Q (l_caddr[6]));
  DFFHQX1 \l_caddr_reg[7] (.CK (clk), .D (n_110), .Q (l_caddr[7]));
  DFFHQX1 \l_caddr_reg[8] (.CK (clk), .D (n_108), .Q (l_caddr[8]));
  DFFHQX1 \l_caddr_reg[9] (.CK (clk), .D (n_107), .Q (l_caddr[9]));
  DFFHQX1 \l_caddr_reg[10] (.CK (clk), .D (n_106), .Q (l_caddr[10]));
  DFFHQX1 \l_caddr_reg[11] (.CK (clk), .D (n_105), .Q (l_caddr[11]));
  DFFHQX1 \l_caddr_reg[12] (.CK (clk), .D (n_104), .Q (l_caddr[12]));
  DFFHQX1 \l_id_reg[0] (.CK (clk), .D (n_103), .Q (l_id[0]));
  DFFHQX1 \l_id_reg[1] (.CK (clk), .D (n_102), .Q (l_id[1]));
  DFFHQX1 \l_id_reg[2] (.CK (clk), .D (n_101), .Q (l_id[2]));
  DFFHQX1 \l_id_reg[3] (.CK (clk), .D (n_100), .Q (l_id[3]));
  DFFHQX1 l_last_reg(.CK (clk), .D (n_99), .Q (l_last));
  DFFHQX1 \l_len_reg[0] (.CK (clk), .D (n_98), .Q (l_len[0]));
  DFFHQX1 \l_len_reg[1] (.CK (clk), .D (n_97), .Q (l_len[1]));
  DFFHQX1 \l_len_reg[2] (.CK (clk), .D (n_96), .Q (l_len[2]));
  DFFHQX1 \l_len_reg[3] (.CK (clk), .D (n_95), .Q (l_len[3]));
  DFFHQX1 \l_len_reg[4] (.CK (clk), .D (n_94), .Q (l_len[4]));
  DFFHQX1 \l_len_reg[5] (.CK (clk), .D (n_93), .Q (l_len[5]));
  DFFHQX1 \l_len_reg[6] (.CK (clk), .D (n_92), .Q (l_len[6]));
  DFFHQX1 \l_raddr_reg[0] (.CK (clk), .D (n_91), .Q (l_raddr[0]));
  DFFHQX1 \l_raddr_reg[1] (.CK (clk), .D (n_90), .Q (l_raddr[1]));
  DFFHQX1 \l_raddr_reg[2] (.CK (clk), .D (n_89), .Q (l_raddr[2]));
  DFFHQX1 \l_raddr_reg[3] (.CK (clk), .D (n_88), .Q (l_raddr[3]));
  DFFHQX1 \l_raddr_reg[4] (.CK (clk), .D (n_87), .Q (l_raddr[4]));
  DFFHQX1 \l_raddr_reg[5] (.CK (clk), .D (n_86), .Q (l_raddr[5]));
  DFFHQX1 \l_raddr_reg[6] (.CK (clk), .D (n_85), .Q (l_raddr[6]));
  DFFHQX1 \l_raddr_reg[7] (.CK (clk), .D (n_84), .Q (l_raddr[7]));
  DFFHQX1 \l_raddr_reg[8] (.CK (clk), .D (n_83), .Q (l_raddr[8]));
  DFFHQX1 \l_raddr_reg[9] (.CK (clk), .D (n_82), .Q (l_raddr[9]));
  DFFHQX1 \l_raddr_reg[10] (.CK (clk), .D (n_81), .Q (l_raddr[10]));
  DFFHQX1 \l_raddr_reg[11] (.CK (clk), .D (n_122), .Q (l_raddr[11]));
  DFFHQX1 \l_raddr_reg[12] (.CK (clk), .D (n_121), .Q (l_raddr[12]));
  DFFHQX1 l_sdr_dma_last_reg(.CK (clk), .D (n_120), .Q
       (l_sdr_dma_last));
  DFFHQX1 l_start_reg(.CK (clk), .D (n_119), .Q (l_start));
  DFFHQX1 l_wrap_reg(.CK (clk), .D (n_118), .Q (l_wrap));
  DFFHQX1 l_write_reg(.CK (clk), .D (n_117), .Q (l_write));
  DFFHQX1 \timer0_reg[0] (.CK (clk), .D (n_153), .Q (timer0[0]));
  DFFHQX1 \timer0_reg[1] (.CK (clk), .D (n_150), .Q (timer0[1]));
  DFFHQX1 \timer0_reg[2] (.CK (clk), .D (n_149), .Q (timer0[2]));
  DFFHQX1 \timer0_reg[3] (.CK (clk), .D (n_147), .Q (timer0[3]));
  DFFHQX1 \timer0_tc_r_reg[0] (.CK (clk), .D (n_124), .Q
       (timer0_tc_r[0]));
  DFFHQX1 \timer0_tc_r_reg[1] (.CK (clk), .D (1'b0), .Q
       (timer0_tc_r[1]));
  DFFHQX1 \tras_cntr_reg[0] (.CK (clk), .D (n_146), .Q (tras_cntr[0]));
  DFFHQX1 \tras_cntr_reg[1] (.CK (clk), .D (n_145), .Q (tras_cntr[1]));
  DFFHQX1 \tras_cntr_reg[2] (.CK (clk), .D (n_144), .Q (tras_cntr[2]));
  DFFHQX1 \tras_cntr_reg[3] (.CK (clk), .D (n_143), .Q (tras_cntr[3]));
  DFFHQX1 \tras_ok_r_reg[0] (.CK (clk), .D (n_123), .Q (tras_ok));
  DFFHQX1 \tras_ok_r_reg[1] (.CK (clk), .D (1'b0), .Q (tras_ok_r[1]));
  DFFHQX1 \x2b_act_ok_r_reg[0] (.CK (clk), .D (n_10), .Q
       (x2b_act_ok_r[0]));
  DFFHQX1 \x2b_act_ok_r_reg[1] (.CK (clk), .D (1'b0), .Q
       (x2b_act_ok_r[1]));
  DFFHQX1 \x2b_pre_ok_r_reg[0] (.CK (clk), .D (n_11), .Q
       (x2b_pre_ok_r[0]));
  DFFHQX1 \x2b_pre_ok_r_reg[1] (.CK (clk), .D (1'b0), .Q
       (x2b_pre_ok_r[1]));
  DFFHQX1 x2b_rdok_r_reg(.CK (clk), .D (n_9), .Q (x2b_rdok_r));
  DFFHQX1 x2b_wrok_r_reg(.CK (clk), .D (n_8), .Q (x2b_wrok_r));
  DFFHQX1 xfr_ok_r_reg(.CK (clk), .D (n_15), .Q (xfr_ok_r));
  AOI21X1 g2293__2398(.A0 (n_301), .A1 (n_162), .B0 (n_189), .Y
       (n_164));
  NOR2BX1 g2295__5107(.AN (n_161), .B (n_189), .Y (n_163));
  OAI221X1 g2296__6260(.A0 (r2b_write), .A1 (n_12), .B0 (l_write), .B1
       (n_158), .C0 (n_159), .Y (n_162));
  OAI211X1 g2298__4319(.A0 (x2b_ack), .A1 (n_220), .B0 (n_194), .C0
       (n_157), .Y (n_161));
  NOR2BX1 g2299__8428(.AN (n_159), .B (n_189), .Y (n_160));
  NAND2BX1 g2300__5526(.AN (n_12), .B (n_299), .Y (n_159));
  AOI221X1 g2302__6783(.A0 (n_4), .A1 (n_148), .B0 (bank_st[1]), .B1
       (n_77), .C0 (n_59), .Y (n_157));
  INVX1 g2310(.A (n_154), .Y (n_155));
  AOI33XL g2311__1617(.A0 (n_1), .A1 (n_13), .A2 (n_128), .B0
       (bank_valid), .B1 (n_13), .B2 (n_109), .Y (n_154));
  OAI2BB1X1 g2317__2802(.A0N (trp_delay[0]), .A1N (n_127), .B0 (n_142),
       .Y (n_153));
  NOR2X1 g2318__1705(.A (n_189), .B (n_138), .Y (n_152));
  AOI31X1 g2319__5122(.A0 (n_130), .A1 (n_193), .A2 (n_80), .B0
       (n_189), .Y (n_151));
  OAI2BB1X1 g2320__8246(.A0N (trcd_delay[1]), .A1N (n_126), .B0
       (n_141), .Y (n_150));
  OAI2BB1X1 g2321__7098(.A0N (trp_delay[2]), .A1N (n_127), .B0 (n_140),
       .Y (n_149));
  OAI2BB1X1 g2322__6131(.A0N (trp_delay[3]), .A1N (n_127), .B0 (n_139),
       .Y (n_147));
  OAI21X1 g2323__1881(.A0 (tras_cntr[0]), .A1 (n_137), .B0 (n_129), .Y
       (n_146));
  AO22XL g2324__5115(.A0 (n_195), .A1 (n_136), .B0 (tras_delay[1]), .B1
       (n_126), .Y (n_145));
  AO22XL g2325__7482(.A0 (n_196), .A1 (n_136), .B0 (tras_delay[2]), .B1
       (n_126), .Y (n_144));
  AO22XL g2326__4733(.A0 (n_197), .A1 (n_136), .B0 (tras_delay[3]), .B1
       (n_126), .Y (n_143));
  NOR4X1 g2327__6161(.A (n_133), .B (n_132), .C (n_135), .D (n_134), .Y
       (n_148));
  AOI22X1 g2328__9315(.A0 (trcd_delay[0]), .A1 (n_126), .B0 (n_198),
       .B1 (n_75), .Y (n_142));
  AOI22X1 g2329__9945(.A0 (trp_delay[1]), .A1 (n_127), .B0 (n_199), .B1
       (n_75), .Y (n_141));
  AOI22X1 g2330__2883(.A0 (trcd_delay[2]), .A1 (n_126), .B0 (n_200),
       .B1 (n_75), .Y (n_140));
  AOI22X1 g2331__2346(.A0 (trcd_delay[3]), .A1 (n_126), .B0 (n_201),
       .B1 (n_75), .Y (n_139));
  AOI31X1 g2332__1666(.A0 (x2b_ack), .A1 (l_sdr_dma_last), .A2 (n_16),
       .B0 (n_300), .Y (n_138));
  INVX1 g2359(.A (n_136), .Y (n_137));
  NAND4XL g2360__7410(.A (n_66), .B (n_65), .C (n_64), .D (n_63), .Y
       (n_135));
  NAND4XL g2361__6417(.A (n_62), .B (n_73), .C (n_61), .D (n_60), .Y
       (n_134));
  NAND3X1 g2362__5477(.A (n_17), .B (bank_valid), .C (n_69), .Y
       (n_133));
  NAND3X1 g2363__2398(.A (n_18), .B (n_67), .C (n_68), .Y (n_132));
  AOI22X1 g2365__6260(.A0 (bank_st[0]), .A1 (n_77), .B0 (x2b_ack), .B1
       (n_5), .Y (n_130));
  NAND2X1 g2366__4319(.A (tras_delay[0]), .B (n_126), .Y (n_129));
  NOR2BX1 g2386__8428(.AN (n_109), .B (n_49), .Y (n_136));
  NOR2X1 g2387__5526(.A (n_189), .B (n_32), .Y (n_125));
  AND2XL g2388__6783(.A (timer0_tc_t), .B (n_75), .Y (n_124));
  NOR2BX1 g2389__3680(.AN (n_49), .B (n_189), .Y (n_123));
  NOR2X1 g2390__1617(.A (n_189), .B (n_58), .Y (n_122));
  NOR2X1 g2391__2802(.A (n_189), .B (n_57), .Y (n_121));
  NOR2X1 g2392__1705(.A (n_189), .B (n_56), .Y (n_120));
  NOR2X1 g2393__5122(.A (n_189), .B (n_55), .Y (n_119));
  NOR2X1 g2394__8246(.A (n_189), .B (n_54), .Y (n_118));
  NOR2X1 g2395__7098(.A (n_189), .B (n_53), .Y (n_117));
  NOR2X1 g2396__6131(.A (n_189), .B (n_52), .Y (n_116));
  NOR2X1 g2397__1881(.A (n_189), .B (n_51), .Y (n_115));
  NOR2X1 g2398__5115(.A (n_189), .B (n_50), .Y (n_114));
  NOR2X1 g2399__7482(.A (n_189), .B (n_70), .Y (n_113));
  NOR2X1 g2400__4733(.A (n_189), .B (n_71), .Y (n_112));
  NOR2X1 g2401__6161(.A (n_189), .B (n_72), .Y (n_111));
  NOR2X1 g2402__9315(.A (n_189), .B (n_47), .Y (n_110));
  NOR2X1 g2414__9945(.A (b2x_cmd[0]), .B (n_78), .Y (n_127));
  NOR2BX1 g2417__2883(.AN (b2x_cmd[0]), .B (n_78), .Y (n_126));
  NOR2X1 g2418__2346(.A (n_189), .B (n_46), .Y (n_108));
  NOR2X1 g2419__1666(.A (n_189), .B (n_45), .Y (n_107));
  NOR2X1 g2420__7410(.A (n_189), .B (n_44), .Y (n_106));
  NOR2X1 g2421__6417(.A (n_189), .B (n_43), .Y (n_105));
  NOR2X1 g2422__5477(.A (n_189), .B (n_42), .Y (n_104));
  NOR2X1 g2423__2398(.A (n_189), .B (n_41), .Y (n_103));
  NOR2X1 g2424__5107(.A (n_189), .B (n_40), .Y (n_102));
  NOR2X1 g2425__6260(.A (n_189), .B (n_39), .Y (n_101));
  NOR2X1 g2426__4319(.A (n_189), .B (n_38), .Y (n_100));
  NOR2X1 g2427__8428(.A (n_189), .B (n_37), .Y (n_99));
  NOR2X1 g2428__5526(.A (n_189), .B (n_36), .Y (n_98));
  NOR2X1 g2429__6783(.A (n_189), .B (n_35), .Y (n_97));
  NOR2X1 g2430__3680(.A (n_189), .B (n_34), .Y (n_96));
  NOR2X1 g2431__1617(.A (n_189), .B (n_33), .Y (n_95));
  NOR2X1 g2432__2802(.A (n_189), .B (n_48), .Y (n_94));
  NOR2X1 g2433__1705(.A (n_189), .B (n_31), .Y (n_93));
  NOR2X1 g2434__5122(.A (n_189), .B (n_30), .Y (n_92));
  NOR2X1 g2435__8246(.A (n_189), .B (n_29), .Y (n_91));
  NOR2X1 g2436__7098(.A (n_189), .B (n_28), .Y (n_90));
  NOR2X1 g2437__6131(.A (n_189), .B (n_27), .Y (n_89));
  NOR2X1 g2438__1881(.A (n_189), .B (n_26), .Y (n_88));
  NOR2X1 g2439__5115(.A (n_189), .B (n_25), .Y (n_87));
  NOR2X1 g2440__7482(.A (n_189), .B (n_24), .Y (n_86));
  NOR2X1 g2441__4733(.A (n_189), .B (n_23), .Y (n_85));
  NOR2X1 g2442__6161(.A (n_189), .B (n_22), .Y (n_84));
  NOR2X1 g2443__9315(.A (n_189), .B (n_21), .Y (n_83));
  NOR2X1 g2444__9945(.A (n_189), .B (n_20), .Y (n_82));
  NOR2X1 g2445__2883(.A (n_189), .B (n_19), .Y (n_81));
  OAI21X1 g2446__2346(.A0 (n_7), .A1 (n_16), .B0 (n_2), .Y (n_80));
  OAI21X1 g2448__7410(.A0 (n_189), .A1 (b2x_cmd[0]), .B0 (n_74), .Y
       (n_109));
  INVX1 g2449(.A (n_76), .Y (n_77));
  INVX1 g2450(.A (n_75), .Y (n_74));
  XNOR2X1 g2451__6417(.A (bank_row[1]), .B (r2b_raddr[1]), .Y (n_73));
  AOI22X1 g2456__5477(.A0 (r2b_caddr[5]), .A1 (n_4), .B0 (l_caddr[5]),
       .B1 (n_193), .Y (n_72));
  AOI22X1 g2457__2398(.A0 (r2b_caddr[4]), .A1 (n_4), .B0 (l_caddr[4]),
       .B1 (n_193), .Y (n_71));
  AOI22X1 g2458__5107(.A0 (r2b_caddr[3]), .A1 (n_4), .B0 (l_caddr[3]),
       .B1 (n_193), .Y (n_70));
  XNOR2X1 g2459__6260(.A (bank_row[11]), .B (r2b_raddr[11]), .Y (n_69));
  XNOR2X1 g2460__4319(.A (bank_row[8]), .B (r2b_raddr[8]), .Y (n_68));
  XNOR2X1 g2461__8428(.A (bank_row[9]), .B (r2b_raddr[9]), .Y (n_67));
  XNOR2X1 g2462__5526(.A (bank_row[6]), .B (r2b_raddr[6]), .Y (n_66));
  XNOR2X1 g2463__6783(.A (bank_row[5]), .B (r2b_raddr[5]), .Y (n_65));
  XNOR2X1 g2464__3680(.A (bank_row[4]), .B (r2b_raddr[4]), .Y (n_64));
  XNOR2X1 g2465__1617(.A (bank_row[3]), .B (r2b_raddr[3]), .Y (n_63));
  XNOR2X1 g2466__2802(.A (bank_row[2]), .B (r2b_raddr[2]), .Y (n_62));
  XNOR2X1 g2468__1705(.A (bank_row[12]), .B (r2b_raddr[12]), .Y (n_61));
  XNOR2X1 g2469__5122(.A (bank_row[0]), .B (r2b_raddr[0]), .Y (n_60));
  OAI22X1 g2470__8246(.A0 (n_2), .A1 (n_218), .B0 (n_3), .B1 (n_220),
       .Y (n_59));
  AOI22X1 g2471__7098(.A0 (r2b_raddr[11]), .A1 (n_4), .B0
       (l_raddr[11]), .B1 (n_193), .Y (n_58));
  AOI22X1 g2472__6131(.A0 (r2b_raddr[12]), .A1 (n_4), .B0
       (l_raddr[12]), .B1 (n_193), .Y (n_57));
  AOI22X1 g2473__1881(.A0 (sdr_dma_last), .A1 (n_4), .B0
       (l_sdr_dma_last), .B1 (n_193), .Y (n_56));
  AOI22X1 g2474__5115(.A0 (r2b_start), .A1 (n_4), .B0 (l_start), .B1
       (n_193), .Y (n_55));
  AOI22X1 g2475__7482(.A0 (r2b_wrap), .A1 (n_4), .B0 (l_wrap), .B1
       (n_193), .Y (n_54));
  AOI22X1 g2476__4733(.A0 (r2b_write), .A1 (n_4), .B0 (l_write), .B1
       (n_193), .Y (n_53));
  AOI22X1 g2477__6161(.A0 (r2b_caddr[0]), .A1 (n_4), .B0 (l_caddr[0]),
       .B1 (n_193), .Y (n_52));
  AOI22X1 g2478__9315(.A0 (r2b_caddr[1]), .A1 (n_4), .B0 (l_caddr[1]),
       .B1 (n_193), .Y (n_51));
  AOI22X1 g2479__9945(.A0 (r2b_caddr[2]), .A1 (n_4), .B0 (l_caddr[2]),
       .B1 (n_193), .Y (n_50));
  NAND2X1 g2480__2883(.A (n_1), .B (n_14), .Y (n_78));
  NAND3BXL g2481__2346(.AN (n_216), .B (n_202), .C (n_220), .Y (n_76));
  NOR2X1 g2482__1666(.A (n_189), .B (n_14), .Y (n_75));
  AOI22X1 g2483__7410(.A0 (r2b_len[4]), .A1 (n_4), .B0 (l_len[4]), .B1
       (n_193), .Y (n_48));
  AOI22X1 g2484__6417(.A0 (r2b_caddr[7]), .A1 (n_4), .B0 (l_caddr[7]),
       .B1 (n_193), .Y (n_47));
  AOI22X1 g2485__5477(.A0 (r2b_caddr[8]), .A1 (n_4), .B0 (l_caddr[8]),
       .B1 (n_193), .Y (n_46));
  AOI22X1 g2486__2398(.A0 (r2b_caddr[9]), .A1 (n_4), .B0 (l_caddr[9]),
       .B1 (n_193), .Y (n_45));
  AOI22X1 g2487__5107(.A0 (r2b_caddr[10]), .A1 (n_4), .B0
       (l_caddr[10]), .B1 (n_193), .Y (n_44));
  AOI22X1 g2488__6260(.A0 (r2b_caddr[11]), .A1 (n_4), .B0
       (l_caddr[11]), .B1 (n_193), .Y (n_43));
  AOI22X1 g2489__4319(.A0 (r2b_caddr[12]), .A1 (n_4), .B0
       (l_caddr[12]), .B1 (n_193), .Y (n_42));
  AOI22X1 g2490__8428(.A0 (r2b_req_id[0]), .A1 (n_4), .B0 (l_id[0]),
       .B1 (n_193), .Y (n_41));
  AOI22X1 g2491__5526(.A0 (r2b_req_id[1]), .A1 (n_4), .B0 (l_id[1]),
       .B1 (n_193), .Y (n_40));
  AOI22X1 g2492__6783(.A0 (r2b_req_id[2]), .A1 (n_4), .B0 (l_id[2]),
       .B1 (n_193), .Y (n_39));
  AOI22X1 g2493__3680(.A0 (r2b_req_id[3]), .A1 (n_4), .B0 (l_id[3]),
       .B1 (n_193), .Y (n_38));
  AOI22X1 g2494__1617(.A0 (r2b_last), .A1 (n_4), .B0 (l_last), .B1
       (n_193), .Y (n_37));
  AOI22X1 g2495__2802(.A0 (r2b_len[0]), .A1 (n_4), .B0 (l_len[0]), .B1
       (n_193), .Y (n_36));
  AOI22X1 g2496__1705(.A0 (r2b_len[1]), .A1 (n_4), .B0 (l_len[1]), .B1
       (n_193), .Y (n_35));
  AOI22X1 g2497__5122(.A0 (r2b_len[2]), .A1 (n_4), .B0 (l_len[2]), .B1
       (n_193), .Y (n_34));
  AOI22X1 g2498__8246(.A0 (r2b_len[3]), .A1 (n_4), .B0 (l_len[3]), .B1
       (n_193), .Y (n_33));
  AOI22X1 g2499__7098(.A0 (r2b_caddr[6]), .A1 (n_4), .B0 (l_caddr[6]),
       .B1 (n_193), .Y (n_32));
  AOI22X1 g2500__6131(.A0 (r2b_len[5]), .A1 (n_4), .B0 (l_len[5]), .B1
       (n_193), .Y (n_31));
  AOI22X1 g2501__1881(.A0 (r2b_len[6]), .A1 (n_4), .B0 (l_len[6]), .B1
       (n_193), .Y (n_30));
  AOI22X1 g2502__5115(.A0 (r2b_raddr[0]), .A1 (n_4), .B0 (l_raddr[0]),
       .B1 (n_193), .Y (n_29));
  AOI22X1 g2503__7482(.A0 (r2b_raddr[1]), .A1 (n_4), .B0 (l_raddr[1]),
       .B1 (n_193), .Y (n_28));
  AOI22X1 g2504__4733(.A0 (r2b_raddr[2]), .A1 (n_4), .B0 (l_raddr[2]),
       .B1 (n_193), .Y (n_27));
  AOI22X1 g2505__6161(.A0 (r2b_raddr[3]), .A1 (n_4), .B0 (l_raddr[3]),
       .B1 (n_193), .Y (n_26));
  AOI22X1 g2506__9315(.A0 (r2b_raddr[4]), .A1 (n_4), .B0 (l_raddr[4]),
       .B1 (n_193), .Y (n_25));
  AOI22X1 g2507__9945(.A0 (r2b_raddr[5]), .A1 (n_4), .B0 (l_raddr[5]),
       .B1 (n_193), .Y (n_24));
  AOI22X1 g2508__2883(.A0 (r2b_raddr[6]), .A1 (n_4), .B0 (l_raddr[6]),
       .B1 (n_193), .Y (n_23));
  AOI22X1 g2509__2346(.A0 (r2b_raddr[7]), .A1 (n_4), .B0 (l_raddr[7]),
       .B1 (n_193), .Y (n_22));
  AOI22X1 g2510__1666(.A0 (r2b_raddr[8]), .A1 (n_4), .B0 (l_raddr[8]),
       .B1 (n_193), .Y (n_21));
  AOI22X1 g2511__7410(.A0 (r2b_raddr[9]), .A1 (n_4), .B0 (l_raddr[9]),
       .B1 (n_193), .Y (n_20));
  AOI22X1 g2512__6417(.A0 (r2b_raddr[10]), .A1 (n_4), .B0
       (l_raddr[10]), .B1 (n_193), .Y (n_19));
  XNOR2X1 g2513__5477(.A (bank_row[7]), .B (r2b_raddr[7]), .Y (n_18));
  XNOR2X1 g2514__2398(.A (bank_row[10]), .B (r2b_raddr[10]), .Y (n_17));
  NOR4X1 g2515__5107(.A (tras_cntr[0]), .B (tras_cntr[1]), .C
       (tras_cntr[2]), .D (tras_cntr[3]), .Y (n_49));
  NOR2BX1 g2520__6260(.AN (xfr_ok), .B (n_189), .Y (n_15));
  NOR2X1 g2521__4319(.A (x2b_refresh), .B (n_220), .Y (n_16));
  NOR2BX1 g2522__8428(.AN (x2b_pre_ok), .B (n_189), .Y (n_11));
  NOR2BX1 g2523__5526(.AN (x2b_act_ok), .B (n_189), .Y (n_10));
  NOR2BX1 g2524__6783(.AN (x2b_rdok), .B (n_189), .Y (n_9));
  NOR2BX1 g2525__3680(.AN (x2b_wrok), .B (n_189), .Y (n_8));
  NOR2X1 g2526__1617(.A (n_2), .B (b2x_cmd[1]), .Y (n_14));
  NOR2BX1 g2527__2802(.AN (n_217), .B (x2b_refresh), .Y (n_13));
  INVX1 g2529(.A (n_218), .Y (n_7));
  INVX1 g2531(.A (n_194), .Y (n_5));
  CLKINVX4 g2532(.A (n_193), .Y (n_4));
  INVX1 g2533(.A (x2b_refresh), .Y (n_3));
  INVX1 g2534(.A (x2b_ack), .Y (n_2));
  INVX1 g2535(.A (n_189), .Y (n_1));
  XNOR2X1 dec_SUB_UNS_OP_g39__1705(.A (timer0[3]), .B
       (dec_SUB_UNS_OP_n_5), .Y (n_201));
  OAI2BB1X1 dec_SUB_UNS_OP_g40__5122(.A0N (timer0[2]), .A1N
       (dec_SUB_UNS_OP_n_3), .B0 (dec_SUB_UNS_OP_n_5), .Y (n_200));
  OR2XL dec_SUB_UNS_OP_g41__8246(.A (timer0[2]), .B
       (dec_SUB_UNS_OP_n_3), .Y (dec_SUB_UNS_OP_n_5));
  OAI2BB1X1 dec_SUB_UNS_OP_g42__7098(.A0N (timer0[1]), .A1N
       (dec_SUB_UNS_OP_n_1), .B0 (dec_SUB_UNS_OP_n_3), .Y (n_199));
  OR2XL dec_SUB_UNS_OP_g43__6131(.A (timer0[1]), .B
       (dec_SUB_UNS_OP_n_1), .Y (dec_SUB_UNS_OP_n_3));
  NAND2X1 dec_SUB_UNS_OP_g45__1881(.A (n_192), .B (dec_SUB_UNS_OP_n_0),
       .Y (dec_SUB_UNS_OP_n_1));
  INVX1 dec_SUB_UNS_OP_g46(.A (timer0[0]), .Y (dec_SUB_UNS_OP_n_0));
  XNOR2X1 dec_sub_210_41_g62__5115(.A (tras_cntr[3]), .B
       (dec_sub_210_41_n_2), .Y (n_197));
  OAI2BB1X1 dec_sub_210_41_g63__7482(.A0N (tras_cntr[2]), .A1N
       (dec_sub_210_41_n_0), .B0 (dec_sub_210_41_n_2), .Y (n_196));
  OR2XL dec_sub_210_41_g64__4733(.A (tras_cntr[2]), .B
       (dec_sub_210_41_n_0), .Y (dec_sub_210_41_n_2));
  OAI2BB1X1 dec_sub_210_41_g65__6161(.A0N (tras_cntr[1]), .A1N
       (tras_cntr[0]), .B0 (dec_sub_210_41_n_0), .Y (n_195));
  OR2XL dec_sub_210_41_g66__9315(.A (tras_cntr[1]), .B (tras_cntr[0]),
       .Y (dec_sub_210_41_n_0));
  INVXL g2536(.A (n_220), .Y (n_12));
  INVXL g2537(.A (dec_SUB_UNS_OP_n_1), .Y (n_198));
  INVXL g2538(.A (n_299), .Y (n_158));
  INVXL g2539(.A (n_109), .Y (n_128));
  NAND2BX1 g2(.AN (n_202), .B (n_148), .Y (n_299));
  OAI21X1 g2540(.A0 (x2b_ack), .A1 (n_217), .B0 (n_76), .Y (n_300));
  NAND2BX1 g2541(.AN (n_12), .B (bank_st[1]), .Y (n_301));
endmodule

