
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jul  3 2024 14:44:38 IST (Jul  3 2024 09:14:38 UTC)

// Verification Directory fv/async_fifo 

module async_fifo(wr_clk, wr_reset_n, wr_en, wr_data, full, afull,
     rd_clk, rd_reset_n, rd_en, empty, aempty, rd_data);
  input wr_clk, wr_reset_n, wr_en, rd_clk, rd_reset_n, rd_en;
  input [7:0] wr_data;
  output full, afull, empty, aempty;
  output [7:0] rd_data;
  wire wr_clk, wr_reset_n, wr_en, rd_clk, rd_reset_n, rd_en;
  wire [7:0] wr_data;
  wire full, afull, empty, aempty;
  wire [7:0] rd_data;
  wire [2:0] sync_wr_ptr_1;
  wire [2:0] sync_rd_ptr_1;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [2:0] rd_cnt;
  wire [2:0] wr_cnt;
  wire [2:0] rd_ptr;
  wire [2:0] grey_wr_ptr;
  wire [2:0] grey_rd_ptr;
  wire [2:0] wr_ptr;
  wire [2:0] wr_ptr_inc;
  wire [2:0] rd_ptr_inc;
  wire [2:0] sync_rd_ptr_0;
  wire [2:0] sync_wr_ptr_0;
  wire [7:0] rd_data_q;
  wire empty_q, full_q, \get_cnt_103_25:sub00192_n_0 ,
       \get_cnt_103_25:sub00192_n_1 , \get_cnt_103_25:sub00192_n_2 ,
       \get_cnt_103_25:sub00192_n_3 , \get_cnt_103_25:sub00192_n_5 ,
       \get_cnt_164_25:sub00192_n_0 ;
  wire \get_cnt_164_25:sub00192_n_1 , \get_cnt_164_25:sub00192_n_2 ,
       \get_cnt_164_25:sub00192_n_3 , \get_cnt_164_25:sub00192_n_5 ,
       inc_add_102_36_n_0, inc_add_162_36_n_0, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_64;
  INVXL g862(.A (n_51), .Y (empty));
  INVXL g861(.A (n_56), .Y (aempty));
  INVXL g860(.A (n_57), .Y (afull));
  XNOR2X1 g886__2398(.A (sync_wr_ptr_1[2]), .B (n_46), .Y (n_54));
  XNOR2X1 g887__5107(.A (sync_wr_ptr_1[0]), .B (sync_wr_ptr_1[1]), .Y
       (n_46));
  XOR2XL g888__6260(.A (sync_wr_ptr_1[1]), .B (sync_wr_ptr_1[2]), .Y
       (n_55));
  XNOR2X1 g889__4319(.A (sync_rd_ptr_1[2]), .B (n_45), .Y (n_52));
  XNOR2X1 g890__8428(.A (sync_rd_ptr_1[0]), .B (sync_rd_ptr_1[1]), .Y
       (n_45));
  XOR2XL g891__5526(.A (sync_rd_ptr_1[1]), .B (sync_rd_ptr_1[2]), .Y
       (n_53));
  NAND2X1 g950__6783(.A (n_42), .B (n_41), .Y (rd_data[2]));
  NAND2X1 g951__3680(.A (n_44), .B (n_37), .Y (rd_data[5]));
  NAND2X1 g952__1617(.A (n_40), .B (n_43), .Y (rd_data[7]));
  NAND2XL g953__2802(.A (n_39), .B (n_38), .Y (rd_data[1]));
  NAND2X1 g954__1705(.A (n_34), .B (n_31), .Y (rd_data[6]));
  NAND2X1 g955__5122(.A (n_32), .B (n_33), .Y (rd_data[0]));
  NAND2X1 g956__8246(.A (n_35), .B (n_36), .Y (rd_data[4]));
  NAND2XL g957__7098(.A (n_30), .B (n_29), .Y (rd_data[3]));
  AOI22X1 g958__6131(.A0 (\mem[2] [5]), .A1 (n_28), .B0 (\mem[3] [5]),
       .B1 (n_25), .Y (n_44));
  AOI22X1 g959__1881(.A0 (\mem[0] [7]), .A1 (n_26), .B0 (\mem[2] [7]),
       .B1 (n_28), .Y (n_43));
  AOI22X1 g960__5115(.A0 (\mem[2] [2]), .A1 (n_28), .B0 (\mem[3] [2]),
       .B1 (n_25), .Y (n_42));
  AOI22X1 g961__7482(.A0 (\mem[0] [2]), .A1 (n_26), .B0 (\mem[1] [2]),
       .B1 (n_27), .Y (n_41));
  AOI22X1 g962__4733(.A0 (\mem[1] [7]), .A1 (n_27), .B0 (\mem[3] [7]),
       .B1 (n_25), .Y (n_40));
  AOI22X1 g963__6161(.A0 (\mem[2] [1]), .A1 (n_28), .B0 (\mem[1] [1]),
       .B1 (n_27), .Y (n_39));
  AOI22X1 g964__9315(.A0 (\mem[0] [1]), .A1 (n_26), .B0 (\mem[3] [1]),
       .B1 (n_25), .Y (n_38));
  AOI22X1 g965__9945(.A0 (\mem[0] [5]), .A1 (n_26), .B0 (\mem[1] [5]),
       .B1 (n_27), .Y (n_37));
  AOI22X1 g966__2883(.A0 (\mem[0] [4]), .A1 (n_26), .B0 (\mem[1] [4]),
       .B1 (n_27), .Y (n_36));
  AOI22X1 g967__2346(.A0 (\mem[2] [4]), .A1 (n_28), .B0 (\mem[3] [4]),
       .B1 (n_25), .Y (n_35));
  AOI22X1 g968__1666(.A0 (\mem[2] [6]), .A1 (n_28), .B0 (\mem[3] [6]),
       .B1 (n_25), .Y (n_34));
  AOI22X1 g969__7410(.A0 (\mem[0] [0]), .A1 (n_26), .B0 (\mem[2] [0]),
       .B1 (n_28), .Y (n_33));
  AOI22X1 g970__6417(.A0 (\mem[1] [0]), .A1 (n_27), .B0 (\mem[3] [0]),
       .B1 (n_25), .Y (n_32));
  AOI22X1 g971__5477(.A0 (\mem[0] [6]), .A1 (n_26), .B0 (\mem[1] [6]),
       .B1 (n_27), .Y (n_31));
  AOI22X1 g972__2398(.A0 (\mem[2] [3]), .A1 (n_28), .B0 (\mem[1] [3]),
       .B1 (n_27), .Y (n_30));
  AOI22X1 g973__5107(.A0 (\mem[0] [3]), .A1 (n_26), .B0 (\mem[3] [3]),
       .B1 (n_25), .Y (n_29));
  NAND2X1 g974__6260(.A (rd_cnt[0]), .B (n_24), .Y (n_56));
  NAND3BXL g975__4319(.AN (wr_cnt[2]), .B (wr_cnt[0]), .C (wr_cnt[1]),
       .Y (n_57));
  OR3XL g976__8428(.A (rd_cnt[0]), .B (rd_cnt[2]), .C (rd_cnt[1]), .Y
       (n_51));
  NOR3BXL g977__5526(.AN (wr_cnt[2]), .B (wr_cnt[0]), .C (wr_cnt[1]),
       .Y (full));
  NOR2BX1 g978__6783(.AN (rd_ptr[1]), .B (rd_ptr[0]), .Y (n_28));
  NOR2BX1 g979__3680(.AN (rd_ptr[0]), .B (rd_ptr[1]), .Y (n_27));
  NOR2XL g980__1617(.A (rd_cnt[2]), .B (rd_cnt[1]), .Y (n_24));
  NOR2X1 g981__2802(.A (rd_ptr[1]), .B (rd_ptr[0]), .Y (n_26));
  AND2X1 g982__1705(.A (rd_ptr[1]), .B (rd_ptr[0]), .Y (n_25));
  DFFSHQX1 empty_q_reg(.SN (rd_reset_n), .CK (rd_clk), .D (n_23), .Q
       (empty_q));
  SDFFRHQX1 full_q_reg(.RN (wr_reset_n), .CK (wr_clk), .D (full_q), .SI
       (wr_en), .SE (n_21), .Q (full_q));
  SDFFQX1 \mem_reg[0][1] (.CK (wr_clk), .D (\mem[0] [1]), .SI
       (wr_data[1]), .SE (n_20), .Q (\mem[0] [1]));
  SDFFRHQX1 \grey_wr_ptr_reg[0] (.RN (wr_reset_n), .CK (wr_clk), .D
       (grey_wr_ptr[0]), .SI (n_11), .SE (wr_en), .Q (grey_wr_ptr[0]));
  SDFFRHQX1 \grey_rd_ptr_reg[1] (.RN (rd_reset_n), .CK (rd_clk), .D
       (grey_rd_ptr[1]), .SI (n_12), .SE (rd_en), .Q (grey_rd_ptr[1]));
  SDFFRHQX1 \grey_rd_ptr_reg[0] (.RN (rd_reset_n), .CK (rd_clk), .D
       (grey_rd_ptr[0]), .SI (n_10), .SE (rd_en), .Q (grey_rd_ptr[0]));
  SDFFQX1 \mem_reg[0][0] (.CK (wr_clk), .D (\mem[0] [0]), .SI
       (wr_data[0]), .SE (n_20), .Q (\mem[0] [0]));
  SDFFQX1 \mem_reg[3][4] (.CK (wr_clk), .D (wr_data[4]), .SI
       (\mem[3] [4]), .SE (n_19), .Q (\mem[3] [4]));
  SDFFQX1 \mem_reg[3][5] (.CK (wr_clk), .D (wr_data[5]), .SI
       (\mem[3] [5]), .SE (n_19), .Q (\mem[3] [5]));
  SDFFQX1 \mem_reg[3][6] (.CK (wr_clk), .D (wr_data[6]), .SI
       (\mem[3] [6]), .SE (n_19), .Q (\mem[3] [6]));
  SDFFQX1 \mem_reg[3][7] (.CK (wr_clk), .D (wr_data[7]), .SI
       (\mem[3] [7]), .SE (n_19), .Q (\mem[3] [7]));
  SDFFRHQX1 \grey_wr_ptr_reg[1] (.RN (wr_reset_n), .CK (wr_clk), .D
       (grey_wr_ptr[1]), .SI (n_9), .SE (wr_en), .Q (grey_wr_ptr[1]));
  SDFFQX1 \mem_reg[0][2] (.CK (wr_clk), .D (\mem[0] [2]), .SI
       (wr_data[2]), .SE (n_20), .Q (\mem[0] [2]));
  SDFFQX1 \mem_reg[0][3] (.CK (wr_clk), .D (\mem[0] [3]), .SI
       (wr_data[3]), .SE (n_20), .Q (\mem[0] [3]));
  SDFFQX1 \mem_reg[0][4] (.CK (wr_clk), .D (\mem[0] [4]), .SI
       (wr_data[4]), .SE (n_20), .Q (\mem[0] [4]));
  SDFFQX1 \mem_reg[0][5] (.CK (wr_clk), .D (\mem[0] [5]), .SI
       (wr_data[5]), .SE (n_20), .Q (\mem[0] [5]));
  SDFFQX1 \mem_reg[0][6] (.CK (wr_clk), .D (\mem[0] [6]), .SI
       (wr_data[6]), .SE (n_20), .Q (\mem[0] [6]));
  SDFFQX1 \mem_reg[0][7] (.CK (wr_clk), .D (\mem[0] [7]), .SI
       (wr_data[7]), .SE (n_20), .Q (\mem[0] [7]));
  SDFFQX1 \mem_reg[1][0] (.CK (wr_clk), .D (wr_data[0]), .SI
       (\mem[1] [0]), .SE (n_13), .Q (\mem[1] [0]));
  SDFFQX1 \mem_reg[1][1] (.CK (wr_clk), .D (wr_data[1]), .SI
       (\mem[1] [1]), .SE (n_13), .Q (\mem[1] [1]));
  MX2XL g1009__5122(.A (rd_en), .B (empty_q), .S0 (n_64), .Y (n_23));
  SDFFQX1 \mem_reg[1][3] (.CK (wr_clk), .D (wr_data[3]), .SI
       (\mem[1] [3]), .SE (n_13), .Q (\mem[1] [3]));
  SDFFQX1 \mem_reg[1][4] (.CK (wr_clk), .D (wr_data[4]), .SI
       (\mem[1] [4]), .SE (n_13), .Q (\mem[1] [4]));
  SDFFQX1 \mem_reg[1][5] (.CK (wr_clk), .D (wr_data[5]), .SI
       (\mem[1] [5]), .SE (n_13), .Q (\mem[1] [5]));
  SDFFQX1 \mem_reg[1][6] (.CK (wr_clk), .D (wr_data[6]), .SI
       (\mem[1] [6]), .SE (n_13), .Q (\mem[1] [6]));
  SDFFQX1 \mem_reg[1][7] (.CK (wr_clk), .D (wr_data[7]), .SI
       (\mem[1] [7]), .SE (n_13), .Q (\mem[1] [7]));
  SDFFQX1 \mem_reg[2][0] (.CK (wr_clk), .D (wr_data[0]), .SI
       (\mem[2] [0]), .SE (n_14), .Q (\mem[2] [0]));
  SDFFQX1 \mem_reg[2][1] (.CK (wr_clk), .D (wr_data[1]), .SI
       (\mem[2] [1]), .SE (n_14), .Q (\mem[2] [1]));
  SDFFQX1 \mem_reg[2][2] (.CK (wr_clk), .D (wr_data[2]), .SI
       (\mem[2] [2]), .SE (n_14), .Q (\mem[2] [2]));
  SDFFQX1 \mem_reg[1][2] (.CK (wr_clk), .D (wr_data[2]), .SI
       (\mem[1] [2]), .SE (n_13), .Q (\mem[1] [2]));
  SDFFQX1 \mem_reg[2][4] (.CK (wr_clk), .D (wr_data[4]), .SI
       (\mem[2] [4]), .SE (n_14), .Q (\mem[2] [4]));
  SDFFQX1 \mem_reg[2][5] (.CK (wr_clk), .D (wr_data[5]), .SI
       (\mem[2] [5]), .SE (n_14), .Q (\mem[2] [5]));
  SDFFQX1 \mem_reg[2][6] (.CK (wr_clk), .D (wr_data[6]), .SI
       (\mem[2] [6]), .SE (n_14), .Q (\mem[2] [6]));
  SDFFQX1 \mem_reg[2][7] (.CK (wr_clk), .D (wr_data[7]), .SI
       (\mem[2] [7]), .SE (n_14), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[3][0] (.CK (wr_clk), .D (wr_data[0]), .SI
       (\mem[3] [0]), .SE (n_19), .Q (\mem[3] [0]));
  SDFFQX1 \mem_reg[3][1] (.CK (wr_clk), .D (wr_data[1]), .SI
       (\mem[3] [1]), .SE (n_19), .Q (\mem[3] [1]));
  SDFFQX1 \mem_reg[3][2] (.CK (wr_clk), .D (wr_data[2]), .SI
       (\mem[3] [2]), .SE (n_19), .Q (\mem[3] [2]));
  SDFFQX1 \mem_reg[3][3] (.CK (wr_clk), .D (wr_data[3]), .SI
       (\mem[3] [3]), .SE (n_19), .Q (\mem[3] [3]));
  SDFFQX1 \mem_reg[2][3] (.CK (wr_clk), .D (wr_data[3]), .SI
       (\mem[2] [3]), .SE (n_14), .Q (\mem[2] [3]));
  DFFRHQX1 \wr_ptr_reg[2] (.RN (wr_reset_n), .CK (wr_clk), .D (n_16),
       .Q (wr_ptr[2]));
  DFFRHQX1 \rd_ptr_reg[2] (.RN (rd_reset_n), .CK (rd_clk), .D (n_17),
       .Q (rd_ptr[2]));
  DFFRHQX1 \grey_wr_ptr_reg[2] (.RN (wr_reset_n), .CK (wr_clk), .D
       (n_18), .Q (grey_wr_ptr[2]));
  DFFRHQX1 \grey_rd_ptr_reg[2] (.RN (rd_reset_n), .CK (rd_clk), .D
       (n_15), .Q (grey_rd_ptr[2]));
  SDFFRHQX1 \wr_ptr_reg[1] (.RN (wr_reset_n), .CK (wr_clk), .D
       (wr_ptr[1]), .SI (wr_ptr_inc[1]), .SE (wr_en), .Q (wr_ptr[1]));
  OAI32X1 g1034__7098(.A0 (wr_cnt[2]), .A1 (n_3), .A2 (wr_en), .B0
       (n_0), .B1 (n_57), .Y (n_21));
  SDFFRHQX1 \rd_ptr_reg[1] (.RN (rd_reset_n), .CK (rd_clk), .D
       (rd_ptr[1]), .SI (rd_ptr_inc[1]), .SE (rd_en), .Q (rd_ptr[1]));
  SDFFRHQX1 \rd_ptr_reg[0] (.RN (rd_reset_n), .CK (rd_clk), .D (rd_en),
       .SI (n_1), .SE (rd_ptr[0]), .Q (rd_ptr[0]));
  SDFFRHQX1 \wr_ptr_reg[0] (.RN (wr_reset_n), .CK (wr_clk), .D (wr_en),
       .SI (n_0), .SE (wr_ptr[0]), .Q (wr_ptr[0]));
  OAI2BB1X1 g1038__6131(.A0N (grey_wr_ptr[2]), .A1N (n_0), .B0 (n_8),
       .Y (n_18));
  OAI2BB1X1 g1039__1881(.A0N (rd_ptr[2]), .A1N (n_1), .B0 (n_7), .Y
       (n_17));
  OAI2BB1X1 g1040__5115(.A0N (wr_ptr[2]), .A1N (n_0), .B0 (n_8), .Y
       (n_16));
  OAI2BB1X1 g1041__7482(.A0N (grey_rd_ptr[2]), .A1N (n_1), .B0 (n_7),
       .Y (n_15));
  NOR3X1 g1042__4733(.A (n_0), .B (wr_ptr[0]), .C (wr_ptr[1]), .Y
       (n_20));
  NAND2BX1 g1043__6161(.AN (n_6), .B (wr_ptr[0]), .Y (n_19));
  XOR2XL g1044__9315(.A (rd_ptr_inc[1]), .B (rd_ptr_inc[2]), .Y (n_12));
  XNOR2X1 g1045__9945(.A (wr_ptr[0]), .B (wr_ptr_inc[1]), .Y (n_11));
  XNOR2X1 g1046__2883(.A (rd_ptr[0]), .B (rd_ptr_inc[1]), .Y (n_10));
  XOR2XL g1047__2346(.A (wr_ptr_inc[1]), .B (wr_ptr_inc[2]), .Y (n_9));
  OR3X1 g1048__1666(.A (n_0), .B (n_5), .C (wr_ptr[0]), .Y (n_14));
  OR3X1 g1049__7410(.A (n_0), .B (n_2), .C (wr_ptr[1]), .Y (n_13));
  DFFRHQX1 \sync_rd_ptr_0_reg[2] (.RN (wr_reset_n), .CK (wr_clk), .D
       (grey_rd_ptr[2]), .Q (sync_rd_ptr_0[2]));
  DFFRHQX1 \sync_wr_ptr_1_reg[1] (.RN (rd_reset_n), .CK (rd_clk), .D
       (sync_wr_ptr_0[1]), .Q (sync_wr_ptr_1[1]));
  DFFRHQX1 \sync_rd_ptr_0_reg[1] (.RN (wr_reset_n), .CK (wr_clk), .D
       (grey_rd_ptr[1]), .Q (sync_rd_ptr_0[1]));
  DFFRHQX1 \sync_rd_ptr_1_reg[0] (.RN (wr_reset_n), .CK (wr_clk), .D
       (sync_rd_ptr_0[0]), .Q (sync_rd_ptr_1[0]));
  DFFRHQX1 \sync_rd_ptr_1_reg[1] (.RN (wr_reset_n), .CK (wr_clk), .D
       (sync_rd_ptr_0[1]), .Q (sync_rd_ptr_1[1]));
  DFFRHQX1 \sync_wr_ptr_0_reg[0] (.RN (rd_reset_n), .CK (rd_clk), .D
       (grey_wr_ptr[0]), .Q (sync_wr_ptr_0[0]));
  DFFRHQX1 \sync_wr_ptr_0_reg[2] (.RN (rd_reset_n), .CK (rd_clk), .D
       (grey_wr_ptr[2]), .Q (sync_wr_ptr_0[2]));
  DFFRHQX1 \sync_wr_ptr_1_reg[0] (.RN (rd_reset_n), .CK (rd_clk), .D
       (sync_wr_ptr_0[0]), .Q (sync_wr_ptr_1[0]));
  DFFRHQX1 \sync_rd_ptr_0_reg[0] (.RN (wr_reset_n), .CK (wr_clk), .D
       (grey_rd_ptr[0]), .Q (sync_rd_ptr_0[0]));
  DFFRHQX1 \sync_wr_ptr_1_reg[2] (.RN (rd_reset_n), .CK (rd_clk), .D
       (sync_wr_ptr_0[2]), .Q (sync_wr_ptr_1[2]));
  DFFRHQX1 \sync_rd_ptr_1_reg[2] (.RN (wr_reset_n), .CK (wr_clk), .D
       (sync_rd_ptr_0[2]), .Q (sync_rd_ptr_1[2]));
  DFFQXL \rd_data_q_reg[6] (.CK (rd_clk), .D (rd_data[6]), .Q
       (rd_data_q[6]));
  DFFQXL \rd_data_q_reg[5] (.CK (rd_clk), .D (rd_data[5]), .Q
       (rd_data_q[5]));
  DFFQXL \rd_data_q_reg[0] (.CK (rd_clk), .D (rd_data[0]), .Q
       (rd_data_q[0]));
  DFFQXL \rd_data_q_reg[1] (.CK (rd_clk), .D (rd_data[1]), .Q
       (rd_data_q[1]));
  DFFQXL \rd_data_q_reg[2] (.CK (rd_clk), .D (rd_data[2]), .Q
       (rd_data_q[2]));
  DFFQXL \rd_data_q_reg[4] (.CK (rd_clk), .D (rd_data[4]), .Q
       (rd_data_q[4]));
  DFFQXL \rd_data_q_reg[3] (.CK (rd_clk), .D (rd_data[3]), .Q
       (rd_data_q[3]));
  DFFQXL \rd_data_q_reg[7] (.CK (rd_clk), .D (rd_data[7]), .Q
       (rd_data_q[7]));
  NAND2X1 g1069__6417(.A (wr_ptr[1]), .B (wr_en), .Y (n_6));
  DFFRHQX1 \sync_wr_ptr_0_reg[1] (.RN (rd_reset_n), .CK (rd_clk), .D
       (grey_wr_ptr[1]), .Q (sync_wr_ptr_0[1]));
  NAND2X1 g1071__5477(.A (wr_en), .B (wr_ptr_inc[2]), .Y (n_8));
  NAND2X1 g1072__2398(.A (rd_en), .B (rd_ptr_inc[2]), .Y (n_7));
  INVX1 g1073(.A (wr_ptr[1]), .Y (n_5));
  INVX1 g1074(.A (n_56), .Y (n_4));
  INVX1 g1075(.A (full_q), .Y (n_3));
  INVX1 g1076(.A (wr_ptr[0]), .Y (n_2));
  INVX1 g1077(.A (rd_en), .Y (n_1));
  INVX1 g1078(.A (wr_en), .Y (n_0));
  XOR2XL \get_cnt_103_25:sub00192_g96__5107 (.A
       (\get_cnt_103_25:sub00192_n_3 ), .B
       (\get_cnt_103_25:sub00192_n_5 ), .Y (wr_cnt[2]));
  ADDFX1 \get_cnt_103_25:sub00192_g97__6260 (.A
       (\get_cnt_103_25:sub00192_n_2 ), .B (wr_ptr[1]), .CI
       (\get_cnt_103_25:sub00192_n_0 ), .CO
       (\get_cnt_103_25:sub00192_n_5 ), .S (wr_cnt[1]));
  OAI2BB1X1 \get_cnt_103_25:sub00192_g98__4319 (.A0N (wr_ptr[0]), .A1N
       (\get_cnt_103_25:sub00192_n_1 ), .B0
       (\get_cnt_103_25:sub00192_n_2 ), .Y (wr_cnt[0]));
  XNOR2X1 \get_cnt_103_25:sub00192_g99__8428 (.A (wr_ptr[2]), .B
       (sync_rd_ptr_1[2]), .Y (\get_cnt_103_25:sub00192_n_3 ));
  NAND2BX1 \get_cnt_103_25:sub00192_g100__5526 (.AN (wr_ptr[0]), .B
       (n_52), .Y (\get_cnt_103_25:sub00192_n_2 ));
  INVX1 \get_cnt_103_25:sub00192_g101 (.A (n_52), .Y
       (\get_cnt_103_25:sub00192_n_1 ));
  INVX1 \get_cnt_103_25:sub00192_g102 (.A (n_53), .Y
       (\get_cnt_103_25:sub00192_n_0 ));
  XOR2XL \get_cnt_164_25:sub00192_g96__6783 (.A
       (\get_cnt_164_25:sub00192_n_3 ), .B
       (\get_cnt_164_25:sub00192_n_5 ), .Y (rd_cnt[2]));
  ADDFX1 \get_cnt_164_25:sub00192_g97__3680 (.A
       (\get_cnt_164_25:sub00192_n_2 ), .B (n_55), .CI
       (\get_cnt_164_25:sub00192_n_0 ), .CO
       (\get_cnt_164_25:sub00192_n_5 ), .S (rd_cnt[1]));
  OAI2BB1X1 \get_cnt_164_25:sub00192_g98__1617 (.A0N (n_54), .A1N
       (\get_cnt_164_25:sub00192_n_1 ), .B0
       (\get_cnt_164_25:sub00192_n_2 ), .Y (rd_cnt[0]));
  XNOR2X1 \get_cnt_164_25:sub00192_g99__2802 (.A (sync_wr_ptr_1[2]), .B
       (rd_ptr[2]), .Y (\get_cnt_164_25:sub00192_n_3 ));
  OR2X1 \get_cnt_164_25:sub00192_g100__1705 (.A
       (\get_cnt_164_25:sub00192_n_1 ), .B (n_54), .Y
       (\get_cnt_164_25:sub00192_n_2 ));
  INVX1 \get_cnt_164_25:sub00192_g101 (.A (rd_ptr[0]), .Y
       (\get_cnt_164_25:sub00192_n_1 ));
  INVX1 \get_cnt_164_25:sub00192_g102 (.A (rd_ptr[1]), .Y
       (\get_cnt_164_25:sub00192_n_0 ));
  XNOR2X1 inc_add_102_36_g23__5122(.A (wr_ptr[2]), .B
       (inc_add_102_36_n_0), .Y (wr_ptr_inc[2]));
  OA21X1 inc_add_102_36_g24__8246(.A0 (wr_ptr[1]), .A1 (wr_ptr[0]), .B0
       (inc_add_102_36_n_0), .Y (wr_ptr_inc[1]));
  NAND2X1 inc_add_102_36_g25__7098(.A (wr_ptr[1]), .B (wr_ptr[0]), .Y
       (inc_add_102_36_n_0));
  XNOR2X1 inc_add_162_36_g23__6131(.A (rd_ptr[2]), .B
       (inc_add_162_36_n_0), .Y (rd_ptr_inc[2]));
  OA21X1 inc_add_162_36_g24__1881(.A0 (rd_ptr[1]), .A1 (rd_ptr[0]), .B0
       (inc_add_162_36_n_0), .Y (rd_ptr_inc[1]));
  NAND2X1 inc_add_162_36_g25__5115(.A (rd_ptr[1]), .B (rd_ptr[0]), .Y
       (inc_add_162_36_n_0));
  AOI21X1 g2(.A0 (n_51), .A1 (n_1), .B0 (n_4), .Y (n_64));
endmodule

